### ISSUE TITLE
get-agent-state state null

### ISSUE THREAD

**Issue by sangkyuleeKOR** [stitionai/devika#103]
The installation appears to have been successful
The api key was also written in config.toml, but no matter how many messages I sent to the UI, there was no response. 
What are the potential problems?

![devika](https://github.com/stitionai/devika/assets/44499503/e9aa4a5a-329f-48cd-b775-2afb9fb0b913)
![ollama](https://github.com/stitionai/devika/assets/44499503/d4930010-73da-4a48-81a2-867805d40185)
![ui](https://github.com/stitionai/devika/assets/44499503/12a18a75-6341-46b3-a5cd-edd11bcbd105)

It seems the agent is not connected to the project.

**Comment by Mason-zy** [comment]
edit cody.py "
        response = response.strip()

        response = response.split("```", 1)[1]
        response = response[:response.rfind("```")]"

**Comment by sangkyuleeKOR** [comment]
thanks for your reply! I edited ~~~ to ```, and then I tried it. But it still hangs indefinitely.

**Comment by Manoj-Madushantha** [comment]
I am also facing this problem? any suggestions?

**Comment by abinovarghese** [comment]
same here

**Comment by Wenqiaog** [comment]
me too

**Comment by miterfrants** [comment]
edit MessageInput.svelte handleSendMessage function
```js
async function handleSendMessage() {
    const projectName = localStorage.getItem("selectedProject");

    if (!projectName) {
      alert("Please select a project first!");
      return;
    }

    if (messageInput.trim() === "") {
      messageInput = "";
      return;
    }

    if (isAgentActive) {
      console.log("Sending message", messageInput);
      await sendMessage(messageInput);
      messageInput = "";
    }
    
    console.log("Executing agent", messageInput);
    await executeAgent(messageInput);
    messageInput = "";

  }
 ```

**Comment by ndizeye-patrick** [comment]
this can be better



async function handleSendMessage() {
    const projectName = localStorage.getItem("selectedProject");

    if (!projectName) {
        alert("Please select a project first!");
        return;
    }

    const trimmedInput = messageInput.trim(); // Trim the input to remove whitespace

    if (trimmedInput === "") {
        // Clear the message input if it's empty or contains only whitespace
        messageInput = "";
        return;
    }

    if (isAgentActive) {
        console.log("Sending message", trimmedInput);
        await sendMessage(trimmedInput);
    } else {
        console.log("Executing agent", trimmedInput);
        await executeAgent(trimmedInput);
    }

    // Clear the message input after sending or executing
    messageInput = "";
}

**Comment by kiswigu2** [comment]
not working

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
