### ISSUE TITLE
get-agent-state POST - Response: {"state":null} - NO RESPONSE

### ISSUE THREAD

**Issue by sumit171204** [stitionai/devika#106]
@
![Screenshot 2024-03-24 144851](https://github.com/stitionai/devika/assets/71690208/e5c0ecef-168d-45da-b5ac-f5fe57a91f6d)
![image](https://github.com/stitionai/devika/assets/71690208/a5e1bceb-e659-4bd4-8392-ab4d5e633677)
NO Response

**Comment by feirydraco** [comment]
How did you solve this?

**Comment by sumit171204** [comment]
I added Gemini Models, now currently working only on gemini models.

**Comment by byomi** [comment]
i still have this problme how to solve it??

**Comment by sainudheenp** [comment]
@sumit171204 i still have this problme how to solve it??
