### ISSUE TITLE
INSTALLED EVERYTHING BUT IT IS NOT CREATING A PROJECT

### ISSUE THREAD

**Issue by bajwa4200** [stitionai/devika#108]
When i select create new project it just does not do anything at all and when i type in the chat it says "Select a project" , is there something i missed during my installation how to fix this.

**Comment by ketangangal** [comment]
Hello @bajwa4200 , 

Have two terminal Open. 

1. Terminal One : Exec these cmd to start ui server.

```
cd ui/
bun install
bun run dev
```

2. Terminal Two : Exec these cmd to start flask backend. 

```
python devika.py 
```

**Comment by bajwa4200** [comment]
I executed the commands mentioned for terminal one they worked fine but in terminal 2 :
 python3 devika.py
Traceback (most recent call last):
  File "/home/dev/Documents/devika/devika.py", line 24, in <module>
    logger = Logger()
  File "/home/dev/Documents/devika/src/logger.py", line 12, in __init__
    self.logger = LogInit(pathName=logs_dir + "/devika_agent.log", console=True, colors=True)
  File "/home/dev/.local/lib/python3.10/site-packages/fastlogging/fastlogging.py", line 540, in LogInit
    logger = GetLogger(domain, level, pathName, maxSize, backupCnt, console, indent, server, connect)
  File "/home/dev/.local/lib/python3.10/site-packages/fastlogging/fastlogging.py", line 520, in GetLogger
    logger = domains[domain] = Logger(domain, level, pathName, maxSize, backupCnt, console, indent, server, connect)
  File "/home/dev/.local/lib/python3.10/site-packages/fastlogging/fastlogging.py", line 176, in __init__
    self.F = open(pathName, "a", encoding=Logger.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/devika_agent.log'

**Comment by bajwa4200** [comment]
I executed the commands mentioned for terminal one they worked fine but in terminal 2 :
 python3 devika.py
Traceback (most recent call last):
  File "/home/dev/Documents/devika/devika.py", line 24, in <module>
    logger = Logger()
  File "/home/dev/Documents/devika/src/logger.py", line 12, in __init__
    self.logger = LogInit(pathName=logs_dir + "/devika_agent.log", console=True, colors=True)
  File "/home/dev/.local/lib/python3.10/site-packages/fastlogging/fastlogging.py", line 540, in LogInit
    logger = GetLogger(domain, level, pathName, maxSize, backupCnt, console, indent, server, connect)
  File "/home/dev/.local/lib/python3.10/site-packages/fastlogging/fastlogging.py", line 520, in GetLogger
    logger = domains[domain] = Logger(domain, level, pathName, maxSize, backupCnt, console, indent, server, connect)
  File "/home/dev/.local/lib/python3.10/site-packages/fastlogging/fastlogging.py", line 176, in __init__
    self.F = open(pathName, "a", encoding=Logger.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/devika_agent.log'

**Comment by angeloluidens** [comment]
I used one Terminal, starting the Backend with "python devika.py &", sends this process to the background and releases the Terminal for executing the commands to start the UI.

**Comment by kimsama** [comment]
> I used one Terminal, starting the Backend with "python devika.py &", sends this process to the background and releases the Terminal for executing the commands to start the UI (those in your Termine One).
> 
> Yet, I encountered the same issue: I cannot Create a project. Some of the items on the UI work either, such as entering a prompt, except that Devika cannot execute a prompt without a project defined.

Same on here.

**Comment by ketangangal** [comment]
Hello @kimsama , @angeloluidens ,

UI is buggy but you can try invoking api from postman.

**Comment by codevladdo** [comment]
Just thought i'd add - running into the same issue ...

**Comment by ARajgor** [comment]
fetch the latest changes.

**Comment by visaeon** [comment]
Latest version installed and i have the same error 

Ollama running
Backend running 
and frontend 

but cant create a new project still

**Comment by ARajgor** [comment]
share logs

> Latest version installed and i have the same error
> 
> Ollama running Backend running and frontend
> 
> but cant create a new project still
