### ISSUE TITLE
Interface not working on Windows using WSL no errors

### ISSUE THREAD

**Issue by Orsso** [stitionai/devika#113]
Hello, after following installation recommandations, it compile with no error but it result on the interface not working (no any buttons respond when being clicked) and i basically can't do anything. Maybe i did something wrong. Here are some screenshot of my terminal and web ui.  I am not used to WSL utilisation, i just installed it but i don't know if it require more manipulations in order to work as intended. Thank you by advance for your help to run this promising project on my computer ! :) 
![image](https://github.com/stitionai/devika/assets/106078665/f9514893-3367-4052-8d68-587e6fd13e1f)
![image](https://github.com/stitionai/devika/assets/106078665/d9648359-32b6-4417-978b-f29fc47b804e)
![image](https://github.com/stitionai/devika/assets/106078665/4a391da1-6b70-4ef9-bd9d-04c04355fd84)

**Comment by kimsama** [comment]
Same on me but I installed WIndows not WSL.

**Comment by Drlordbasil** [comment]
Same issue here, WSL anthony@MSI:~/devika$ ollama serve
git clone https://github.com/stitionai/devika.git
cd devika/
uv venv
uv pip install -r requirements.txt
cd ui/
bun install
bun run dev
python3 devika.py
Error: listen tcp 127.0.0.1:11434: bind: address already in use
Cloning into 'devika'...
remote: Enumerating objects: 251, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 251 (delta 43), reused 24 (delta 18), pack-reused 178
Receiving objects: 100% (251/251), 5.23 MiB | 13.10 MiB/s, done.
Resolving deltas: 100% (72/72), done.
Using Python 3.10.12 interpreter at: /usr/bin/python3
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
Resolved 117 packages in 519ms
Installed 117 packages in 370ms
 + annotated-types==0.6.0
 + anthropic==0.21.3
 + anyio==4.3.0
 + arabic-reshaper==3.0.0
 + asn1crypto==1.5.1
 + beautifulsoup4==4.12.3
 + blinker==1.7.0
 + certifi==2024.2.2
 + cffi==1.16.0
 + chardet==5.2.0
 + charset-normalizer==3.3.2
 + click==8.1.7
 + colorama==0.4.6
 + cryptography==42.0.5
 + cssselect2==0.7.0
 + distro==1.9.0
 + exceptiongroup==1.2.0
 + fastlogging==1.0.0
 + filelock==3.13.1
 + flask==3.0.2
 + flask-cors==4.0.0
 + fsspec==2024.3.1
 + gitdb==4.0.11
 + gitpython==3.1.42
 + greenlet==3.0.3
 + h11==0.14.0
 + html5lib==1.1
 + httpcore==1.0.4
 + httpx==0.25.2
 + huggingface-hub==0.21.4
 + idna==3.6
 + iniconfig==2.0.0
 + itsdangerous==2.1.2
 + jinja2==3.1.3
 + joblib==1.3.2
 + keybert==0.8.4
 + lxml==5.1.0
 + markdown==3.6
 + markdown-it-py==3.0.0
 + markdownify==0.11.6
 + markupsafe==2.1.5
 + mdurl==0.1.2
 + mistletoe==1.3.0
 + mpmath==1.3.0
 + netlify-py==0.1.0
 + networkx==3.2.1
 + numpy==1.26.4
 + nvidia-cublas-cu12==12.1.3.1
 + nvidia-cuda-cupti-cu12==12.1.105
 + nvidia-cuda-nvrtc-cu12==12.1.105
 + nvidia-cuda-runtime-cu12==12.1.105
 + nvidia-cudnn-cu12==8.9.2.26
 + nvidia-cufft-cu12==11.0.2.54
 + nvidia-curand-cu12==10.3.2.106
 + nvidia-cusolver-cu12==11.4.5.107
 + nvidia-cusparse-cu12==12.1.0.106
 + nvidia-nccl-cu12==2.19.3
 + nvidia-nvjitlink-cu12==12.4.99
 + nvidia-nvtx-cu12==12.1.105
 + ollama==0.1.7
 + openai==1.14.2
 + oscrypto==1.3.0
 + packaging==24.0
 + pdfminer-six==20231228
 + pillow==10.2.0
 + playwright==1.42.0
 + pluggy==1.4.0
 + pycparser==2.21
 + pydantic==2.6.4
 + pydantic-core==2.16.3
 + pyee==11.0.1
 + pygments==2.17.2
 + pyhanko==0.23.1
 + pyhanko-certvalidator==0.26.3
 + pypdf==4.1.0
 + pypng==0.20220715.0
 + pytest==8.1.1
 + pytest-base-url==2.1.0
 + pytest-playwright==0.4.4
 + python-bidi==0.4.2
 + python-slugify==8.0.4
 + pyyaml==6.0.1
 + qrcode==7.4.2
 + regex==2023.12.25
 + reportlab==4.0.9
 + requests==2.31.0
 + rich==13.7.1
 + safetensors==0.4.2
 + scikit-learn==1.4.1.post1
 + scipy==1.12.0
 + sentence-transformers==2.6.0
 + six==1.16.0
 + smmap==5.0.1
 + sniffio==1.3.1
 + soupsieve==2.5
 + sqlalchemy==2.0.29
 + sqlmodel==0.0.16
 + svglib==1.5.1
 + sympy==1.12
 + text-unidecode==1.3
 + threadpoolctl==3.4.0
 + tiktoken==0.6.0
 + tinycss2==1.2.1
 + tokenizers==0.15.2
 + toml==0.10.2
 + tomli==2.0.1
 + torch==2.2.1
 + tqdm==4.66.2
 + transformers==4.39.1
 + triton==2.2.0
 + typing-extensions==4.10.0
 + tzlocal==5.2
 + uritools==4.0.2
 + urllib3==1.26.15
 + webencodings==0.5.1
 + werkzeug==3.0.1
 + xhtml2pdf==0.2.15
bun install v1.0.35 (940448d6)

 + @sveltejs/adapter-auto@3.1.1
 + @sveltejs/kit@2.5.4
 + @sveltejs/vite-plugin-svelte@3.0.2
 + autoprefixer@10.4.19
 + postcss@8.4.38
 + postcss-load-config@5.0.3
 + svelte@4.2.12
 + tailwindcss@3.4.1
 + vite@5.2.2
 + xterm@5.3.0
 + xterm-addon-fit@0.8.0

 163 packages installed [1.71s]
$ vite dev
Forced re-optimization of dependencies

  VITE v5.2.2  ready in 443 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
10:39:15 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:115:10 A11y: '#' is not a valid href attribute
10:39:15 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:124:14 A11y: '#' is not a valid href attribute
10:39:15 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:186:16 A11y: '#' is not a valid href attribute
10:39:16 AM [vite] ✨ new dependencies optimized: xterm
10:39:16 AM [vite] ✨ optimized dependencies changed. reloading
10:39:16 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:115:10 A11y: '#' is not a valid href attribute
10:39:16 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:124:14 A11y: '#' is not a valid href attribute
10:39:16 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:186:16 A11y: '#' is not a valid href attribute
10:39:16 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:115:10 A11y: '#' is not a valid href attribute
10:39:16 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:124:14 A11y: '#' is not a valid href attribute
10:39:16 AM [vite-plugin-svelte] /home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:186:16 A11y: '#' is not a valid href attribute

**Comment by Drlordbasil** [comment]
NOTE:I even tried fresh installing/changing config, but its this file:
/home/anthony/devika/devika/ui/src/lib/components/ControlPanel.svelte:186:16


Which       <div class="py-1" role="none">
        <a
          href="#"
          class="text-white block px-4 py-2 text-sm hover:bg-slate-700"
          on:click|preventDefault={createNewProject}
        >
        
        is the issue

**Comment by Drlordbasil** [comment]
> Same on me but I installed WIndows not WSL.

Windows doesnt have BUN support yet sadly.

**Comment by Drlordbasil** [comment]
Fixed with separate terminals IE:
first is the BUN UI and all that, second terminal is simply running devika/devika.py
Fixed WSL issues.

**Comment by kimsama** [comment]
> > Same on me but I installed WIndows not WSL.
> 
> 
> 
> Windows doesnt have BUN support yet sadly. 

What about with WSL, especially WEL2? Is that OK?

**Comment by Drlordbasil** [comment]
> > > Same on me but I installed WIndows not WSL.
> > 
> > 
> > Windows doesnt have BUN support yet sadly.
> 
> What about with WSL, especially WEL2? Is that OK?

Yes bun is easily installed using ubuntu/visual studio code WSL or just the WSL terminal. still need the 2 terminals though. :D

**Comment by Drlordbasil** [comment]
> > Fixed with separate terminals IE: first is the BUN UI and all that, second terminal is simply running devika/devika.py Fixed WSL issues.
> 
> How you fixed that issue in windows without using WSL?

Not possible to use bun yet on regular windows.

**Comment by DiDisama317** [comment]
Same Issue with Windows. I used the experimental version of BUN, and everything was going well until I tried to run the code, I tried to start the UI first and then the server but still no response.

**Comment by Orsso** [comment]
> Fixed with separate terminals IE: first is the BUN UI and all that, second terminal is simply running devika/devika.py Fixed WSL issues.

Same issue with separated terminals

**Comment by Drlordbasil** [comment]
> > Fixed with separate terminals IE: first is the BUN UI and all that, second terminal is simply running devika/devika.py Fixed WSL issues.
> 
> Same issue with separated terminals

Can you possibly send more info like pip freeze? uv/bun both installed? Do you like pie or cake?

**Comment by iAstrodude** [comment]
** CMD**

>> ollama 
if its already run or getting freeze than kill their process using
>> taskkill /IM ollama.exe /F

>>start ollama  

it will resolve the issue

**Comment by Jmenotts** [comment]
having same issues on windows 10 tried powershell and gitbash even tried different ports not sure whats going off

**Comment by Balu027** [comment]
Same issue here with experimental windows build

**Comment by ARajgor** [comment]
fetch the latest changes. I also use windows 11 and install bun(experimental) and works perfectly fine with node 20.9.0.

tell me if it's help or not

**Comment by Balu027** [comment]
I updated to the latest one, now it's even worse :D Now http://localhost:3000/ is just a blank screen.
![devika](https://github.com/stitionai/devika/assets/26222275/93935b9a-3a01-462f-9a4b-90ad40c677cd)

**Comment by ARajgor** [comment]
share the network log and console log from browser also which node version?

**Comment by Balu027** [comment]
It's a bit weird. There are two options: it's either 'loading' instantly, looks like it finished loading, in this case I have a totally empty console log and a pretty populated network log.
![console log completed](https://github.com/stitionai/devika/assets/26222275/553c113b-5a28-4a77-81b8-7d639955fbac)
![network_completed_1](https://github.com/stitionai/devika/assets/26222275/6f96a30f-5e53-418e-81ae-8eec050d3363)
![network_completed_2](https://github.com/stitionai/devika/assets/26222275/6fc0f6b0-fbdc-44e0-a65d-0b37863b47b0)

If I try to reload it again, it just keeps working (the working icon is spinning indefinitely). The console log is still empty. Network log only has a localhost.
![network_working](https://github.com/stitionai/devika/assets/26222275/e4b7dd09-88b3-45bf-ab12-b7b7cf2224ad)

If I press stop, however, I get a cancelled localhost and an error in the console.
![network_stopped](https://github.com/stitionai/devika/assets/26222275/226ef569-8d90-4464-af2d-20c541fc49fb)
![console_stopped](https://github.com/stitionai/devika/assets/26222275/76abd9c6-771b-4bce-8460-c0e9cbbc97e8)

Where can I see the node version?

**Comment by ARajgor** [comment]
Fetch the latest changes and do a clean install.

**Comment by Balu027** [comment]
When I do the bun run start, I get this:

$ vite build && vite preview
vite v5.2.8 building SSR bundle for production...
✓ 649 modules transformed.
error when starting preview server:
undefined
error: script "start" exited with code 1

**Comment by ARajgor** [comment]
do you have latest version of bun?

**Comment by Balu027** [comment]
I updated that as well, now it goes a bit further:

$ vite build && vite preview
vite v5.2.8 building SSR bundle for production...
✓ 649 modules transformed.
vite v5.2.8 building for production...
✓ 688 modules transformed.
.svelte-kit/output/client/_app/version.json                                                            0.03 kB │ gzip:   0.05 kB
.svelte-kit/output/client/.vite/manifest.json                                                          5.68 kB │ gzip:   0.91 kB
.svelte-kit/output/client/_app/immutable/assets/tiktoken_bg.D1vgAo9Z.wasm                          1,100.09 kB
.svelte-kit/output/client/_app/immutable/assets/2.B4T8hs7e.css                                         6.19 kB │ gzip:   2.27 kB
.svelte-kit/output/client/_app/immutable/assets/Toaster.BkLvsHqN.css                                  12.78 kB │ gzip:   2.79 kB
.svelte-kit/output/client/_app/immutable/assets/0.ky7OTPEa.css                                        20.59 kB │ gzip:   4.69 kB
.svelte-kit/output/client/_app/immutable/entry/start.BjLKhbXo.js                                       0.07 kB │ gzip:   0.08 kB
.svelte-kit/output/client/_app/immutable/chunks/stores.Y4PAX1XE.js                                     0.23 kB │ gzip:   0.17 kB
.svelte-kit/output/client/_app/immutable/nodes/1.CcRYBzjx.js                                           0.79 kB │ gzip:   0.50 kB
.svelte-kit/output/client/_app/immutable/chunks/each.M-WWh_9i.js                                       0.86 kB │ gzip:   0.53 kB
.svelte-kit/output/client/_app/immutable/chunks/index.CtFfpz60.js                                      0.99 kB │ gzip:   0.60 kB
.svelte-kit/output/client/_app/immutable/chunks/Toaster.svelte_svelte_type_style_lang.CxETsj9g.js      2.57 kB │ gzip:   1.06 kB
.svelte-kit/output/client/_app/immutable/chunks/mode.D1BbPwL2.js                                       2.66 kB │ gzip:   1.06 kB
.svelte-kit/output/client/_app/immutable/nodes/3.cUIO3gCP.js                                           3.69 kB │ gzip:   1.52 kB
.svelte-kit/output/client/_app/immutable/chunks/index.CcqImCu-.js                                      5.52 kB │ gzip:   2.67 kB
.svelte-kit/output/client/_app/immutable/entry/app.XrUJMKMm.js                                         6.76 kB │ gzip:   2.72 kB
.svelte-kit/output/client/_app/immutable/chunks/icons.N1DyG8ix.js                                      6.98 kB │ gzip:   2.81 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.B_jgbYNs.js                                  9.23 kB │ gzip:   3.58 kB
.svelte-kit/output/client/_app/immutable/chunks/utils.Ckxz92B5.js                                     22.06 kB │ gzip:   7.54 kB
.svelte-kit/output/client/_app/immutable/chunks/entry.CKS99Ke6.js                                     25.81 kB │ gzip:  10.32 kB
.svelte-kit/output/client/_app/immutable/nodes/0.C5uExL6Y.js                                          41.27 kB │ gzip:  13.25 kB
.svelte-kit/output/client/_app/immutable/chunks/api.Bs-WsMpV.js                                       42.46 kB │ gzip:  13.28 kB
.svelte-kit/output/client/_app/immutable/nodes/4.By3_eLQt.js                                         120.29 kB │ gzip:  34.82 kB
.svelte-kit/output/client/_app/immutable/nodes/2.CaR3aJ7y.js                                       1,449.05 kB │ gzip: 600.66 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 9.06s
error when starting preview server:
undefined
error: script "start" exited with code 1

**Comment by ARajgor** [comment]
follow this https://github.com/stitionai/devika?tab=readme-ov-file#installation
