### ISSUE TITLE
Config.toml should be removed, replaced with example.config.toml and gitignored because it poses a security risk

### ISSUE THREAD

**Issue by timurista** [stitionai/devika#119]
The way it is structured now, it's too easy for a developer to accidentally commit their keys to config.toml and merge into main. At a minimum the config.toml should be ignored  in gitignore and I suggest you replace it with something like "example.config.toml" so that developers must create a fresh config.toml and don't accidentally commit keys.

**Comment by beckerben** [comment]
Agreed
