### ISSUE TITLE
Interface Not Working on Windows Using BUN for Experimental Windows Builds

### ISSUE THREAD

**Issue by DiDisama317** [stitionai/devika#120]
I was using the experimental version of BUN install on Windows, and everything went fine during the installation.

But I can not inference the devika whether I start the server first then UI or UI first then the server. The localhost web freezes and there's no response whatever I click on. 

<img width="564" alt="Screenshot 2024-03-24 233319" src="https://github.com/stitionai/devika/assets/87849405/172af147-6c98-45eb-9c32-bb55ca82430a">

<img width="1112" alt="Screenshot 2024-03-24 234208" src="https://github.com/stitionai/devika/assets/87849405/a86a970a-054f-481e-98f3-2ef6fab58b32">

![image](https://github.com/stitionai/devika/assets/87849405/3f496b53-e356-433a-8cac-14f2b90bfafe)

**Comment by kimsama** [comment]
This looks like a same issue as #113

**Comment by DiDisama317** [comment]
> This looks like a same issue as #113

Yeah, The only difference is that the post #113 uses WSL for BUN installing while I just used the experimental version of BUN on Windows.

**Comment by iAstrodude** [comment]
you able to solve your issue? or make sure you install ollama and running it, if not do use these command
###Download Ollama..

`** CMD**

>> start ollama (if downloaded)

in case:: if its already run or getting freeze than kill their process using
>> taskkill /IM ollama.exe /F

>>start ollama  

it will resolve the issue`

**Comment by DiDisama317** [comment]
> you able to solve your issue? or make sure you install ollama and running it, if not do use these command ###Download Ollama..
> 
> `** CMD**
> 
> > > start ollama (if downloaded)
> 
> in case:: if its already run or getting freeze than kill their process using
> 
> > > taskkill /IM ollama.exe /F
> 
> > > start ollama
> 
> it will resolve the issue`

No, that seem not be working for me. By the way, I've tried on both Ubuntu and Windows, and they both can't run this.

**Comment by ARajgor** [comment]
move the discussion to here https://github.com/stitionai/devika/issues/113
