### ISSUE TITLE
Interface barely working

### ISSUE THREAD

**Issue by mberman84** [stitionai/devika#123]
I'm on MacOS. Settings, the terminal, the browser, none of it works. I can enter a prompt, it prepares a plan, and then it freezes and nothing happens. It gets stuck on "writing code..."

**Comment by cornasdf** [comment]
I have been seeing the same on an ubuntu VM.  if you ask it what it is doing, it seems to be changing the answer but it won't show me any code... (yet?)

**Comment by cornasdf** [comment]
I think it is just very slow.  i asked it to show code and it seems to have written some 50 lines of python in 'app.py' in the project's directory and added two requirements to requirements.txt.  Took about 45 mins on my VM.  I don't seem to be pushing any significant mem or CPU usage.

**Comment by moinuddin14** [comment]
Just in case if you haven't looked at, at the end of the run there's a projects folder that gets created in the cloned repo and from where you have run the server. Inside that you will see the artifacts that it has generated during it's run. But at the moment i don't see any helpful artifacts being generated, it just adds some psudo code and bunch of common information.

**Comment by MyNameIsOka** [comment]
Just wanted to add on this, as I am experiencing the same. 
Clicking on `Settings` and `Logs`, doesn't do anything.  
It started writing code, but just a simple hello world server, and after that it just stopped (?)
Would be nice to understand better what it is actually doing at any given time.

**Comment by RohitX0X** [comment]
Did your terminal throw any error , it should throw an error ususally when things get stuck in between

**Comment by Captainnik53** [comment]
Same thing happening with me. The UI gets stuck after showing `writing code..` and when I asked explicitly to show the code, it showed me the code. 
Also, @moinuddin14 comment is accurate, it will show the results in the file, even if the status is stuck in UI. Probably looks like some frontend issue here. No errors found in server logs

**Comment by 11philip22** [comment]
I have been running it in WSL. Same issues :(

**Comment by ARajgor** [comment]
Everyone, fetch the latest changes and run it again.then share your thoughts.

**Comment by cornasdf** [comment]
I did try to fetch teh latest and try again but I couldn't get the agent online and the system was unusable.  Will try again in a week or so...

**Comment by SkelegonDK** [comment]
Same here, it gets the first task done, then gets stuck until I restart Devika or delete the project and restart.

**Comment by ARajgor** [comment]
fixed. fetch the latest changes. for more read the changelog in discord.
