### ISSUE TITLE
unable to go beyond python devika.py

### ISSUE THREAD

**Issue by cardchase** [stitionai/devika#128]
System:
`Ollama is running on http://127.0.0.1:11434/`

`Olama Web UI is running at: http://127.0.0.1:3000/`

When I type `ollama serve `I get 
`Error: listen tcp 127.0.0.1:11434: bind: address already in use`

I am able to clone the repository and run `python devika.py`
I am stuck at:

```
(base) user@user-TRX50-AERO-D:~/devika$ python devika.py
24.03.25 09:24:27: root: INFO   : Booting up... This may take a few seconds
24.03.25 09:24:27: root: INFO   : Initializing Devika...
24.03.25 09:24:27: root: INFO   : Initializing Prerequisites Jobs...
24.03.25 09:24:27: root: INFO   : Loading sentence-transformer BERT models...
24.03.25 09:24:30: root: INFO   : BERT model loaded successfully.
 * Serving Flask app 'devika'
 * Debug mode: off
```

When I `bun run dev` I get `$ vite dev` and its stuck there

and the code is stuck / the service is running however I am not able to access it.

Can I run devika ui on any other web address? This is cause I have ollama webui installed. Can anybody update me on if I need to uninstall ollama webui to get devika to run? I think thats the problem I am facing. Since devika and ollama webui are for the same address, ollama is taking precedence over devika?

I guess the devika.py loads more? and then the front end doesnt end at $ vite dev?

**Comment by javacaliente** [comment]
Even after  this step 2. Install bun - JavaScript runtime (https://bun.sh/)
You still have to do the 
cd ui/
bun install
before you can
bun run dev

**Comment by Alphayellowcat** [comment]
Like open-webui, it ues port 3000. The first method is to change the port when starting webui. Or try editing devika\ui\vite.config.js and change the port 3000.

**Comment by cardchase** [comment]
So I made these changes:

I installed `bun` 

```
(base) user@user:~/devika/ui$ bun --version
1.0.29
```

I changed the config.js to:
```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	server: {
	    port: 5000,
	},
});
```

I had forgot to install `playwright` so I installed and then deleted the folder and restarted the process.

I can see something has changed

```
(base) user@user:~$ ollama serve
Error: listen tcp 127.0.0.1:11434: bind: address already in use

```

When I run `python devika.py` I am still stuck at the model loading

```
(base) user@user:~/devika$ python devika.py
24.03.26 11:42:31: root: INFO   : Booting up... This may take a few seconds
24.03.26 11:42:31: root: INFO   : Initializing Devika...
24.03.26 11:42:31: root: INFO   : Initializing Prerequisites Jobs...
24.03.26 11:42:31: root: INFO   : Loading sentence-transformer BERT models...
24.03.26 11:42:34: root: INFO   : BERT model loaded successfully.
 * Serving Flask app 'devika'
 * Debug mode: off

And then I ran

(base) user@user:~/devika/ui$ bun run install
error: Failed to run "install" due to error AccessDenied

So I ran sudo

(base) user@user:~/devika/ui$ sudo bun run install
[sudo] password for harshad: 
error loading current directory

error: CouldntReadCurrentDirectory

----- bun meta -----
Bun v1.0.29 (a146856d) Linux x64 #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2
RunCommand: 
Elapsed: 1ms | User: 8ms | Sys: 23ms
RSS: 33.55MB | Peak: 18.87MB | Commit: 33.55MB | Faults: 0
----- bun meta -----

0   0x604d4261137b
1   ???
2   ???
3   ???
4   ???
5   ???
6   ???

Search GitHub issues https://bun.sh/issues or ask for #help in https://bun.sh/discord
```

Earlier when I ran `cd ui bun run dev` , I had got to `$ velte 1/2` but I am not get to that step when I am trying to recreate the issue and I am still stuck where I was

**Comment by feb-in** [comment]
Try running it with npm run dev, worked for me!

**Comment by cardchase** [comment]
I had to reinstall linux. I think my ollama webui installation was causing issues.
now I can see the webui.
Solution, remove ollama webui as I think its binding to the port 3000 is causing the issue. and follow the readme.
This issue can be closed

**Comment by KingLeoJr** [comment]
Hello
I have similar issue.
I can see the webui but everything is undefined. Could someone suggest what needs to be done, please?
![2024-03-30_11h52_06](https://github.com/stitionai/devika/assets/130857609/a86df104-9c9f-4994-9a79-181d65732b53)
![2024-03-30_11h52_49](https://github.com/stitionai/devika/assets/130857609/4bac16c3-3355-4ba4-a718-22b76c0285ce)

![2024-03-30_11h52_29](https://github.com/stitionai/devika/assets/130857609/ca630bb4-ebc1-42e1-91dc-42286b6edc3b)

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
