### ISSUE TITLE
Any plans for docker image

### ISSUE THREAD

**Issue by alfi4000** [stitionai/devika#132]
Are there any plans for a docker image or prebuilt version?

**Comment by Devesh-N** [comment]
Hey, I might make it

**Comment by Devesh-N** [comment]
UPDATE: Someone already made a PR about it, you can check it out @alfi4000

**Comment by alfi4000** [comment]
It looks like here is someone working on it: https://github.com/stitionai/devika/pull/101

**Comment by alfi4000** [comment]
It looks like someone is working on it: 
https://github.com/stitionai/devika/pull/101

**Comment by Devesh-N** [comment]
Yep, that's what I'm talking about

**Comment by sounishnath003** [comment]
Hello - @alfi4000  , you can look at #101 PR. 
- We are almost completed. Do check it out. 
- Try it out you could clone and run using `make compose-up` command which has been configured. (linux based systems)
- Make sure you have a docker installed in your machine.

**Comment by alfi4000** [comment]
Ok I’ll try it out the next days!
