### ISSUE TITLE
Flask server is not starting.

### ISSUE THREAD

**Issue by Impossibles800** [stitionai/devika#135]
- in `pip install -r requirements.txt` installs all the required Python packages, including Flask, then why it is showing this error?
  Error:
    File "C:\Users\BZK2KOR\Desktop\Internship\Gen-AI\DevikaAI\devika\devika.py", line 1, in <module>
    from flask import Flask, request, jsonify, send_file, make_response
  ModuleNotFoundError: No module named 'flask'
  
  Note: Python packages installed in env, and running the Python server inside that env.

**Comment by manish-9245** [comment]
try using devika.py

**Comment by Drlordbasil** [comment]
> try using python3 devika.py

^ if that doesn't work make sure you are properly within your env too if using one. Issues tend to be that its not installed on current env or the path for python isn't correct like manish suggests.

**Comment by batjko** [comment]
I get the same.
All requirements were installed successfully, within the venv. But running `python3 devika.py`, as per readme instructions, gives me the above error. 

![image](https://github.com/stitionai/devika/assets/7287076/35a9bf7f-ec90-419d-83ad-e9949fced244)


---
Btw, the big list-of-commands code block in the readme could be confusing as starting any of the three servers (ollama, devika, UI) doesn't return to the terminal, so you have to open a new one for each.
Small issue, but could trip people up as well.

**Comment by Drlordbasil** [comment]
> I get the same. All requirements were installed successfully, within the venv. But running `python3 devika.py`, as per readme instructions, gives me the above error.
> 
> ![image](https://private-user-images.githubusercontent.com/7287076/316505802-35a9bf7f-ec90-419d-83ad-e9949fced244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzIyNDksIm5iZiI6MTcxMTM3MTk0OSwicGF0aCI6Ii83Mjg3MDc2LzMxNjUwNTgwMi0zNWE5YmY3Zi1lYzkwLTQxOWQtODNhZC1lOTk0OWZjZWQyNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMTMwNTQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFmNTZjODM0Nzc1OTk5OTNiMzBjYWQwMjUxZTE5M2E4NTI0NGI3Y2RiMzgwZmQwY2FkNTNiYjUxNjhjM2Q1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MHQiUsAbviPw7XmTcp5r30YaMPFOcU0YDT_MS5QxKck)
> 
> Btw, the big list-of-commands code block in the readme could be confusing as starting any of the three servers (ollama, devika, UI) doesn't return to the terminal, so you have to open a new one for each. Small issue, but could trip people up as well.

If using UV you forgot the line that says "activate" but you can copy and paste or click to activate. Could be that, I ran into the issue before I went to env even though I had proper wsl dependencies, its also most likely that the requirements werent downloaded to proper pathing in that case. :) HOpe this helps!

**Comment by batjko** [comment]
Yes I was sure I had done it, but repeating the steps again, including the activation and re-installation of the dependencies after that, then made it work for me.

**Comment by ARajgor** [comment]
create virtual env. search how to create venv in python. install the requirements.txt
