### ISSUE TITLE
Webbrowser Search not working

### ISSUE THREAD

**Issue by NumerusXXL** [stitionai/devika#136]
Devika makes a plan and then comes to the point when it has to browse the web and do the research. Suddenly nothing happens. There is also no window on start. The browser tab is empty
![изображение](https://github.com/stitionai/devika/assets/117753548/3b9d6a91-c5ef-4b5c-8e53-00350cad4d1b)

**Comment by NinjaEde** [comment]
Have you entered your Bing API key in the config.toml file?

**Comment by Drlordbasil** [comment]
> Have you entered your Bing API key in the config.toml file?

I set mine an issue persists, maybe we are using the wrong endpoint or something for our bing api?

**Comment by Drlordbasil** [comment]
> > Have you entered your Bing API key in the config.toml file?
> 
> Some documentation on how to get the API key might be helpful Also some log message that Web Search is failing is needed as right now the user has no idea what's happening.

gotchu fam:
https://www.youtube.com/watch?v=RXGfb7jIM0c&ab_channel=VideoPizzazz

**Comment by Ahmet0691** [comment]
It would be more wonderful if he did his web research using the selenium library

**Comment by ARajgor** [comment]
fetch the latest changes
