### ISSUE TITLE
the application is great, but unfortunately in Vietnam we cannot create Claude

### ISSUE THREAD

**Issue by KalvinThien** [stitionai/devika#139]
the application is great, but unfortunately in Vietnam we cannot create Claude

**Comment by amrrs** [comment]
I think you can use it with local models powdered by Ollama

**Comment by shahab00x** [comment]
> I think you can use it with local models powdered by Ollama

It uses Ollama for some parts of it like processing web search results but not for coding. It should though but you cannot select it as an LLM in the main interface

**Comment by ARajgor** [comment]
you different models or APIs if the Claude is geo-restricted. as mention you can use ollama
