### ISSUE TITLE
[feature request] Implement Windows .bat Launcher for Devika

### ISSUE THREAD

**Issue by Tom-Neverwinter** [stitionai/devika#144]
Feature Description
I am suggesting the creation of a Windows batch file (.bat) launcher to facilitate an easier start-up process for Devika on Windows operating systems. This launcher would enable users to start Devika with just a double click, bypassing the need for command-line interactions or manual configuration.

Rationale
Many users and contributors of Devika may be operating on Windows. Providing a .bat launcher could significantly simplify the initial setup and daily usage for this large user base. This addition aims to lower the technical barrier to entry, making Devika more accessible to a broader range of users and developers, especially those less familiar with command-line operations.

Proposed Solution
The proposed solution involves developing a .bat file that automates the setup and launch process for Devika on Windows systems. This script should handle tasks like setting up the correct environment variables, activating any necessary virtual environments, and launching the Devika software. The objective is to streamline the user's start-up process to a single action.

Additional Context
Improving user experience by simplifying the start-up process can lead to increased adoption and a more vibrant community around Devika. A .bat launcher is a standard practice in many open-source projects targeting Windows users, contributing significantly to user retention and satisfaction.

I hope this feature will be considered for future updates, and I am open to contributing to its implementation or testing.

Thank you for considering this request.

**Comment by lydonator** [comment]
There cannot be a simple BAT installation for Windows users because BUN (JS front end) is not compatible with Windows. Devika can only currently be run on Linux, Mac and WSL (Windows Subsystem for Linux). 

I suppose it's possible that you could switch out the front end with something like Node, but that would take some effort.

**Comment by ARajgor** [comment]
if you tested and it work perfectly and you may create a PR for this.

**Comment by ARajgor** [comment]
currently, there is no plan for this so closing it.
