### ISSUE TITLE
Add pre-commit configurations and basic GitHub actions to validate the changes effortlessly

### ISSUE THREAD

**Issue by franklinselva** [stitionai/devika#153]
Now might be a good time to start adding dev configurations to the project. We can start considering pre-commit configurations to keep everyone's changes in self-check effortlessly. Also, adding a basic checker to Github actions before reviewing the code would save us more time in a longer run.

If this proposal is okay, I am willing to take it up myself.

**Comment by ARajgor** [comment]
are you going for it or not? if not then close this issue.

**Comment by franklinselva** [comment]
We cannot merge at this point. I am closing it
