### ISSUE TITLE
How use other API ? ( Deepseek AI )

### ISSUE THREAD

**Issue by DonMonro** [stitionai/devika#158]
Hi guys
any one know how can i use free and open source API like "Deepseek coder AI" and "Deepseek API" ?
its more much better in coding and have 1M free token API.

**Comment by rajakumar05032000** [comment]
Its not supported at the moment, if I am not wrong.

**Comment by NinjaEde** [comment]
You can use it locally through OLLAMA - that‘s at least I did it.

**Comment by DonMonro** [comment]
> You can use it locally through OLLAMA - that‘s at least I did it.

yeah i think this the only way at this time
