### ISSUE TITLE
部署好了，新建项目没有反应！

### ISSUE THREAD

**Issue by FlowersWithoutMoon** [stitionai/devika#159]
1

**Comment by stanleyyan** [comment]
选择模型呀，右上角下拉框

**Comment by FlowersWithoutMoon** [comment]
![动画](https://github.com/stitionai/devika/assets/87750901/dab44c73-8f5b-46e2-abbe-9cf263acbf78)
还是没有反应呢

**Comment by An-Jhon** [comment]
可以查看终端，好像是终端中会有提示，我的是提示：sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by stanleyyan** [comment]
配置一下模型，需要去编辑.env文件

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
