### ISSUE TITLE
Not getting the response from backend - Agent is not getting started.

### ISSUE THREAD

**Issue by Chinnapani9439** [stitionai/devika#162]
24.03.26 16:51:06: root: DEBUG  : /api/model-list GET - Response: {"models":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"],["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]}
 
24.03.26 16:51:06: root: INFO   : /api/get-agent-state POST
24.03.26 16:51:06: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}
 
24.03.26 16:51:06: root: INFO   : /api/get-messages POST
24.03.26 16:51:06: root: DEBUG  : /api/get-messages POST - Response: {"messages":[{"from_devika":false,"message":"Hi","timestamp":"2024-03-26 16:45:06"},{"from_devika":false,"message":"Hello","timestamp":"2024-03-26 16:45:53"}]}
 
24.03.26 16:51:07: root: INFO   : /api/token-usage GET
24.03.26 16:51:07: root: INFO   : /api/project-list GET
24.03.26 16:51:07: root: DEBUG  : /api/token-usage GET - Response: {"token_usage":0}
 
24.03.26 16:51:07: root: DEBUG  : /api/project-list GET - Response: {"projects":["Test"]}
 
24.03.26 16:51:07: root: INFO   : /api/model-list GET
24.03.26 16:51:07: root: DEBUG  : /api/model-list GET - Response: {"models":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"],["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]}
 
24.03.26 16:51:07: root: INFO   : /api/get-agent-state POST
24.03.26 16:51:07: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}
 
24.03.26 16:51:07: root: INFO   : /api/get-messages POST
24.03.26 16:51:07: root: DEBUG  : /api/get-messages POST - Response: {"messages":[{"from_devika":false,"message":"Hi","timestamp":"2024-03-26 16:45:06"},{"from_devika":false,"message":"Hello","timestamp":"2024-03-26 16:45:53"}]}
 
24.03.26 16:51:08: root: INFO   : /api/token-usage GET
24.03.26 16:51:08: root: DEBUG  : /api/token-usage GET - Response: {"token_usage":0}
 
24.03.26 16:51:08: root: INFO   : /api/project-list GET
24.03.26 16:51:08: root: DEBUG  : /api/project-list GET - Response: {"projects":["Test"]}
 
24.03.26 16:51:08: root: INFO   : /api/model-list GET
24.03.26 16:51:08: root: DEBUG  : /api/model-list GET - Response: {"models":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"],["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]}
 
24.03.26 16:51:08: root: INFO   : /api/get-agent-state POST
24.03.26 16:51:08: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}
 
24.03.26 16:51:08: root: INFO   : /api/get-messages POST
24.03.26 16:51:08: root: DEBUG  : /api/get-messages POST - Response: {"messages":[{"from_devika":false,"message":"Hi","timestamp":"2024-03-26 16:45:06"},{"from_devika":false,"message":"Hello","timestamp":"2024-03-26 16:45:53"}]}

**Comment by YakovAU** [comment]
same error log. ive put in my bing api and openai key, im using WSL2 ubtuntu LTS on windows 11.

**Comment by ibndias** [comment]
Same here, nothing happens

**Comment by PunkSarich** [comment]
same.i have set OPENAI_BASE_URL and still nothing reports from devika

**Comment by ketangangal** [comment]
For now use postman and fire cmd from there flask backend will work , I will look into this issue.

**Comment by machinelearningzuu** [comment]
@ketangangal yes. I called the API manually (execute-agent) and it worked.

**Comment by YakovAU** [comment]
For those who didnt understand, you can use curl: 

> curl -X POST -H "Content-Type: application/json" -d '{"prompt":"your prompt here", "base_model":"gpt-4-0125-preview", >"project_name":"<Project name>"}' http://localhost:1337/api/execute-agent

**Comment by KermaniMojtaba** [comment]
same here, running on a Mac.
I tried curl, but it didn't work either, get " status: 404,"

**Comment by machinelearningzuu** [comment]
@KermaniMojtaba did you tried through PostMan. If so share the Request URL and JSON Body here
