### ISSUE TITLE
this is making me depressed

### ISSUE THREAD

**Issue by Aadit017** [stitionai/devika#164]

**Comment by michaelfortunato** [comment]
Same. I think a lot of people got into software engineering because it is a way to demonstrate and build on our innate creativity, and at the same time using reasoning and system design to solve real problems. Personally speaking, it's emotionally difficult to see this all being automated.

**Comment by 0xmulch** [comment]
I hear the both of you. I would like to comment with an alt perspective:

This should be looked at as a catalyst for creativity-- implementation isn't the point, building excellent products that makes the world better is the target

Tools like this could help you be _more_ creative. 

You can fail faster. Find PMF faster, all with 100x less sunk costs and effort.

You get to focus on building the stuff that the local AIs don't yet have the capability to. You get to focus on the big, amazing ideas and leverage these LLMs to get you there as fast as possible. 

**I posit: Did the printing press make books go away?**

**Comment by dpublic** [comment]
I agree with 0xmulch, you have to use the tools that are given to you because we can't turn back time.
I see this eventually becoming a great tool for software developers to use as it gives you at least a base for your projects and helps you get through the wall of software developers writers block.
I don't think anybody wants a self-opinionated automated software developer because they could go in the wrong direction.
You are Iron Man/Woman and this is your iron suit.

**Comment by OxygenCobalt** [comment]
I'm not going to lie, as an autistic person that fled away from the illogical and incoherent world of people into computing, seeing this field collapse into basically talking to stakeholders and AI agents is legitimately heart-breaking. And that's assuming that it even survives in some form and isn't going the way of the telephone router or village artisan. I think @0xmulch's point is valid coming from a "founder type" background of coming up with and marketing as many products as possible, but I've never had the idea generation skills or charisma to pull that off. Feels more likely that I'm made redundant instead.

**Comment by 0skxr** [comment]
I haven't even started my job training yet since I'm still in school. I have been coding for the best part of my life. It's really sad to see that I might not get a job because of greedy CEOs that replace developers with AI agents.

**Comment by mufeedvh** [comment]
Hey everyone, the creator of Devika here. Wanted to share my 2 cents. 🙌 

This is an important discussion to have so I appreciate posting this issue. All of your points are valid. I personally do not believe humans will be replaced by agents like this... entirely. Most positions will indeed be redundant in the future, mostly the ones with the tasks to write boilerplate code or CRUD apps. If you've something unique to show for, you will never be replaced by AI. Even though AI can emulate them, some elements are unique to humans, focus on what you want to excel in and you'll do just fine. Of course, I am personally being very optimistic about this whole AI-integrated future, I could be wrong.

In short, strive to be in the top percentile of whatever skill you're pursuing, as long as you stand out of the crowd, I don't think this AI wave is going to affect you. This takes an enormous amount of work, but that's how the game works. :)

This project will be open-source forever, I do not have any financial incentives with the project even though I could turn it into one with a single decision, investors and VCs are filling up my inbox. I could release a paid-managed version of this in a day, but I won't. This project is modeled after Devin, which is closed source and proprietary, we need to commoditize and bring powerful tools to everyone, not just the people who are privileged to access it, that's the intention behind the project. Thanks! 🙌
