### ISSUE TITLE
Unable to Start UI Server with "bun run dev" Command

### ISSUE THREAD

**Issue by THURAKA-ANANTH** [stitionai/devika#165]
Problem:
When attempting to run the UI server using bun run dev, the server does not start up as expected. However, using npm run dev works as intended.

Steps to Reproduce:

Navigate to the ui/ directory.
Execute npm run dev.

Expected Behavior:
The UI server should start up and be accessible.

Actual Behavior:
The UI server fails to start up, and no errors or output are provided.

Notes:

The npm run dev command utilizes a different approach to start the server compared to bun run dev. Investigating the differences in how these commands are configured may provide insights into the issue.
Ensure that all necessary dependencies are installed and up to date before attempting to run the server with npm run dev.
Check for any error messages or logs that might indicate why npm run dev is failing to start the server.

**Comment by deepsuthar496** [comment]
Which platform do you uwwse? ( windows , linux or macos )

**Comment by Ahmet0691** [comment]
Install WSL and run it on ubuntu.

**Comment by huangjingcai** [comment]
mac works well follow the Readme

**Comment by THURAKA-ANANTH** [comment]
> Which platform do you use? ( windows , linux or macos )

LINUX

**Comment by deepsuthar496** [comment]
Create a virtual environment using **Conda Env** with Python version **3.11**, and then install all requirements.

**Comment by THURAKA-ANANTH** [comment]
> Create a virtual environment using **Conda Create** with Python version **3.11**, and then install all requirements.

OK
