### ISSUE TITLE
Uncaught (in promise) TypeError: xtermAddonFit.FitAddon is not a constructor

### ISSUE THREAD

**Issue by tensiondriven** [stitionai/devika#171]
On a relatively clean MacOS system,

1) Followed instructions to install uv, bin, pip requirements, etc
2) Started python server
3) Started web server

When using the web page, the following message is displayed in the console:

```
Uncaught (in promise) TypeError: xtermAddonFit.FitAddon is not a constructor
```

Does xtermAddonFit need to be added to the bun requirements?

**Comment by ARajgor** [comment]
fetch the latest changes
