### ISSUE TITLE
It doesn't work I have an error

### ISSUE THREAD

**Issue by start-life** [stitionai/devika#173]
VITE v5.2.2  ready in 766 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
23:20:23 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:115:10 A11y: '#' is not a valid e
23:20:23 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:124:14 A11y: '#' is not a valid e
23:20:23 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:186:16 A11y: '#' is not a valid e

**Comment by wilofice** [comment]
me too. I have same error. 

  VITE v5.2.2  ready in 294 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
8:32:46 PM [vite-plugin-svelte] /home/n/Desktop/sources/devika/ui/src/lib/components/ControlPanel.svelte:115:10 A11y: '#' is not a valid href attribute
8:32:46 PM [vite-plugin-svelte] /home/n/Desktop/sources/devika/ui/src/lib/components/ControlPanel.svelte:124:14 A11y: '#' is not a valid href attribute
8:32:46 PM [vite-plugin-svelte] /home/n/Desktop/sources/devika/ui/src/lib/components/ControlPanel.svelte:186:16 A11y: '#' is not a valid href attribute
8:32:47 PM [vite-plugin-svelte] /home/n/Desktop/sources/devika/ui/src/lib/components/ControlPanel.svelte:115:10 A11y: '#' is not a valid href attribute
8:32:47 PM [vite-plugin-svelte] /home/n/Desktop/sources/devika/ui/src/lib/components/ControlPanel.svelte:124:14 A11y: '#' is not a valid href attribute
8:32:47 PM [vite-plugin-svelte] /home/n/Desktop/sources/devika/ui/src/lib/components/ControlPanel.svelte:186:16 A11y: '#' is not a valid href attribute

**Comment by KaustubhTrivedi** [comment]
Can I take this issue?

**Comment by KaustubhTrivedi** [comment]
Just replace "#" with "#/" your issue will be resolved for the time being. Also, It should not cause the app to not start, this is just a A11Y error. i.e. Svelte says that using "#" might not be best for accessibility.

**Comment by start-life** [comment]
The user interface opens for me but nothing happens I try to press the buttons and nothing happens and this is the error so what can be done?

**Comment by ARajgor** [comment]
fetch the latest changes.
