### ISSUE TITLE
I cannot get the response from the LLM, what's wrong with it?

### ISSUE THREAD

**Issue by huangjingcai** [stitionai/devika#178]
I have setting my OpenAI API Key, and I choose the GPT-3.5 ,but it just not work.What should I do ?
here is the screen shot:
![WX20240327-115723@2x](https://github.com/stitionai/devika/assets/3855873/d0de87e1-4f32-4835-b45d-7e1bff9b27c2)
and the logs:
![WX20240327-115854@2x](https://github.com/stitionai/devika/assets/3855873/d67c13ec-2764-4795-93e3-397953e1cc7b)

I need help for this, thanks my bro

**Comment by ketangangal** [comment]
@huangjingcai use postman to interact with devika for fast response it will take some time to from ui to work.

**Comment by huangjingcai** [comment]
@ketangangal thanks for the tips,  but i do not know the URL, can you tell me more about it? 🤝

**Comment by DeekshithRajBasa** [comment]
@huangjingcai 
![image](https://github.com/stitionai/devika/assets/37568816/b7e84502-7c24-4ff1-88a9-cac271e81857)
