### ISSUE TITLE
Stuck at loading screen, agent busy?

### ISSUE THREAD

**Issue by cardchase** [stitionai/devika#180]
![Devika](https://github.com/stitionai/devika/assets/33249394/407de050-8ff4-4f31-a152-8694c82c4ac3)
I have managed to get the webui and also have uploaded my claude api key also have the llava-34B model installed on my system.

Now, when I select the model and type anything, i am stuck at _Agent is busy..._ at the bottom corner and nothing comes up.
On ollama, I get 30t/s while Devika, I get none

Also, log file is empty.

I get this in the terminal:

```
24.03.27 16:01:17: root: INFO   : /api/model-list GET
24.03.27 16:01:17: root: DEBUG  : /api/model-list GET - Response: {"models":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"],["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"],["GROQ Mixtral","mixtral-8x7b-32768"],["llava","llava:34b"]]}

24.03.27 16:01:17: root: INFO   : /api/get-agent-state POST
24.03.27 16:01:17: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

24.03.27 16:01:17: root: INFO   : /api/get-messages POST
24.03.27 16:01:17: root: DEBUG  : /api/get-messages POST - Response: {"messages":null}

24.03.27 16:01:17: root: INFO   : /api/token-usage GET
24.03.27 16:01:17: root: DEBUG  : /api/token-usage GET - Response: {"token_usage":0}

24.03.27 16:01:17: root: INFO   : /api/token-usage GET
24.03.27 16:01:17: root: DEBUG  : /api/token-usage GET - Response: {"token_usage":0}

24.03.27 16:01:18: root: INFO   : /api/token-usage GET
24.03.27 16:01:18: root: DEBUG  : /api/token-usage GET - Response: {"token_usage":0}

24.03.27 16:01:18: root: INFO   : /api/token-usage GET
24.03.27 16:01:18: root: DEBUG  : /api/token-usage GET - Response: {"token_usage":0}

24.03.27 16:01:18: root: INFO   : /api/project-list GET
24.03.27 16:01:18: root: DEBUG  : /api/project-list GET - Response: {"projects":["Trial","Trial","test"]}
```
Also, I am unable to remove an existing project

**Comment by machinelearningzuu** [comment]
@cardchase Same for me. when I call the API manually it works, unfortunately

**Comment by machinelearningzuu** [comment]
like this 

![image](https://github.com/stitionai/devika/assets/41842488/bac13ead-0e8d-4dff-9b73-a20b336a9a41)

**Comment by cardchase** [comment]
![image](https://github.com/stitionai/devika/assets/33249394/63eea227-0d45-4b99-8379-769f1c9a5ffd)
i am getting this. I dont know gow to get to the api

**Comment by huangjingcai** [comment]
@cardchase Use Postman not the browser

**Comment by huangjingcai** [comment]
@machinelearningzuu this is my post, but it response the same result with different prompt, what about yours?
![WX20240327-144638@2x](https://github.com/stitionai/devika/assets/3855873/2252f801-2a64-43db-b006-cdb1c7a8fd89)

**Comment by DeekshithRajBasa** [comment]
Please add API key to get started, go to setting and add your API key.

**Comment by cardchase** [comment]
> Please add API key to get started, go to setting (http://localhost:3000/settings) and add your API key. <img alt="Screenshot 2024-03-27 at 12 29 27 PM" width="500" src="https://private-user-images.githubusercontent.com/37568816/317162381-63f8571b-fd33-4b76-be06-f5bb83a3db15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjMxMjMsIm5iZiI6MTcxMTUyMjgyMywicGF0aCI6Ii8zNzU2ODgxNi8zMTcxNjIzODEtNjNmODU3MWItZmQzMy00Yjc2LWJlMDYtZjViYjgzYTNkYjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA3MDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViZjhhMmJmZTExMmY2NjczNzk2YjU1OTJlMzY0MTg5NDRhNzlkMjNiNDYyYWI3NzIxODNhMmY1YmZiZWYzYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IQFQfANivU_t_4ef1MaNbfideyx7bvEj817MWxDr5UE">

I did put in Claude API and I got the dropdown model but no response.
Will try postman and see how it goes

**Comment by breax1** [comment]
I'm getting 404 error

![Screenshot from 2024-03-27 13-06-38](https://github.com/stitionai/devika/assets/99740637/74439432-dd13-413d-acc9-46ae23a347c9)

**Comment by breax1** [comment]
I fixed it but it didn't work :)

![Screenshot from 2024-03-27 13-41-15](https://github.com/stitionai/devika/assets/99740637/e780deac-d334-4931-9c5b-4cc892011e3c)


> I'm getting 404 error
> 
> ![Screenshot from 2024-03-27 13-06-38](https://private-user-images.githubusercontent.com/99740637/317218471-74439432-dd13-413d-acc9-46ae23a347c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzUyMzEsIm5iZiI6MTcxMTUzNDkzMSwicGF0aCI6Ii85OTc0MDYzNy8zMTcyMTg0NzEtNzQ0Mzk0MzItZGQxMy00MTNkLWFjYzktNDZhZTIzYTM0N2M5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEwMjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNzIwYzQ4ZDhhMWM4N2UyNWNlMmJjZDQ5MTM4MGFhMWJjOGU0ODIwNjQ5MmNjZWQ3ZmFiMzg0MzJmZjVlN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pt-H_CjRZ-gNuOspjeUyU_9LPKRR4MyDlQaFqwHW6mQ)

**Comment by machinelearningzuu** [comment]
@huangjingcai yeah this is correct. when you call this agent start actioning. you can see the changes in the UI

**Comment by machinelearningzuu** [comment]
@breax1 because your end-point is incorrect. It should be http://127.0.0.1:1337/api/execute-agent

**Comment by rajakumar05032000** [comment]
Already created PR , which solves this issue.
PR : #190

**Comment by cardchase** [comment]
I installed postman however I am unsure to go from here. I have this screen on Postman: 
![image](https://github.com/stitionai/devika/assets/33249394/751c498c-3b4b-4e97-8e59-a960795bf5fb)
Where am i to enter the url and the endpoint in this application?

**Comment by DopeDealers** [comment]
> Already created PR , which solves this issue. PR : #190

issue still persists for me

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
