### ISSUE TITLE
No Reply From Devika

### ISSUE THREAD

**Issue by GSrinivasKishanLal** [stitionai/devika#185]
After setup of Devika in Ubuntu System is done and ran,
Getting no reply from Devika form any Model.
Response in python console after running devika.py file:

{
      "from_devika": false,
      "message": "Tokens used",
      "timestamp": "2024-03-27 10:31:30"
    }
 
Kindly make a note on this issue I am getting for Devika AI

![package_devika_issue](https://github.com/stitionai/devika/assets/165138176/6e17f351-9982-4e1b-ab79-367b8a697656)

**Comment by rajakumar05032000** [comment]
Already created PR , which solves this issue.
PR : #190

**Comment by huangjingcai** [comment]
@rajakumar05032000 Have the PR merged into main branch already? I pulled but still the same with @rajakumar05032000

**Comment by axsddlr** [comment]
190 pr does not fix issue

**Comment by sainudheenp** [comment]
@rajakumar05032000 Yh , issue still exist.

**Comment by rajakumar05032000** [comment]
If the issue still exist, can someone send the full logs and also would like to know which model you are using? ( I have tested well with Ollama & Groq mixtral)

**Comment by rajakumar05032000** [comment]
Those who are facing issues, can you please create a new project in devika UI and and then add your query & check?

Only first prompt in a devika project, yields response from devika and rest of the prompts yield no response from devika..

Unless devika itself asks you question, then only second or consequent prompts will yield response from devika..its a known issue.

So please create a new project in devika UI and check with a prompt..

Recently, tested Again this fix with Chatgpt, Groq, Ollama, Claude models also, it works fine as expected!

@niazikashif thanks for helping in testing with ChatGPT models.

**Comment by rajakumar05032000** [comment]
for people who are using Groq models, please make sure to add this fix from #193 (which fixes groq client issues, only then it will work) and then try.

**Comment by GSrinivasKishanLal** [comment]
Hello @rajakumar05032000 thank you for your suggestion, once when I tried creating new project in Devika UI also, I am still getting no reply, kindly note the below response, I get and the issue is still existing.

24.03.28 14:37:13: root: INFO   : /api/get-messages POST
24.03.28 14:37:13: root: DEBUG  : /api/get-messages POST - Response: {
  "messages": [
    {
      "from_devika": false,
      "message": "Hello",
      "timestamp": "2024-03-28 14:36:54"
    }
  ]
}

**Comment by rajakumar05032000** [comment]
> Hello @rajakumar05032000 thank you for your suggestion, once when I tried creating new project in Devika UI also, I am still getting no reply, kindly note the below response, I get and the issue is still existing.
> 
> 24.03.28 14:37:13: root: INFO : /api/get-messages POST 24.03.28 14:37:13: root: DEBUG : /api/get-messages POST - Response: { "messages": [ { "from_devika": false, "message": "Hello", "timestamp": "2024-03-28 14:36:54" } ] }

Can you please send the full log of  devika_agent.log file (which is present in logs folder) and also please confirm that whether you had added your API keys in config.toml file..

**Comment by GSrinivasKishanLal** [comment]
> > Hello @rajakumar05032000 thank you for your suggestion, once when I tried creating new project in Devika UI also, I am still getting no reply, kindly note the below response, I get and the issue is still existing.
> > 24.03.28 14:37:13: root: INFO : /api/get-messages POST 24.03.28 14:37:13: root: DEBUG : /api/get-messages POST - Response: { "messages": [ { "from_devika": false, "message": "Hello", "timestamp": "2024-03-28 14:36:54" } ] }
> 
> Can you please send the full log of devika_agent.log file (which is present in logs folder) and also please confirm that whether you had added your API keys in config.toml file..

Sure @rajakumar05032000 , kindly find attachment for the devika_agent.log file and also find given image where the api key is given in hte config.toml file:

![config_tom_file_changes](https://github.com/stitionai/devika/assets/165138176/796deda5-4d0f-4061-8907-7d36f5a81abc)
[devika_agent.log](https://github.com/stitionai/devika/files/14787236/devika_agent.log)

**Comment by rajakumar05032000** [comment]
> > > Hello @rajakumar05032000 thank you for your suggestion, once when I tried creating new project in Devika UI also, I am still getting no reply, kindly note the below response, I get and the issue is still existing.
> > > 24.03.28 14:37:13: root: INFO : /api/get-messages POST 24.03.28 14:37:13: root: DEBUG : /api/get-messages POST - Response: { "messages": [ { "from_devika": false, "message": "Hello", "timestamp": "2024-03-28 14:36:54" } ] }
> > 
> > 
> > Can you please send the full log of devika_agent.log file (which is present in logs folder) and also please confirm that whether you had added your API keys in config.toml file..
> 
> Sure @rajakumar05032000 , kindly find attachment for the devika_agent.log file and also find given image where the api key is given in hte config.toml file:
> 
> ![config_tom_file_changes](https://private-user-images.githubusercontent.com/165138176/317673958-796deda5-4d0f-4061-8907-7d36f5a81abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjE2NzAsIm5iZiI6MTcxMTYyMTM3MCwicGF0aCI6Ii8xNjUxMzgxNzYvMzE3NjczOTU4LTc5NmRlZGE1LTRkMGYtNDA2MS04OTA3LTdkMzZmNWE4MWFiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMDIyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDY3ZjE3OTI2OGU0NWExNGFlNTlmYmE5NGRhNThmODdiODY2NjU5MDUzMTA5NWY4NmM2NTZlYmQ2N2Y3MjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ekBwHcF-g7lcnw5rvMX0yDwWIquVYTIDpdflaeFCzHs) [devika_agent.log](https://github.com/stitionai/devika/files/14787236/devika_agent.log)

Kindly, Can you please share devika_prompts.log file( which is present in same logs directory).

**Comment by GSrinivasKishanLal** [comment]
> > > > Hello @rajakumar05032000 thank you for your suggestion, once when I tried creating new project in Devika UI also, I am still getting no reply, kindly note the below response, I get and the issue is still existing.
> > > > 24.03.28 14:37:13: root: INFO : /api/get-messages POST 24.03.28 14:37:13: root: DEBUG : /api/get-messages POST - Response: { "messages": [ { "from_devika": false, "message": "Hello", "timestamp": "2024-03-28 14:36:54" } ] }
> > > 
> > > 
> > > Can you please send the full log of devika_agent.log file (which is present in logs folder) and also please confirm that whether you had added your API keys in config.toml file..
> > 
> > 
> > Sure @rajakumar05032000 , kindly find attachment for the devika_agent.log file and also find given image where the api key is given in hte config.toml file:
> > ![config_tom_file_changes](https://private-user-images.githubusercontent.com/165138176/317673958-796deda5-4d0f-4061-8907-7d36f5a81abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjE2NzAsIm5iZiI6MTcxMTYyMTM3MCwicGF0aCI6Ii8xNjUxMzgxNzYvMzE3NjczOTU4LTc5NmRlZGE1LTRkMGYtNDA2MS04OTA3LTdkMzZmNWE4MWFiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMDIyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDY3ZjE3OTI2OGU0NWExNGFlNTlmYmE5NGRhNThmODdiODY2NjU5MDUzMTA5NWY4NmM2NTZlYmQ2N2Y3MjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ekBwHcF-g7lcnw5rvMX0yDwWIquVYTIDpdflaeFCzHs) [devika_agent.log](https://github.com/stitionai/devika/files/14787236/devika_agent.log)
> 
> Kindly, Can you please share devika_prompts.log file( which is present in same logs directory).

Yes, Sure, Kindly find the prompts file below:

[devika_prompts.log](https://github.com/stitionai/devika/files/14787898/devika_prompts.log)

**Comment by rajakumar05032000** [comment]
> > > > > Hello @rajakumar05032000 thank you for your suggestion, once when I tried creating new project in Devika UI also, I am still getting no reply, kindly note the below response, I get and the issue is still existing.
> > > > > 24.03.28 14:37:13: root: INFO : /api/get-messages POST 24.03.28 14:37:13: root: DEBUG : /api/get-messages POST - Response: { "messages": [ { "from_devika": false, "message": "Hello", "timestamp": "2024-03-28 14:36:54" } ] }
> > > > 
> > > > 
> > > > Can you please send the full log of devika_agent.log file (which is present in logs folder) and also please confirm that whether you had added your API keys in config.toml file..
> > > 
> > > 
> > > Sure @rajakumar05032000 , kindly find attachment for the devika_agent.log file and also find given image where the api key is given in hte config.toml file:
> > > ![config_tom_file_changes](https://private-user-images.githubusercontent.com/165138176/317673958-796deda5-4d0f-4061-8907-7d36f5a81abc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjE2NzAsIm5iZiI6MTcxMTYyMTM3MCwicGF0aCI6Ii8xNjUxMzgxNzYvMzE3NjczOTU4LTc5NmRlZGE1LTRkMGYtNDA2MS04OTA3LTdkMzZmNWE4MWFiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMDIyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDY3ZjE3OTI2OGU0NWExNGFlNTlmYmE5NGRhNThmODdiODY2NjU5MDUzMTA5NWY4NmM2NTZlYmQ2N2Y3MjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ekBwHcF-g7lcnw5rvMX0yDwWIquVYTIDpdflaeFCzHs) [devika_agent.log](https://github.com/stitionai/devika/files/14787236/devika_agent.log)
> > 
> > 
> > Kindly, Can you please share devika_prompts.log file( which is present in same logs directory).
> 
> Yes, Sure, Kindly find the prompts file below:
> 
> [devika_prompts.log](https://github.com/stitionai/devika/files/14787898/devika_prompts.log)

Thanks for sharing! Devika is not communicating with your LLM for some reasons. If possible can you please try with groq model(which is free now for now & can be accessed easily just by google sign-in.).

-> Kindly please do pull the latest changes ( as few changes got merged a hr ago) and restart devika.py file &  UI.
-> Kindly also update config.toml file with new API key.
-> Create a new devika project and try with some command like "create a flappy bird game" or something like that , instead of simple "Hi" message.

Thanks for your patience! Looking forward to hear from you soon!

**Comment by rajakumar05032000** [comment]
> > create a flappy bird game
> 
> Thank you @rajakumar05032000, after creating a groq key and using it, I am getting reply from Devika for GORQ- llama2 LLM in my new project.
> 
> Just a kind reminder that when I pulled the latest changes, the "config.toml" file was missing, I replaced it in my local with my existing one, kindly check it, otherwise the Devika response for gorq LLM is replying.

Thanks for your patience & I am glad that I was able to solve your issue.

-> rename of config.toml to sample.config.toml was an intended change. Because with config.toml file, developers can accidentally push their API keys along with code.

Btw, If your issue got resolved, feel free to close this issue.

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
