### ISSUE TITLE
Error when Ollama run on another server (same LAN)

### ISSUE THREAD

**Issue by ansutung** [stitionai/devika#187]
24.03.27 09:05:32: root: WARNING: Ollama server not running, please start the server to use models from Ollama.
24.03.27 09:05:42: root: INFO   : Booting up... This may take a few seconds
24.03.27 09:05:42: root: INFO   : Initializing Devika...
24.03.27 09:05:42: root: INFO   : Initializing Prerequisites Jobs...
24.03.27 09:05:42: root: INFO   : Loading sentence-transformer BERT models...
24.03.27 09:05:56: root: INFO   : BERT model loaded successfully.
 * Serving Flask app 'devika'
 * Debug mode: off

**Comment by gt-madanb** [comment]
Following

**Comment by DanielDKnudsen** [comment]
Me too

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed. now you can give host url
