### ISSUE TITLE
Devika starts searching the internet and then it hangs with no action later on...

### ISSUE THREAD

**Issue by qwaszaq** [stitionai/devika#194]
i want it to create a test single-page website with data on world's population, there's no problem with communication between local ollama LLM and devika and it even starts to search the web for data. it visits two webpages and then there is no action, cpu and gpu usage is none. what might be the case?

**Comment by Anarchon14** [comment]
On my end it browsed two pages, and stuck on Writing Code (as internal dialogue) - already waiting for more than an hour and it seems it's in a infinite loop

**Comment by qwaszaq** [comment]
same for me, however in my case it managed to visit three websites :D

**Comment by jyonny-byte** [comment]
Same, it wrote some code once before getting stuck, otherwise same as above.

**Comment by huangjingcai** [comment]
same for me, sometime I was confused, is it really work now？

**Comment by allelive** [comment]
anche io stesso problema

**Comment by hao0608** [comment]
Same here. The browser and terminal display nothing, but project has been created.
![image](https://github.com/stitionai/devika/assets/65147485/cef92a50-3787-4d08-bcef-b8a8d21beac3)

**Comment by qwaszaq** [comment]
All right!  Can you tell me what API did you use and what prompt you applied?

**Comment by hao0608** [comment]
@qwaszaq I'm using the OpenAI and Bing APIs, and my prompt is 'Give me a python code with KNN classify iris datasets.' I just pulled the latest version, and the terminal seems to be working successfully, but the browser still isn't working. :(

**Comment by qwaszaq** [comment]
Thanx ! I just wonder if anyone has used Google search api?

**Comment by hao0608** [comment]
According to this [YouTube video](https://www.youtube.com/watch?v=eLiMpEIRBzY), around the 6:40 mark, it seems there was support for Google Search previously, but now only Bing Search remains.

**Comment by abhisrinu** [comment]
same here, it goes to few search results and then freezes, but I do see that sometimes it does write the code in the projects folder but it just gets stuck after searching 3(or n) pages. I did try both google and bing to see if thats the problem but same case

**Comment by hqnicolas** [comment]
Fixed today! thank you!
frozen fix project forked today at https://github.com/hqnicolas/devika

**Comment by allelive** [comment]
> Risolto oggi! Grazie! progetto di correzione congelata biforcato oggi su https://github.com/hqnicolas/devika

il link ce hai fornito errore 404 pagina non trovata volevo sapere come hai risolto io ho cancellato e reinstallato ora mi da errore devika.py' terminated by signal SIGILL (Illegal instruction)
non so come risolvere, credevo fosse la versione di python non compatibile ma penso sia per la cpu perche io ho scheda intel integrata senza cpu e senza supporto avx e per questo non riesco a utilizzare penso io ma ieri mi funzionava cavolo perche lo cancellato hahaha ciao

**Comment by allelive** [comment]
> Risolto oggi! Grazie! progetto di correzione congelata biforcato oggi su https://github.com/hqnicolas/devika

forse era andata via la connessione ho aperto ora il link

**Comment by hqnicolas** [comment]
ho apportato la correzione ora è necessario un server Ollama esterno per eseguire il codice https://github.com/hqnicolas/devika Utilizzo Docker Compose per eseguire "docker compose build" + "docker compose up"

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
