### ISSUE TITLE
docker-compose up not working

### ISSUE THREAD

**Issue by bancroftway** [stitionai/devika#198]
I tried the latest docker support, by using 'docker compose up' , and got this exception: => ERROR [devika-backend-engine  8/20] RUN $HOME/.cargo/bin/uv venv

![image](https://github.com/stitionai/devika/assets/13262438/b6280b76-ef79-4aa4-8e39-a91ce5a281a9)

**Comment by juvi21** [comment]
The docker-compose command represents the legacy version of the tool. Try without the '-' e.g docker compose up should work.
