### ISSUE TITLE
On Click of dropdown create project button UI is not properly aligned

### ISSUE THREAD

**Issue by Dcode36** [stitionai/devika#199]
after click on drop down the create project button is not properly aligned its width and not looking good.

<img width="1451" alt="Screenshot 2024-03-27 at 11 40 12 PM" src="https://github.com/stitionai/devika/assets/92368983/06bea946-1e71-45ba-a808-efa4f2417c43">

**Comment by Vishnuxx** [comment]
will fix it

**Comment by rowbot1** [comment]
I get the same, thanks for reporting

**Comment by CDotNightHawk** [comment]
Same

**Comment by CDotNightHawk** [comment]
localhost/:1 Access to fetch at 'http://127.0.0.1:1337/api/project-list' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
api.js:28 
        
        
       GET http://127.0.0.1:1337/api/project-list net::ERR_FAILED 426 (Upgrade Required)
window.fetch @ fetcher.js?v=2a2b36c1:65
fetchProjectList @ api.js:28
(anonymous) @ +page.svelte:21
setInterval (async)
(anonymous) @ +page.svelte:20
run @ chunk-663KAPRR.js?v=2a2b36c1:30
(anonymous) @ chunk-663KAPRR.js?v=2a2b36c1:2136
flush @ chunk-663KAPRR.js?v=2a2b36c1:1333
init @ chunk-663KAPRR.js?v=2a2b36c1:2217
Root @ root.svelte:21
createProxiedComponent @ svelte-hooks.js?v=2a2b36c1:341
ProxyComponent @ proxy.js?v=2a2b36c1:242
Proxy<Root> @ proxy.js?v=2a2b36c1:349
initialize @ client.js?v=2a2b36c1:433
_hydrate @ client.js?v=2a2b36c1:2385
await in _hydrate (async)
start @ client.js?v=2a2b36c1:293
(anonymous) @ (index):1057
Promise.then (async)
(anonymous) @ (index):1056
Show 11 more frames
Show less
fetcher.js?v=2a2b36c1:65

**Comment by huangjingcai** [comment]
same with the model choose dropdown at the first time loading

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed

**Comment by raviteja-02** [comment]
Still I'm facing the error
![image](https://github.com/stitionai/devika/assets/120414406/443d590d-2e0f-4739-a216-38d34a60f720)

**Comment by zhaohaoyun** [comment]
Still I'm facing the error too
