### ISSUE TITLE
The Terminal XTerm widget gets squished down whenever the Browser widget is updated with a snapshot event

### ISSUE THREAD

**Issue by mufeedvh** [stitionai/devika#2]
## What's the issue?

The Browser Widget and the Terminal Widget share the half-row space in the main web UI. When the Browser gets populated with the browser sessions' snapshot, the Terminal Widget overflows the main app container due the the size of the Browser Widget changing.

See here: https://github.com/stitionai/devika/blob/main/ui/src/App.svelte#L46-L49

**Browser Widget:** https://github.com/stitionai/devika/blob/main/ui/src/components/BrowserWidget.svelte
**Terminal Widget:** https://github.com/stitionai/devika/blob/main/ui/src/components/TerminalWidget.svelte

## How to fix?

Make the Terminal Widget adapt to the size changes in the Browser Widget, also make the Browser Widget the same size filled by the snapshot image by default.

**Comment by VedantAnand17** [comment]
error404 is coming on all of the links sir
