### ISSUE TITLE
[ Feat ] Create Issues template and Extend Contribution guide.

### ISSUE THREAD

**Issue by i-Am-GhOsT** [stitionai/devika#20]
Hi Everyone,

[Arindam](https://linktr.ee/arindamtanti) this side. I recently came to know about this project via social media. I don't want to raise an irrelevant Issue/ feature request. So I was going through the codes and recent issues. Noticed there are no Issue Temples for this repo. This is a great project and I believe more contributions will come along the way. So having some issue templates for each type issue can  help me keep a format, segregation and also helps in case of automation, like blocking spam issues. Also we can extend the contribution guide for better code checkins.

Hence I am raising this issue as a feature request. If the maintainers agree with my point. I would like to take this task on me. 

Thanks and Regards
❤️❤️ Arindam

**Comment by i-Am-GhOsT** [comment]
Sample [Contribution Guidelines](https://tuxtechlab.github.io/Blogs/Contribution/?h=contr), [Issue templates](https://github.com/TuxTechLab/Blogs/tree/master/.github%2FISSUE_TEMPLATE)

**Comment by mufeedvh** [comment]
Created, thanks! 🙌
