### ISSUE TITLE
Devika isn't responding 

### ISSUE THREAD

**Issue by ilearnio** [stitionai/devika#206]
Aparentely because the agent's state on backend is null

![image](https://github.com/stitionai/devika/assets/14331216/31e3256a-12ea-47d8-b187-4b693b443ade)

**Comment by arunbhati** [comment]
+1, I'm facing same issue

**Comment by sainudheenp** [comment]
same issue here

**Comment by rajakumar05032000** [comment]
Have you guys pulled the latest code ? Because fix had been already merged, 12 hrs ago approx..

If yes, please check whether you have configured your API's correctly for LLM..

**Comment by rajakumar05032000** [comment]
If the issue still exist, can someone send the full logs and also would like to know which model you are using? ( I have tested well with Ollama & Groq mixtral) not with Open AI models

**Comment by zxconan** [comment]
<img width="543" alt="image" src="https://github.com/stitionai/devika/assets/2890376/e76b7fb7-aa29-466c-87bf-2880f68703e9">
Both Ollama and Groq, this is log from UI

**Comment by rajakumar05032000** [comment]
> Both Ollama and Groq, this is log from UI.
> 
> <img alt="image" width="543" src="https://private-user-images.githubusercontent.com/2890376/317638989-e76b7fb7-aa29-466c-87bf-2880f68703e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTIyOTIsIm5iZiI6MTcxMTYxMTk5MiwicGF0aCI6Ii8yODkwMzc2LzMxNzYzODk4OS1lNzZiN2ZiNy1hYTI5LTQ2NmMtODdiZi0yODgwZjY4NzAzZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDc0NjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ4NmU4OWM5YjhjMTM4MmE5MzBlMzc5MzFlNjQ2MmFlYjUxNWVhN2ZjNGEwYTBjMWFjMWZjYzlmMDE4NTgwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NxFtyYpN1g7aj125QZf7iYgxYfuaxheWgMPezENKzq4">
> Agent is not in completed state <img alt="image" width="730" src="https://private-user-images.githubusercontent.com/2890376/317640090-952ddd10-d6fc-4b21-af69-78236d4c4968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTIyOTIsIm5iZiI6MTcxMTYxMTk5MiwicGF0aCI6Ii8yODkwMzc2LzMxNzY0MDA5MC05NTJkZGQxMC1kNmZjLTRiMjEtYWY2OS03ODIzNmQ0YzQ5NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDc0NjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZmMzY0OTc2ZGNkYTRjMzZkMjI5YTkwMzk3NjNhNzFjMDFmZDFhNWFhOTk5NjYxZDcxY2U2MmQ0Y2JiMDI5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lWW5XdVI6v0iSn1LlTWJc6tl2Eb1msyYph8-FEbkOHs">

As I can see from the logs, token_usage is 322 &  agent is also active, which means your task is getting executed .

**Comment by rajakumar05032000** [comment]
> Aparentely because the agent's state on backend is null
> 
> ![image](https://private-user-images.githubusercontent.com/14331216/317594905-31e3256a-12ea-47d8-b187-4b693b443ade.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTM1NzksIm5iZiI6MTcxMTYxMzI3OSwicGF0aCI6Ii8xNDMzMTIxNi8zMTc1OTQ5MDUtMzFlMzI1NmEtMTJlYS00N2Q4LWIxODctNGI2OTNiNDQzYWRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4MDc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzODllYzYwMzc4ZGYzMGJhNzdhMjRmOTA1MmJmZDUxYjUxNjFmNzEyYzM5NjNjMWRiOGNjNTAzNmE3MmM2NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hynSdfqwfiLRV8XDE0cdXXtu5Vnw1toh8n6H5giculg)


Those who are facing issues, can you please create a new project in devika UI and and then add your query & check?

Only first prompt in a devika project, works and rest of the prompts yield no response from devika..

Only if devika itself asks you question, then only second or consequent prompts will yield response from devika..its a known issue.

**Comment by ysr171** [comment]
similar thing happening in new project with the first prompt

**Comment by zxconan** [comment]
keep sleeping

<img width="539" alt="image" src="https://github.com/stitionai/devika/assets/2890376/b29217df-e62e-4f44-bd91-bfa57d5d8c72">

a new project and first prompt
<img width="528" alt="image" src="https://github.com/stitionai/devika/assets/2890376/47177674-0718-45d4-9d63-575db9eb4aa3">

**Comment by rajakumar05032000** [comment]
> keep sleeping
> 
> <img alt="image" width="539" src="https://private-user-images.githubusercontent.com/2890376/317653756-b29217df-e62e-4f44-bd91-bfa57d5d8c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTU2MTQsIm5iZiI6MTcxMTYxNTMxNCwicGF0aCI6Ii8yODkwMzc2LzMxNzY1Mzc1Ni1iMjkyMTdkZi1lNjJlLTRmNDQtYmQ5MS1iZmE1N2Q1ZDhjNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDg0MTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZiZDc4MDkyM2I2NzBlMjhkYjNhMTRiYmM1ZjkyMjM5ZGRlZGZmMzMwMDlkYjg3NjYzZDFhNGI2YzYwMjIzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lcAviPU0G4tLAIV4d1vfdwDaVtzMPtVy_1A9c0djHLo">
> a new project and first prompt <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/2890376/317654133-47177674-0718-45d4-9d63-575db9eb4aa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTU2MTQsIm5iZiI6MTcxMTYxNTMxNCwicGF0aCI6Ii8yODkwMzc2LzMxNzY1NDEzMy00NzE3NzY3NC0wNzE4LTQ1ZDQtOWQ2My01NzVkYjllYjRhYTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDg0MTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFjN2MzMTRjOGYzZjg3NGM4NmUxYjk5MDY4ZTUxZWQ0YmE1MWY1ZmNjNWVjOTk0MDFkYzY1ODc0YmY1ZWExYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3MF7HjDRXlcbXujSagb5Hk1G2fz7DEUCUeiN10c8tRw">

Can you please send the full devika UI screenshot and logs of devika_agent.log file (which is present in logs folder) and also the model name.

**Comment by Guillaume351** [comment]
For ollama, there is an import missing. I've fixed it in my PR : #215

**Comment by sengarshiv** [comment]
> > keep sleeping
> > <img alt="image" width="539" src="https://private-user-images.githubusercontent.com/2890376/317653756-b29217df-e62e-4f44-bd91-bfa57d5d8c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTU2MTQsIm5iZiI6MTcxMTYxNTMxNCwicGF0aCI6Ii8yODkwMzc2LzMxNzY1Mzc1Ni1iMjkyMTdkZi1lNjJlLTRmNDQtYmQ5MS1iZmE1N2Q1ZDhjNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDg0MTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZiZDc4MDkyM2I2NzBlMjhkYjNhMTRiYmM1ZjkyMjM5ZGRlZGZmMzMwMDlkYjg3NjYzZDFhNGI2YzYwMjIzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lcAviPU0G4tLAIV4d1vfdwDaVtzMPtVy_1A9c0djHLo">
> > a new project and first prompt <img alt="image" width="528" src="https://private-user-images.githubusercontent.com/2890376/317654133-47177674-0718-45d4-9d63-575db9eb4aa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTU2MTQsIm5iZiI6MTcxMTYxNTMxNCwicGF0aCI6Ii8yODkwMzc2LzMxNzY1NDEzMy00NzE3NzY3NC0wNzE4LTQ1ZDQtOWQ2My01NzVkYjllYjRhYTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDg0MTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFjN2MzMTRjOGYzZjg3NGM4NmUxYjk5MDY4ZTUxZWQ0YmE1MWY1ZmNjNWVjOTk0MDFkYzY1ODc0YmY1ZWExYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3MF7HjDRXlcbXujSagb5Hk1G2fz7DEUCUeiN10c8tRw">
> 
> Can you please send the full devika UI screenshot and logs of devika_agent.log file (which is present in logs folder) and also the model name.

Facing same issue, any resolution found for this??

**Comment by NIkhilbadveli** [comment]
![image](https://github.com/stitionai/devika/assets/24986098/735c0f7a-5389-4181-bc22-f1797d627ee3)

I don't think this kind of polling is really the right approach to this. We should use https://pypi.org/project/pusher/ events to send any communication needed from the backend to the UI.

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
