### ISSUE TITLE
nothing can be clicked

### ISSUE THREAD

**Issue by mickiezhang** [stitionai/devika#213]
After  bun run dev ，nothing can be clicked, anyone know why?

<img width="2554" alt="image" src="https://github.com/stitionai/devika/assets/148047157/7a05d20f-4928-4533-b4b0-590c22a9e16e">

**Comment by apurvns** [comment]
make sure ollama is running on port 11434 , then refresh and click dropdown on right and left side of screens, its clickable and you will able to create new project and select models .

**Comment by start-life** [comment]
For me it works on 11434 but there is still this fault

**Comment by apurvns** [comment]
can you try running ui with 'bun run dev --host' with host parameter.

**Comment by start-life** [comment]
Now some work and some I couldn't create a new project and choose a model but the settings button doesn't work and I also can't choose the project from the list it doesn't work


  VITE v5.2.2  ready in 803 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://192.168.1.32:3000/
  ➜  press h + enter to show help
18:58:26 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:115:10 A11y: '#' is not a valid href attribute
18:58:26 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:124:14 A11y: '#' is not a valid href attribute
18:58:26 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:186:16 A11y: '#' is not a valid href attribute
18:58:27 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:115:10 A11y: '#' is not a valid href attribute
18:58:27 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:124:14 A11y: '#' is not a valid href attribute
18:58:27 [vite-plugin-svelte] C:/zxcv/devika/ui/src/lib/components/ControlPanel.svelte:186:16 A11y: '#' is not a valid href attribute

**Comment by thenetguy** [comment]
did devika write this repo? wsl install doesnt work , docker install doesnt work , whats going on here

**Comment by Unity20092024** [comment]
This app takes up soooo much space

**Comment by salin1771** [comment]
after we click on new project and we enter the project name it does not update the project name . basically that button does not work . Do you have any solution for this ?

![Screenshot 2024-03-31 234254](https://github.com/stitionai/devika/assets/101279376/1ced3d66-23cb-4420-a53c-b42111e747b9)

**Comment by janvi2021** [comment]
> did devika write this repo? wsl install doesnt work , docker install doesnt work , whats going on here

i guess yes

**Comment by janvi2021** [comment]
> after we click on new project and we enter the project name it does not update the project name . basically that button does not work . Do you have any solution for this ?
> 
> ![Screenshot 2024-03-31 234254](https://private-user-images.githubusercontent.com/101279376/318291668-1ced3d66-23cb-4420-a53c-b42111e747b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjM0OTIsIm5iZiI6MTcxMTk2MzE5MiwicGF0aCI6Ii8xMDEyNzkzNzYvMzE4MjkxNjY4LTFjZWQzZDY2LTIzY2ItNDQyMC1hNTNjLWI0MjExMWU3NDdiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwOTE5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzA1ZDBlMDY0YWM3NjhlM2ViMjk4NTcwMGE4ODE4ZDBjOTFlNDMyMzMwNjg0Njk4OTY1MWUyN2ZiZjMyODVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.96LNma95-fL-Q3hvxHWTkATKA2Yu_D-Sy1XfM876XkU)

stuck at this same issue

**Comment by Innary** [comment]
> > after we click on new project and we enter the project name it does not update the project name . basically that button does not work . Do you have any solution for this ?
> > ![Screenshot 2024-03-31 234254](https://private-user-images.githubusercontent.com/101279376/318291668-1ced3d66-23cb-4420-a53c-b42111e747b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjM0OTIsIm5iZiI6MTcxMTk2MzE5MiwicGF0aCI6Ii8xMDEyNzkzNzYvMzE4MjkxNjY4LTFjZWQzZDY2LTIzY2ItNDQyMC1hNTNjLWI0MjExMWU3NDdiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwOTE5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzA1ZDBlMDY0YWM3NjhlM2ViMjk4NTcwMGE4ODE4ZDBjOTFlNDMyMzMwNjg0Njk4OTY1MWUyN2ZiZjMyODVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.96LNma95-fL-Q3hvxHWTkATKA2Yu_D-Sy1XfM876XkU)
> 
> stuck at this same issue

SAME ISSUE

**Comment by Innary** [comment]
> > > after we click on new project and we enter the project name it does not update the project name . basically that button does not work . Do you have any solution for this ?
> > > ![Screenshot 2024-03-31 234254](https://private-user-images.githubusercontent.com/101279376/318291668-1ced3d66-23cb-4420-a53c-b42111e747b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjM0OTIsIm5iZiI6MTcxMTk2MzE5MiwicGF0aCI6Ii8xMDEyNzkzNzYvMzE4MjkxNjY4LTFjZWQzZDY2LTIzY2ItNDQyMC1hNTNjLWI0MjExMWU3NDdiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQwOTE5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzA1ZDBlMDY0YWM3NjhlM2ViMjk4NTcwMGE4ODE4ZDBjOTFlNDMyMzMwNjg0Njk4OTY1MWUyN2ZiZjMyODVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.96LNma95-fL-Q3hvxHWTkATKA2Yu_D-Sy1XfM876XkU)
> > 
> > 
> > stuck at this same issue
> 
> SAME ISSUE

I use `bun run dev --host` instead `bun run dev` .
And I use Network, likes: http://192.168.3.14:3000/.
It works.

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
