### ISSUE TITLE
bun install core dumped

### ISSUE THREAD

**Issue by uptopoint** [stitionai/devika#214]
$ bun install
Illegal instruction (core dumped)

I am getting this issue, I am trying this on ubuntu
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

I am not sure what is the issue and where dumped core is stored. Can someone help me or guide me to find the issue. 
I found on internet sometimes core dump happens if system don't support AVX2 instruction set. Can that be a issue here ?

**Comment by ARajgor** [comment]
find out more about problem here .https://github.com/oven-sh/bun/issues/67
