### ISSUE TITLE
Feature req: Have an option to talk with Devika (Text-to-voice)

### ISSUE THREAD

**Issue by Shalinluitel** [stitionai/devika#222]
Hello all, it would be great is there will be an option to integrate with Eleven Labs API for text-to-speech with Devika. Just a curiosity and first time participating.

**Comment by ARajgor** [comment]
a good thought. if want to contribute then start building ;)

**Comment by Shalinluitel** [comment]
Would love to but I don't know how to code that good

**Comment by ARajgor** [comment]
Okay not an issue. I consider this as a feature to be implement. Currently closing the issue.
