### ISSUE TITLE
Anaconda Issue?

### ISSUE THREAD

**Issue by GitDakky** [stitionai/devika#23]
Trying to execute bun run dev and get the following output:
...\devika\ui> bun run dev                            
bun: The term 'bun' is not recognized as a name of a cmdlet, function, script file, or executable program.                                   
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by chanmathew** [comment]
@GitDakky You need to install the Bun runtime, see here: https://bun.sh/docs/installation

**Comment by DatOneDue** [comment]
I get a little bit further. I have bun installed but when I run the bun run dev inside the \iu\ folder I get the following:

devika\devika\ui> bun run dev
$ vite
error: Failed to due to error bunsh: No such file or directory:

**Comment by GetGud** [comment]
I have the same issue

**Comment by chanmathew** [comment]
You'll need to install the dependencies by running _bun install_ first

**Comment by mufeedvh** [comment]
Please follow the [Quick Start](https://github.com/stitionai/devika?tab=readme-ov-file#quick-start) guide.
