### ISSUE TITLE
Breakdown chat interface to be more structured and grouped

### ISSUE THREAD

**Issue by franklinselva** [stitionai/devika#231]
I want to add this as a recommendation and see how it can be achieved. The current chat interface is straight responses from the agent. I think it would be nice to have something like this.

 - Add the requirements section for each project as a separate panel that can be updated by the user over time
 - Group the steps to be carried out for each requirement within a panel and this should help the user from scrolling back and forth for details
 - Simple chat interface from the agent to keep things as lively as ever. This is something we already have but need to filter out the above two items

This should help us tidy things up from UI and possibly extend to be more information-friendly. 

I am up for a discussion to see how this turns out and am open to seeing any design choices towards this direction.

**Comment by javacaliente** [comment]
Those are great ideas. They should be implemented.

**Comment by franklinselva** [comment]
#290

**Comment by ARajgor** [comment]
if you are moving to discussion then close this
