### ISSUE TITLE
Agent stuck doing nothing

### ISSUE THREAD

**Issue by jyana** [stitionai/devika#233]
Not sure which logs/files to check on but running on Windows 11 current versioning (3/28/24 @ 9PM ET) the agent appears to get stuck after browsing a few pages or after having setup some project files. It then sits there saying, "writing code" but there's no update to the database file or project files happening at all.

**Comment by pathquester** [comment]
Same issue here.

**Comment by hqnicolas** [comment]
it Just happend in Windows 10 to me...
Ubuntu works fine....

**Comment by mufeedvh** [comment]
Thank you for opening this issue, fixed here: https://github.com/stitionai/devika/commit/6b32459898c0515de1ba15b2d0ef760a588396da! 🙌
