### ISSUE TITLE
after runninf the frontend code i am getting this error  please help 

### ISSUE THREAD

**Issue by nani757** [stitionai/devika#239]
> bun run dev                                (devika) 
$ vite dev
file:///devika_test/devika_1/ui/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error: script "dev" exited with code 1

**Comment by paarthagrawal8** [comment]
Please check the node version that you are using try node 16.20

**Comment by nani757** [comment]
yes, it's working with ```node -v 18.20.0``` and the ```npm -v 10.5.0```
thanks paarth
