### ISSUE TITLE
ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by llg0363** [stitionai/devika#245]
i have got this problem when i browered in my chrome,here is the full error message:
ReferenceError: Request is not defined
    at getRequest (file:///Users/xxxxx/xxxxx/devika/ui/node_modules/@sveltejs/kit/src/exports/node/index.js:107:2)
    at file:///Users/xxxxx/xxxxx/devika/ui/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
i have started all the servic and installed all requements by flowing documentary steps, meanwhile updated my base enverament, but i still got this error, what should i do to fix this issue?

**Comment by arjunasuresh3** [comment]
+1

**Comment by amindala** [comment]
I am also experiencing the same problem. Could you please give a detailed solution? How to under the node from the environment?

**Comment by dimpu** [comment]
If you use nvm switch to version 20 or Install latest node version. 

`
nvm install 20 
nvm use 20
`

This should fix the issue.

**Comment by amindala** [comment]
> If you use nvm switch to version 20 or Install latest node version.
> 
> `nvm install 20 && nvm use 20`
> 
> This should fix the issue.

Thanks a lot. This fixed it.
