### ISSUE TITLE
Ollama Model

### ISSUE THREAD

**Issue by techriffic** [stitionai/devika#25]
Hello when i am choosing Ollama Models i am getting this error on terminal and Devika doesnt move forward, i have tried different ollama models but same issue, havnt tried openai or claude i want to test locally first

(devika) username@usernames-Macbook-M3-Max devika % python devika.py
24.03.22 02:28:49: root: INFO   : Booting up... This may take a few seconds
24.03.22 02:28:49: root: INFO   : Initializing Devika...
24.03.22 02:28:49: root: INFO   : Initializing Prerequisites Jobs...
24.03.22 02:28:49: root: INFO   : Loading sentence-transformer BERT models...
24.03.22 02:28:53: root: INFO   : BERT model loaded successfully.
 * Serving Flask app 'devika'
 * Debug mode: off
Token usage: 383
Exception in thread Thread-201 (<lambda>):
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devika/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devika/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/username/devika/devika.py", line 56, in <lambda>
    target=lambda: Agent(base_model=base_model).execute(prompt, project_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/devika/src/agents/agent.py", line 264, in execute
    plan = self.planner.execute(prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/devika/src/agents/planner/planner.py", line 70, in execute
    response = self.llm.inference(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/devika/src/llm/llm.py", line 58, in inference
    model = self.model_id_to_enum_mapping()[self.model_id]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: '7B - Q4_K_M'

**Comment by wrapss** [comment]
same

**Comment by dmerriman11** [comment]
Installing Ollama in your OS flavor solved it for me.

WIndows Ollama Docker.

**Comment by haseeb-heaven** [comment]
Yes i have same issue in MacOS as well

**Comment by vishnusureshperumbavoor** [comment]
I got the same error on linux

**Comment by vishnusureshperumbavoor** [comment]
function selectModel(model) {
    selectedModel = `${model[0]} (${model[1]})`;
    localStorage.setItem("selectedModel", model[0]);
  }
  
  error is not getting when the function is like this. but ain't nothing happening

**Comment by haseeb-heaven** [comment]
We need PR to fix this issue asap

**Comment by NinjaEde** [comment]
@vishnusureshperumbavoor 
Additionally you have to change the line above as well
`selectedModel = `${model[0]}`;`

This worked for me and I get answers from my local LLM.

**Comment by amjiddader** [comment]
> selectedModel = model[0];
>     localStorage.setItem("selectedModel", selectedModel);

Worked , Thanks..

**Comment by NinjaEde** [comment]
I think my above solution works only with the OLLAMA models, since the other models rely on the second parameter of the models array.

A more general and better solution is to change the server part.
Change the **src/llm/llm.py** to the following:

```
    OLLAMA_MODELS = [
        (
            model["name"],
            model["name"]
        )
        for model in Ollama.list_models()
    ]
```
and leave the frontend part like it was.

**Comment by techriffic** [comment]
> @vishnusureshperumbavoor Additionally you have to change the line above as well.
> 
> ```
>     selectedModel = model[0];
>     localStorage.setItem("selectedModel", selectedModel);
> ```
> 
> This worked for me and I get answers from my local LLM.

perfect! thanks
