### ISSUE TITLE
Devika stuck at duckduckgo search

### ISSUE THREAD

**Issue by vdsasi** [stitionai/devika#260]
Devika getting stuck at duckduckgo search. it is not showing any results that is pulled from the browser. instead it just showing that it is researching but it is not pulling any info from browser. here i am using claude api and i entered and setup perfectly it is working fine but browsing results are not being fetched.

![image](https://github.com/stitionai/devika/assets/94822289/ff364fbf-2878-483c-bc27-e46036716411)

**Comment by jonny7737** [comment]
I just installed Devika and have exactly the same issue.

**Comment by essamgoda** [comment]
I just installed Devika and have the same issue.

**Comment by essamgoda** [comment]
it worked after installing "playwright" as mentioned in [quick-start](https://github.com/stitionai/devika?tab=readme-ov-file#quick-start)

**Comment by essamgoda** [comment]
it worked but never continued to write code
it stops at the below point
> I'm currently analyzing the project prompt and identifying the key components of the plan.

**Comment by vdsasi** [comment]
> it worked after installing "playwright" as mentioned in [quick-start](https://github.com/stitionai/devika?tab=readme-ov-file#quick-start)

i installed playwright and all other dependencies that are required for this project

**Comment by essamgoda** [comment]
> > it worked after installing "playwright" as mentioned in [quick-start](https://github.com/stitionai/devika?tab=readme-ov-file#quick-start)
> 
> i installed playwright and all other dependencies that are required for this project. Even then it is not working

It worked once then every time sent a step-by-step plan then stuck in searching step

**Comment by essamgoda** [comment]
I found it was stuck with me in [this line](https://github.com/stitionai/devika/blob/f0f33b265563c50b80c180b523402365bbe6571e/src/agents/agent.py#L332) 
and I added this then it proceeded to the next steps
`if ask_user != "" and ask_user is not None:`

but never complete the code it sends task is completed but generated code is one file contain comments only

**Comment by TaylorBechard** [comment]
Seeing the same. Doesn't search the internet. Just confirms development is finished with commented file showing.

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
