### ISSUE TITLE
Frontend UI is glitchy on a phone

### ISSUE THREAD

**Issue by Polygons1** [stitionai/devika#262]
just open up the Devika web app on a phone (I am using an iPhone 14 Pro Max (latest iOS, latest Safari)) and you'll see the view is glitchy

![IMG_0206](https://github.com/stitionai/devika/assets/47899327/5467f4d9-407e-494b-91e7-fe4d0dcdb22d)

**Comment by Hackff1** [comment]
Bro how to install ollam in phone how you install in  phone

**Comment by Polygons1** [comment]
I am running the app on a server lol

**Comment by ARajgor** [comment]
fetch the latest changes. currnetly not responsive UI but we'll try.
https://github.com/stitionai/devika/pull/295
