### ISSUE TITLE
 error: postinstall script from "esbuild" terminated by SIGABRT (Abort) zsh: abort      bun install

### ISSUE THREAD

**Issue by SudeshGagare** [stitionai/devika#267]
sudeshwamangagare@Sudeshs-MacBook-Air ui % bun install 
bun install v1.0.36 (40f61ebb)
  🚚 @esbuild/darwin-arm64... dyld[9062]: Library not loaded: /opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib
  Referenced from: <4D1DFEA6-29A7-34D0-B5E6-63A9C5050318> /opt/homebrew/Cellar/node/20.3.1/bin/node
  Reason: tried: '/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/opt/homebrew/opt/icu4c/lib/libicui18n.73.dylib' (no such file), '/usr/local/lib/libicui18n.73.dylib' (no such file), '/usr/lib/libicui18n.73.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/opt/homebrew/Cellar/icu4c/74.2/lib/libicui18n.73.dylib' (no such file), '/usr/local/lib/libicui18n.73.dylib' (no such file), '/usr/lib/libicui18n.73.dylib' (no such file, not in dyld cache)

error: postinstall script from "esbuild" terminated by SIGABRT (Abort)
zsh: abort      bun install
sudeshwamangagare@Sudeshs-MacBook-Air ui %

**Comment by omkargadute** [comment]
there is a file called sample.config.toml just rename it to config.toml and fill in the APIs key as per your requirements

**Comment by SudeshGagare** [comment]
Thanks, now facing another exception while executing "bun install"

**Comment by SudeshGagare** [comment]
Ignore Resolved, need to upgrade the packages using "brew upgarde"
