### ISSUE TITLE
api/get-browser-snapshot can get any file in the filesystem

### ISSUE THREAD

**Issue by Polygons1** [stitionai/devika#270]
the endpoint api/get-browser-snapshot can send back any file in the system and this isn't really good...

**Comment by Polygons1** [comment]
even [Synk](https://snyk.io/) complains that there are 3 endpoints with the Path Traversal vulnerability ( api/get-browser-snapshot, api/download-project, api/download-project-pdf )

**Comment by ItsNeil17** [comment]
Yup this is quite a big vulnerability, if the contents of the files are also visible that would be really bad. Looking forward to a fix for this ^

**Comment by mufeedvh** [comment]
This app is intended to be functional on a local machine and not hosted on the Internet, but this should nevertheless be handled correctly. Will fix the LFI, thanks for raising the issue! 🙌
