### ISSUE TITLE
Model/Worker not replying/working on prompt

### ISSUE THREAD

**Issue by DopeDealers** [stitionai/devika#274]
**Describe the bug**
App does not reply at all with any project or model.

**To Reproduce**
1. Start all the servers
2. Click on project drop down choose a project and select a model of your choice
3. Send a prompt
4. Zero errors inside of console/webservers

**Expected behavior**
Model to start working on the prompt

**Screenshots**
[here](https://cdn.cyci.rocks/393996898945728500/firefox_gyF8swVHuI.png)

**Desktop**
 - OS: Ubuntu 22.04
 - Browser Firefox/chrome/edge
 - Version Latest commits

**Comment by sapoepsilon** [comment]
Same thing:
```
24.03.30 20:42:36: root: INFO   : /api/model-list GET
24.03.30 20:42:36: root: DEBUG  : /api/model-list GET - Response: {"models":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"],["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"],["Gemini 1.0 Pro","gemini-1.0-pro"],["Gemini 1.5 Pro","gemini-1.5-pro"],["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2-70B","llama2-70b-4096"],["GROQ GEMMA-7B-IT","gemma-7b-it"]]}

24.03.30 20:42:36: root: INFO   : /api/get-agent-state POST
24.03.30 20:42:36: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

24.03.30 20:42:36: root: INFO   : /api/get-messages POST
24.03.30 20:42:36: root: DEBUG  : /api/get-messages POST - Response: {"messages":null}

24.03.30 20:42:37: root: INFO   : /api/token-usage GET
24.03.30 20:42:37: root: INFO   : /api/project-list GET
24.03.30 20:42:37: root: DEBUG  : /api/token-usage GET - Response: {"token_usage":0}

24.03.30 20:42:37: root: DEBUG  : /api/project-list GET - Response: {"projects":["portfolio"]}

24.03.30 20:42:37: root: INFO   : /api/model-list GET
24.03.30 20:42:37: root: DEBUG  : /api/model-list GET - Response: {"models":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"],["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"],["Gemini 1.0 Pro","gemini-1.0-pro"],["Gemini 1.5 Pro","gemini-1.5-pro"],["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2-70B","llama2-70b-4096"],["GROQ GEMMA-7B-IT","gemma-7b-it"]]}

24.03.30 20:42:37: root: INFO   : /api/get-agent-state POST
24.03.30 20:42:37: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

24.03.30 20:42:37: root: INFO   : /api/get-messages POST
24.03.30 20:42:37: root: DEBUG  : /api/get-messages POST - Response: {"messages":null}

24.03.30 20:42:38: root: INFO   : /api/token-usage GET
24.03.30 20:42:38: root: INFO   : /api/project-list GET
24.03.30 20:42:38: root: DEBUG  : /api/token-usage GET - Response: {"token_usage":0}
24.03.30 20:42:38: root: DEBUG  : /api/project-list GET - Response: {"projects":["portfolio"]}


24.03.30 20:42:38: root: INFO   : /api/model-list GET
24.03.30 20:42:38: root: DEBUG  : /api/model-list GET - Response: {"models":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"],["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"],["Gemini 1.0 Pro","gemini-1.0-pro"],["Gemini 1.5 Pro","gemini-1.5-pro"],["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2-70B","llama2-70b-4096"],["GROQ GEMMA-7B-IT","gemma-7b-it"]]}

24.03.30 20:42:38: root: INFO   : /api/get-agent-state POST
24.03.30 20:42:38: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

24.03.30 20:42:38: root: INFO   : /api/get-messages POST
24.03.30 20:42:38: root: DEBUG  : /api/get-messages POST - Response: {"messages":null}
```

**Comment by coldworth** [comment]
same here24.03.31 11:39:46: root: INFO   : /api/model-list GET
24.03.31 11:39:46: root: DEBUG  : /api/model-list GET - Response: {"models":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"],["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"],["Gemini 1.0 Pro","gemini-1.0-pro"],["Gemini 1.5 Pro","gemini-1.5-pro"],["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2-70B","llama2-70b-4096"],["GROQ GEMMA-7B-IT","gemma-7b-it"],["codellama","codellama:7b-code"],["mistral","mistral:latest"],["openhermes","openhermes:latest"]]}

24.03.31 11:39:46: root: INFO   : /api/get-agent-state POST
24.03.31 11:39:46: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-03-31 11:36:21","token_usage":326}}

24.03.31 11:39:46: root: INFO   : /api/get-messages POST
24.03.31 11:39:46: root: DEBUG  : /api/get-messages POST - Response: {"messages":[{"from_devika":false,"message":"create a snake game in python","timestamp":"2024-03-31 11:36:21"}]}

**Comment by cocobeach** [comment]
Same here

**Comment by DopeDealers** [comment]
bump this issue

**Comment by pathquester** [comment]
Same issue.

**Comment by p971607** [comment]
me too

**Comment by ARajgor** [comment]
fetch the latest changes.

**Comment by DopeDealers** [comment]
Fetched the latest changes issue still persists.

**Comment by ARajgor** [comment]
> Fetched the latest changes issue still persists.

Share the logs
