### ISSUE TITLE
Completed task in 2/3 iterations

### ISSUE THREAD

**Issue by hgncom** [stitionai/devika#278]
Hello Devika Team and Community,

I've been exploring the capabilities of Devika to automate the development of a complex application. The project is structured into multiple steps, from selecting an appropriate framework to integrating with external systems for data exchange.

However, Devika completes the task prematurely after a few iterations of coding, indicating it's finished, even though the project requirements have not been fully met.

I am using the Bing + OpenAI API and Ollama is running. I tried with GPT model 3.5 and 4, but it gives the exact same result.

When I end the task in the command prompt it says: **The process tried to write to a nonexistent pipe.**

Anyone any idea why it so quickly stops and what I can do to prevent this?

Please see the attached screenshot and config below.

![Screenshot 2024-03-31 172946 - github](https://github.com/stitionai/devika/assets/33844627/1afad1df-0b0a-4239-9a42-471f4dd3c303)

[STORAGE]
SQLITE_DB = "db/devika.db"
SCREENSHOTS_DIR = "screenshots"
PDFS_DIR = "pdfs"
PROJECTS_DIR = "projects"
LOGS_DIR = "logs"
REPOS_DIR = "repos"
WEB_SEARCH = "bing"

[API_KEYS]
BING = "hidden"
GOOGLE_SEARCH = "<YOUR_GOOGLE_SEARCH_API_KEY>"
GOOGLE_SEARCH_ENGINE_ID = "<YOUR_GOOGLE_SEARCH_ENGINE_ID>"
CLAUDE = "<YOUR_CLAUDE_API_KEY>"
NETLIFY = "<YOUR_NETLIFY_API_KEY>"
OPENAI = "sk-hidden"
GROQ = "<YOUR_GROQ_API_KEY>"
GEMINI = "<YOUR_GEMINI_API_KEY>"

[API_ENDPOINTS]
BING = "hidden"
GOOGLE_SEARCH = "https://www.googleapis.com/customsearch/v1"
OLLAMA = "http://127.0.0.1:11434"

[LOGGING]
LOG_REST_API = "true"
LOG_PROMPTS = "false"

**Comment by ARajgor** [comment]
fetch the latest changes. if you are still getting the problem feel free to re-open
