### ISSUE TITLE
Devika completely frozen

### ISSUE THREAD

**Issue by Arenexu** [stitionai/devika#281]
**Describe the bug**
The problem I have is that I cannot interact with the devika UI at all and it seems as if Devika has not loaded models or projects in either.
When I try to for example open Devika settings, the UI goes into an infinite loading loop.

The backend and frontend behave normally.

**To Reproduce**

**Expected behavior**
I expected to be able to open the settings panel:

![image](https://github.com/stitionai/devika/assets/52036873/71e67872-240d-40cc-8b9d-289901c73d5b)

**Screenshots**
![image](https://github.com/stitionai/devika/assets/52036873/c2265447-7216-4cbe-be0a-0d19ff548530)
![image](https://github.com/stitionai/devika/assets/52036873/a6bba93b-dfed-4008-9438-abbc4da3c404)
![image](https://github.com/stitionai/devika/assets/52036873/4ba76c87-8032-448c-bd19-03b14ae87c81)

**Desktop:**
 - OS: Windows 11 64-bit
 - Browser Opera GX
 - Version 107.0.5045.79

Thanks for your help in advance

**Comment by Ahmet0691** [comment]
update all code

**Comment by ARajgor** [comment]
fetch the latest changes.
