### ISSUE TITLE
playwright._impl._errors.Error: It looks like you are using Playwright Sync API

### ISSUE THREAD

**Issue by anthonynovaes** [stitionai/devika#284]
When I request something more complex from Devika, it returns this error to me. Also, create a ticket for this bug.
 
  File "C:\Users\Anthony Novaes\AppData\Roaming\Python\Python312\site-packages\playwright\sync_api\_context_manager.py", line 
48, in __enter__
    raise Error(
playwright._impl._errors.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

**Comment by metasanjaya** [comment]
Same error here

**Comment by thatsmethen** [comment]
https://github.com/stitionai/devika/issues/279#issuecomment-2028930795

**Comment by cafeTechne** [comment]
Samesiez

**Comment by jyonny-byte** [comment]
Same here

**Comment by jmtatsch** [comment]
+1

**Comment by samuelbirocchi** [comment]
I fixed that in my branch. I can make a PR here

**Comment by cafeTechne** [comment]
You're the best! I spent the morning working on this!

**Comment by LeonieFreisinger** [comment]
Thanks @samuelbirocchi
