### ISSUE TITLE
按照GitHub上的安装要求安装了环境，但是打不开页面？

### ISSUE THREAD

**Issue by zhao1012** [stitionai/devika#285]
我按照坐着的要求配置了环境，但是打不开页面？服务已经正常启动了
![image](https://github.com/stitionai/devika/assets/38517343/edb29a77-4614-4bb3-8baa-ece66d0c3fa3)
![image](https://github.com/stitionai/devika/assets/38517343/27921112-0fd2-48dc-bd04-a1fe427f450e)

**Comment by LGinC** [comment]
安装版本为18.20的node试试

**Comment by zhao1012** [comment]
已解决，谢谢。

**Comment by liqwertyu** [comment]
> 安装版本为18.20的node试试

这里的版本是什么版本，我也有同样的问题
