### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by katmai** [stitionai/devika#291]
**Describe the bug**
stuck on running the software

**To Reproduce**
cd ui
bun install
bun run dev

**Expected behavior**
idk, never run the software. i'm expected the ui to spin up i guess

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
bun install v1.0.36 (40f61ebb)

 4 packages installed [369.00ms]
atlas@chia01:~/devika/ui$ bun run dev
$ vite dev
file:///home/atlas/devika/ui/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error: script "dev" exited with code 1

**Comment by ARajgor** [comment]
which node version are you using??

**Comment by katmai** [comment]
> which node version are you using??

node -v
v12.22.9

**Comment by ARajgor** [comment]
okay, so the frontend is solved. also your backend problem seems like a ollama. can you try to run without ollama

**Comment by katmai** [comment]
> okay, so the frontend is solved. also your backend problem seems like a ollama. can you try to run without ollama

i did a test swap to python 3.10 and it came online. is there a recommended python version that we should be using?

```
$ python devika.py
24.04.03 22:26:39: root: INFO   : Initializing Devika...
24.04.03 22:26:39: root: INFO   : Initializing Prerequisites Jobs...
24.04.03 22:26:44: root: INFO   : Loading sentence-transformer BERT models...
/home/atlas/devika/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
24.04.03 22:26:47: root: INFO   : BERT model loaded successfully.
24.04.03 22:26:49: root: INFO   : Ollama available
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
24.04.03 22:26:51: root: INFO   : Devika is up and running!
```

**Comment by matiyin** [comment]
> > which node version are you using??
> 
> node -v v12.22.9
> 
> now that you asked that question, i'm loading node18 and trying again.

switching from node 12.x to 18.x worked for me, linux mint 21.2

**Comment by ARajgor** [comment]
for node use >=18
for python use >=3.10 and <3.12
