### ISSUE TITLE
Use GPT4FREE since Devika is FULLY OPEN-SOURCE

### ISSUE THREAD

**Issue by keithorange** [stitionai/devika#30]
Also you should easily include gpt4free option. https://github.com/xtekky/gpt4free

**Comment by mufeedvh** [comment]
Looks cool, will check this out, thanks! 🙌

**Comment by TheMaskedAvengers** [comment]
Vaguely recall this reverse engineers the Open API API, so hoping it's just a case of changing the OpenAI end point to point at the gpt4free server and putting in the GPT4All API key....which seems to be always the same as far as I can see online...bit of a security issue there, perhaps.

In theory that gives you access to GPT4 free of charge. If you use bing chat you'll have a 30 prompt limit per conversation, but doubt devika takes that many to get the job done most of the time? Suspect other services don't have that limit perhaps?

**Comment by TheMaskedAvengers** [comment]
So think it's a just a case of specifying this URL as the end point for openai: http://localhost:1337/v1 and making up your own API key to use - see here:
https://github.com/xtekky/gpt4free/blob/main/docs/interference.md
