### ISSUE TITLE
Windows 10 Enterprise v19045 (Playwright Fail: No Media Features)

### ISSUE THREAD

**Issue by TaylorBechard** [stitionai/devika#301]
**Describe the bug**
Unable to install playwright due to Windows 10 Enterprise not having Media Features available:

**Screenshots**
![image](https://github.com/stitionai/devika/assets/145132624/9dfbe257-ab37-4fee-aad2-fad2e4a6c4f6)

![image](https://github.com/stitionai/devika/assets/145132624/988246d9-e520-4823-960b-f752f54526a3)

**To Reproduce**
Steps to reproduce the behavior in PoweShell:
1. Install bun
2. Install node
3. Run "npx playwright install --with-deps"
4. See error:
```

$ npx playwright install --with-deps
File C:\Users\tbechard\Documents\repos\devika\node_modules\playwright-core\bin\install_media_pack.ps1 cannot be loaded. The file
C:\Users\tbechard\Documents\repos\devika\node_modules\playwright-core\bin\install_media_pack.ps1 is not digitally signed. You cannot run this script on the current system. For more
information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
    + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

**Expected behavior**
Should install playwright with deps.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version: 22H2 19045.4046

**Additional context**
Looks like an issue with my version of windows not having the media services available from what I can see so far. Any help is greatly appreciated, thanks!

**Comment by ARajgor** [comment]
I guess it's a terminal issue. have tried this command in cmd
