### ISSUE TITLE
Should the open ai api key be given to run it??

### ISSUE THREAD

**Issue by sageakshay22** [stitionai/devika#305]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x306642d50>: Failed to establish a new connection: [Errno 2] Lookup timed out'))

can the backend for devika be run without api keys??

**Comment by obliviousz** [comment]
Nope, actually you need it. If you don't want to, then try Ollama and run llama2, it would not require.

But bing search API key is a must as it seemed to me.

**Comment by sageakshay22** [comment]
but the backend it not running even after giving the bing api also its shows the same error as before

**Comment by obliviousz** [comment]
Did you select llama2 model?

**Comment by sageakshay22** [comment]
my whole python backend is only not running its showing the open ai error

**Comment by sageakshay22** [comment]
frontend is working

**Comment by sageakshay22** [comment]
yes

**Comment by sageakshay22** [comment]
ill send

**Comment by obliviousz** [comment]
pip install urllib3==1.25.11



Run this

**Comment by sageakshay22** [comment]
The error traceback you've provided indicates several issues related to DNS resolution and connection problems, ultimately leading to a failure to establish a connection to openaipublic.blob.core.windows.net. Here's a breakdown of the issues:

DNS Resolution Error:

The first error seems to originate from a DNS resolution issue. It indicates that the DNS resolution lifetime expired after a certain period, likely due to malformed text input from the server. This error arises from the greendns.py module.
It seems to be caused by malformed text input from the DNS server.
Connection Timeout Error:

The second part of the traceback indicates a connection timeout error while trying to establish a connection to openaipublic.blob.core.windows.net. This error originates from the urllib3 and requests modules.
The specific error message indicates that the lookup timed out.
Max Retries Exceeded:

The third part of the traceback shows that max retries were exceeded while attempting to establish a connection to openaipublic.blob.core.windows.net.
These errors suggest there might be network issues, DNS configuration problems, or possibly issues with the server hosting openaipublic.blob.core.windows.net. To resolve these issues, you may consider the following steps:

Check your network connectivity and ensure that DNS resolution is functioning correctly.
Verify the DNS configuration and ensure that it's correctly resolving domain names.
Check if there are any firewall or security settings blocking the connection.
Ensure that the server openaipublic.blob.core.windows.net is reachable and operational.
If the issue persists, you may need to contact the administrator of the DNS server or the owner of the openaipublic.blob.core.windows.net server for further assistance.





 this is the error

**Comment by obliviousz** [comment]
https://stackoverflow.com/questions/39064126/failed-to-establish-a-new-connection

**Comment by ARajgor** [comment]
is it solved or not? if solved then close the issue
