### ISSUE TITLE
 unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by darrassi1** [stitionai/devika#306]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by obliviousz** [comment]
how did this error occur?

**Comment by darrassi1** [comment]
> how did this error occur?

When I run Devika for the first time

**Comment by obliviousz** [comment]
@darrassi1 Doesnt help much, can you tell me the exact place?

python3 devika.py? or bun run dev?

**Comment by darrassi1** [comment]
> @darrassi1 Doesnt help much, can you tell me the exact place?
> 
> python3 devika.py? or bun run dev? And line number. Can you send the full error.

python devika.py

**Comment by DavidBendahan** [comment]
I had the same problem on the 6th step of the installation:

> Start the Devika server:

`python devika.py`

### I solved by upgrading python to the [latest stable version](https://www.python.org/downloads/release/python-3119/) `3.11.9`

Then you will need to:

```
# Deactivate the current virtual environment
deactivate

# Remove the old virtual environment folder
Remove-Item venv -Recurse

# Create a new virtual environment with the updated Python version
python -m venv venv

# Activate the new virtual environment
.\venv\Scripts\Activate

# Reinstall the dependencies
pip install -r requirements.txt
```

hope it helps! Keep Coding 😎💻
