### ISSUE TITLE
Need more robust information to explain why a response from the model was invalid and know I'm not in an undefined loop

### ISSUE THREAD

**Issue by cafeTechne** [stitionai/devika#307]
**Describe the bug**
After asking a question to intercede on the initial (unsatisfactory plan), it seems as if I'm in some sort of loop : 
"Invalid response from the model, trying again...
24.04.02 10:50:32: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 71202}
24.04.02 10:50:52: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 70863}
Invalid response from the model, trying again...
24.04.02 10:50:52: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 71760}
24.04.02 10:51:08: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 71385}
Invalid response from the model, trying again...
24.04.02 10:51:08: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 72300}
"
**To Reproduce**
1. Ask a question
2. Ask another question when it is Active
3. See above.

**Expected behavior**
I expect more console output to explain what is happening and when it is happening--a config VERBOSE="true" would be useful.

**Screenshots**
![image](https://github.com/stitionai/devika/assets/20980982/af3e698f-8c24-4a31-a442-e7d92f9989ad)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox

**Comment by sinanisler** [comment]
ooof token usage :D

![image](https://github.com/stitionai/devika/assets/1686324/98bf449e-1a51-41d7-80e1-00f90f2b0109)

**Comment by phcha** [comment]
24.04.03 00:43:51: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 291755}
Invalid response from the model, trying again...
24.04.03 00:43:51: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 297391}
24.04.03 00:43:58: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 294960}
Invalid response from the model, trying again...
24.04.03 00:43:58: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 300647}
24.04.03 00:44:05: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 297908}
Invalid response from the model, trying again...
24.04.03 00:44:05: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 303749}
24.04.03 00:44:14: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 301448}
Invalid response from the model, trying again...
24.04.03 00:44:14: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 307070}
24.04.03 00:44:23: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 305445}
Invalid response from the model, trying again...
24.04.03 00:44:23: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 310729}
24.04.03 00:44:30: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 308266}
Invalid response from the model, trying again...
24.04.03 00:44:30: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 313969}
24.04.03 00:44:41: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 313296}
Invalid response from the model, trying again...
24.04.03 00:44:41: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 318104}
24.04.03 00:44:47: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 315421}
Invalid response from the model, trying again...
24.04.03 00:44:48: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 321234}
24.04.03 00:44:54: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 318597}
Invalid response from the model, trying again...
24.04.03 00:44:54: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 324387}


I also encounter the same problem, how to solve it?

**Comment by Whytehorse2022** [comment]
Check your account with your LLM provider. They have hard limits on number of requests, context window, token usage, etc. Sometimes their error message in the API is cryptic like the one you're seeing. Also these LLMs go up and down randomly when heavily used during peak hours.

**Comment by ARajgor** [comment]
> **Describe the bug** After asking a question to intercede on the initial (unsatisfactory plan), it seems as if I'm in some sort of loop : "Invalid response from the model, trying again... 24.04.02 10:50:32: root: INFO : SOCKET tokens MESSAGE: {'token_usage': 71202} 24.04.02 10:50:52: root: INFO : SOCKET tokens MESSAGE: {'token_usage': 70863} Invalid response from the model, trying again... 24.04.02 10:50:52: root: INFO : SOCKET tokens MESSAGE: {'token_usage': 71760} 24.04.02 10:51:08: root: INFO : SOCKET tokens MESSAGE: {'token_usage': 71385} Invalid response from the model, trying again... 24.04.02 10:51:08: root: INFO : SOCKET tokens MESSAGE: {'token_usage': 72300} " **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Ask a question
> 2. Ask another question when it is Active
> 3. See above.
> 
> **Expected behavior** I expect more console output to explain what is happening and when it is happening--a config VERBOSE="true" would be useful.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/20980982/318841016-af3e698f-8c24-4a31-a442-e7d92f9989ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNzI4ODEsIm5iZiI6MTcxMjE3MjU4MSwicGF0aCI6Ii8yMDk4MDk4Mi8zMTg4NDEwMTYtYWYzZTY5OGYtOGMyNC00YTMxLWE0NDItZTdkOTJmOTk4OWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE5Mjk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOTE3MTAxNTdkNjQ2NzA1MmFhN2E0YzczZTVkNTA2YjRjODU4MmEzYjc3MmMxMzI0ZjBkNjg5YTg1ZDVmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bxk4B5ZXa5dXB96uvAhn99v0UfGEWYDh-5qOmBT691Q)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu
> * Browser Firefox
> * Version [e.g. 22]

which model are you using??

**Comment by cafeTechne** [comment]
I am using open llama local models. There is no token limit.

**Comment by alex89607** [comment]
The same error

**Comment by mast3rm1nd** [comment]
same...

**Comment by ARajgor** [comment]
fixed. fetch the latest changes. for more read the changelog in discord.
