### ISSUE TITLE
Agent always quits after discovering an error

### ISSUE THREAD

**Issue by borthdor** [stitionai/devika#320]
The agents always work till he finds this error and then says the task is completed even it still has like 10 steps to do. How can i fix this?

![7a7b7e67141978b29c411d39b21ec8c5](https://github.com/stitionai/devika/assets/59848934/2067a44d-28fc-489a-a010-318d249644d6)

**Comment by obliviousz** [comment]
I want to reproduce this same error. Can you give me the prompt of the project?

**Comment by obliviousz** [comment]
Maybe this was the issue in the patcher file.

https://github.com/stitionai/devika/pull/324

**Comment by Parth-Jain-2002** [comment]
Yeah that 3 lines in patcher.py were problematic. Have opened a pull request for that #321
