### ISSUE TITLE
Minimum system requirements ?

### ISSUE THREAD

**Issue by groozaop** [stitionai/devika#328]
I dont have a system with GPU , so i requested if anyone can get it work on Google Colab T4 GPU.. but that never got addressed..

Someone suggested to use github codespace but it runs out of memory.

So , i tried launching it via gitpod , Finally got docker up ,.. but Still its kind of dead , cant create a new project ( 8 Core, 16GB ram machine)

What am i doing wrong ?

**Comment by Whytehorse2022** [comment]
It looks like you have 2 options. You can use an LLM through an API or you can run an LLM locally. If you don't have a GPU, I recommend using the API. All you need for that is an account with chatGPT/Claude/Gemini/etc. Then the amount of ram is just for the browser interface. It looks like you have plenty of ram for that.

**Comment by ARajgor** [comment]
https://github.com/stitionai/devika/pull/387
