### ISSUE TITLE
access from differnet ip

### ISSUE THREAD

**Issue by vital121** [stitionai/devika#333]
**Is your feature request related to a problem? Please describe.**
when i try to connect to the devika from a differnet pc the socket io points to 127.0.0.1

**Describe the solution you'd like**
api request in browser goto 127.0.0.1:1337

**Describe alternatives you've considered**
set the ip in the env file

**Comment by agrajagco** [comment]
add --host to your line where you invoke 

`bun run dev`

so instead you would run

`bun run dev --host`
