### ISSUE TITLE
Following the simple installation instructions results in an error in building wheel for fastlogging

### ISSUE THREAD

**Issue by JonMike12341234** [stitionai/devika#34]
1.git clone https://github.com/stitionai/devika.git
2.cd devika
3.pip install -r requirements.txt

installation goes fine until building the wheel for fastlogging:

Building wheels for collected packages: fastlogging, keybert, svglib
  Building wheel for fastlogging (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      Creating C:\Users\JonMi\AppData\Local\Temp\pip-install-j4bbgzah\fastlogging_55cbaebdbb0042b698ab20777b87b3f5\fastlogging\fastlogging.pyx
      Creating C:\Users\JonMi\AppData\Local\Temp\pip-install-j4bbgzah\fastlogging_55cbaebdbb0042b698ab20777b87b3f5\fastlogging\network.pyx
      building with Cython 3.0.9
      Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
      Compiling fastlogging\fastlogging.pyx because it changed.
      Compiling fastlogging\network.pyx because it changed.
      [1/2] Cythonizing fastlogging\fastlogging.pyx
      [2/2] Cythonizing fastlogging\network.pyx
      C:\Users\JonMi\miniconda3\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running bdist_wheel
      running build
      running build_ext
      building 'fastlogging.fastlogging' extension
      creating build
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\Users
      creating build\temp.win-amd64-cpython-311\Release\Users\JonMi
      creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData
      creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local
      creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp
      creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp\pip-install-j4bbgzah
      creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp\pip-install-j4bbgzah\fastlogging_55cbaebdbb0042b698ab20777b87b3f5
      creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp\pip-install-j4bbgzah\fastlogging_55cbaebdbb0042b698ab20777b87b3f5\fastlogging
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\JonMi\miniconda3\include -IC:\Users\JonMi\miniconda3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\cppwinrt" /EHsc /TpC:\Users\JonMi\AppData\Local\Temp\pip-install-j4bbgzah\fastlogging_55cbaebdbb0042b698ab20777b87b3f5\fastlogging\fastlogging.cpp /Fobuild\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp\pip-install-j4bbgzah\fastlogging_55cbaebdbb0042b698ab20777b87b3f5\fastlogging\fastlogging.obj /O2 /EHsc /D__PYX_FORCE_INIT_THREADS=1
      fastlogging.cpp
      C:\Users\JonMi\AppData\Local\Temp\pip-install-j4bbgzah\fastlogging_55cbaebdbb0042b698ab20777b87b3f5\fastlogging\fastlogging.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fastlogging
  Running setup.py clean for fastlogging
  Building wheel for keybert (setup.py) ... done
  Created wheel for keybert: filename=keybert-0.8.4-py3-none-any.whl size=39256 sha256=49ecbd373e2a3282f02f94654ffaac049897c0b3c313705b0930acdedd8d4a30
  Stored in directory: C:\Users\JonMi\AppData\Local\Temp\pip-ephem-wheel-cache-ia45drz4\wheels\a0\c7\34\c35525fc11f76fe759878e01896b47c46598ff359e3e0aa4b2
  Building wheel for svglib (setup.py) ... done
  Created wheel for svglib: filename=svglib-1.5.1-py3-none-any.whl size=30977 sha256=6d6af65220c99ca3964dcae5b80789b029158e6c7b5c717ad0989bb01ec1f05d
  Stored in directory: C:\Users\JonMi\AppData\Local\Temp\pip-ephem-wheel-cache-ia45drz4\wheels\7e\01\0e\e6e336915d6e8448890a695770ba88fe030cc71060988016f6
Successfully built keybert svglib
Failed to build fastlogging
ERROR: Could not build wheels for fastlogging, which is required to install pyproject.toml-based projects

Any ideas why this would occur.  
I double checked and made sure MSVC build tools are up to date

**Comment by cyberiumabc** [comment]
Try setup.sh first. I installed in MacOS, and works fine. Also Transformers and Ollama have their own requirements for windows. This repo depends on those 2, so ensure that those 2 work properly.

**Comment by DatOneDue** [comment]
If you are doing this on Windows, you need to make sure your VS is updated to the latest version, I also recommend installing the latest version of powershell then follow these steps:
Navigate to the dir you will be installing Devika and then in the address bar powershell or cmd and enter Python  -n venv devika python=3.11 (I'm not sure if this is the correct version but I could install with this one) and then cd into the venv dir and python venv\Devika\Scripts\activate

You should be able to follow the instructions from here and get it to install.

**Comment by JonMike12341234** [comment]
Thanks for the tips.  
1. I ran setup.sh and got a similar output:
 
``` creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp\pip-install-qjjb4vrp
  creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp\pip-install-qjjb4vrp\fastlogging_981bb67394e34b52917e35297ab06db4
  creating build\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp\pip-install-qjjb4vrp\fastlogging_981bb67394e34b52917e35297ab06db4\fastlogging
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\JonMi\miniconda3\include -IC:\Users\JonMi\miniconda3\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /TpC:\Users\JonMi\AppData\Local\Temp\pip-install-qjjb4vrp\fastlogging_981bb67394e34b52917e35297ab06db4\fastlogging\fastlogging.cpp /Fobuild\temp.win-amd64-cpython-311\Release\Users\JonMi\AppData\Local\Temp\pip-install-qjjb4vrp\fastlogging_981bb67394e34b52917e35297ab06db4\fastlogging\fastlogging.obj /O2 /EHsc /D__PYX_FORCE_INIT_THREADS=1
  fastlogging.cpp
  C:\Users\JonMi\AppData\Local\Temp\pip-install-qjjb4vrp\fastlogging_981bb67394e34b52917e35297ab06db4\fastlogging\fastlogging.cpp : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1
  [end of output]```

2. I have checked for (and updated) MSVC build tools
3. transformers seems in proper function 

```pip show transformers
Name: transformers
Version: 4.38.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: C:\Users\JonMi\miniconda3\Lib\site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: TTS```

4. running ```pip show ollama``` resulted in ```WARNING: Package(s) not found: ollama``` 
so I installed ollama ```pip install ollama```,
```I:\AI_Programs\devika\devika>pip show ollama
Name: ollama
Version: 0.1.7
Summary: The official Python client for Ollama.
Home-page: https://ollama.ai
Author: Ollama
Author-email: hello@ollama.com
License: MIT
Location: C:\Users\JonMi\miniconda3\Lib\site-packages
Requires: httpx
Required-by:```

5.  Closing console and reopening, then retrying ```pip install -r requirements.txt``` once more resulted in the same error as before.

6. Following suggestion to install Devika from an isolated python 3.11 environment now....
```Python -n venv devika python=3.11```
-command not recognized...
editing suggested command to ->
```Python -m venv python=3.11```
going back to directory with requirements.txt: ```cd..``
running ```pip install -r requirements.txt```
which resulted in:
A successful installation!
Thanks for the help!

**Comment by ntrpnr** [comment]
Got the same error.

On Windows, I upgraded Visual Studio build tools and **removed all Python installations**. Then I installed Python 3.12 from Microsoft Store. This made it work.

**Comment by LuKaarGit** [comment]
Anyone else seeing this your environment is likely using wrong python version. use 3.11

**Comment by gauthierbuttez** [comment]
I have same issue:

```
Failed to build fastlogging
ERROR: Could not build wheels for fastlogging, which is required to install pyproject.toml-based projects

```
