### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f64c' in position 120: character maps to <undefined>

### ISSUE THREAD

**Issue by JuanBerta** [stitionai/devika#340]
When I'm asked by the model to help her find documentation, I input an url in the prompt, and after clicking the button for sending the prompt, I receive this message

> Traceback (most recent call last):
  File "C:\Users\Pc\anaconda3\envs\devika\lib\site-packages\fastlogging\fastlogging.py", line 401, in _logMessage
    self.__writePending()
  File "C:\Users\Pc\anaconda3\envs\devika\lib\site-packages\fastlogging\fastlogging.py", line 360, in __writePending
    self.F.write(data)
  File "C:\Users\Pc\anaconda3\envs\devika\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f64c' in position 120: character maps to <undefined>

1. Enter the program (localhost)
2. Create a new project
3. Select "Google" as search engine select "gemma:2b" as ollama model
4. Write a prompt (Example: write a calculator in python)
5. The model asks for help with documentation in TKinter or PySimpleGUI
6. Write a prompt with an url guiding to documentation

**Expected behavior**
I expect that after giving it the url, it would search inside the page

**Actual Result**
I receive the error on the top of my issue

**Screenshot**
![CharEncoder Error](https://github.com/stitionai/devika/assets/42556410/3062427a-8820-4823-b4be-490bcf3af2e7)

**Device information**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 123.0.6312.105

**Comment by MrAnayDongre** [comment]
You are encountering this due to the program attempting to write a Unicode character that isn't supported by default. Try explicitly updating the `fastlogging` library. Check out the `fastlogging.py` from the [git repo ](https://github.com/brmmm3/fastlogging/blob/843c885c4ba9686c53e930c69e4541eddd1fc3fd/fastlogging/fastlogging.py#L4)

After updating check if it supports `UTF-8` encoding.

**Comment by ARajgor** [comment]
it's a logger issue. not a problem there is already pr and it is merged. #350
