### ISSUE TITLE
Blank screen when trying to open settings page 

### ISSUE THREAD

**Issue by notV3NOM** [stitionai/devika#344]
A blank screen appears when pressing the settings button 

1. Start Backend and UI
2. Click on settings button on the left navbar

**Expected behavior**
The settings page opens

**Screenshots**
<img width="458" alt="image" src="https://github.com/stitionai/devika/assets/141054835/d6b7c5b7-5feb-418e-b2e1-1c947aa1808a">

**Desktop (please complete the following information):**
 - OS : WSL2
 - Browser : Chrome 
 - Version : v123 (latest)

**Additional context**
Once the blank page appears, navigating to other pages also doesn't work until a hard refresh. 
It is possible to open the settings page by directly navigating to `http://127.0.0.1:3000/settings`.  Even in this case pressing the settings button on the navbar (after navigating to another page)  will show a blank page

**Comment by obliviousz** [comment]
Did you pip install -r requirements.txt after yesterday?

**Comment by csaicharan** [comment]
on refresh, at least, you can be able to view the settings.

**Comment by visaeon** [comment]
same issues here ......

Are you able to start a new project as i cant do that either

**Comment by notV3NOM** [comment]
> on refresh, at least, you can be able to view the settings.

@csaicharan  Yes , its not a blocking issue. And I prefer changing those in `config.toml` itself 

> same issues here ......
> 
> Are you able to start a new project as i cant do that either

 @visaeon  Im able to start a new project and use devika normally . Maybe your issue is related to https://github.com/stitionai/devika/issues/341

**Comment by visaeon** [comment]
No..... have tried requirements install , pulled new update,
interface loads but nothing working 

  VITE v5.2.8  ready in 998 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
  
  PS C:\Devika> python devika.py
24.04.04 20:19:26: root: INFO   : Initializing Devika...
24.04.04 20:19:26: root: INFO   : Initializing Prerequisites Jobs...
24.04.04 20:19:33: root: INFO   : Loading sentence-transformer BERT models...
24.04.04 20:19:37: root: INFO   : BERT model loaded successfully.
24.04.04 20:19:38: root: INFO   : Ollama available
24.04.04 20:19:39: root: INFO   : Devika is up and running!



The only error i get is this one 

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-status 1.62.1 requires protobuf>=4.21.6, but you have protobuf 3.20.3 which is incompatible.   
tensorboardx 2.5.1 requires protobuf<=3.20.1,>=3.8.0, but you have protobuf 3.20.3 which is incompatible.
tensorflow 2.10.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 3.20.3 which is incompatible. 
tensorflow 2.10.1 requires tensorboard<2.11,>=2.10, but you have tensorboard 2.14.0 which is incompatible.


I tried to get claude 3 to troubleshoot it but when i run its fix the server no longer runs 

pip install mediapipe~=0.10.3 protobuf~=3.19.0 tb-nightly~=2.15.0a20230813 tensorboardx~=2.5.1 tensorflow~=2.10.1 tensorboard~=2.10.0

so i just rerun requirements text and it fixes the backend but the same UI error persists

**Comment by notV3NOM** [comment]
@visaeon  This is a different issue from https://github.com/stitionai/devika/issues/344 , I would recommend using a blank python 3.10 venv and opening a new issue
