### ISSUE TITLE
Error on Bun run dev

### ISSUE THREAD

**Issue by DatOneDue** [stitionai/devika#36]
I cd to the ui folder and bun run dev but I receive the following error message:

%USER%\venv\devika\ui> bun run dev
$ vite
error: Failed to due to error bunsh: No such file or directory:

**Comment by Vishnuxx** [comment]
Have you installed bun on your machine?

**Comment by amjiddader** [comment]
Make sure you are using  latest node and npm. (use NVM for node) \
inside ui folder ignore errors and  run: `npm install ` then `npm update --legacy-peer-deps` then `bun install -f`

Now Start: `bun run dev`


👍🏼  Hope this will help.

**Comment by DatOneDue** [comment]
@j3rry01v thank you so much! bun i vite worked for me!!!

**Comment by anjanakg** [comment]
This worked for me: 
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

**Comment by Delfigore** [comment]
"npm run dev" worked for me

**Comment by anujcb** [comment]
(devika) PS F:\work\Devika\Devika\ui> bun run dev
$ vite dev
**bun: command not found: vite**
error: script "dev" exited with code 1


Do i need to change the package.jason? or install some bun0vite plugin?

**Comment by anujcb** [comment]
never mind...i ran this and it worked

**bun i vite**

**Comment by ARajgor** [comment]
first install bun
then ` bun install `
then ` bun i vite `
then `bun run dev`

**Comment by nicohorn** [comment]
If anyone encounters this error using Windows, make sure the path you're using for you project doesn't cotain rare characters, such as accent marks and try to not use spaces when naming folders or files.

**Comment by GermanJablo** [comment]
Thanks @nicohorn! What a small world 😂

**Comment by nicohorn** [comment]
> Thanks @nicohorn! What a small world 😂

Jajaj de nada!

**Comment by HilmiZul** [comment]
> Make sure you are using latest node and npm. (use NVM for node) inside ui folder ignore errors and run: `npm install ` then `npm update --legacy-peer-deps` then `bun install -f`
> 
> Now Start: `bun run dev`
> 
> 👍🏼 Hope this will help.

thank you.
