### ISSUE TITLE
Installation guide incomplete, simply not working

### ISSUE THREAD

**Issue by xphraze1989** [stitionai/devika#378]
**Describe the bug**
installation guide incomplete, simply not working.
in Windows 11: 

PS C:\devika\devika\ui> bun run dev
$ vite dev
44277 |         sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath)
44278 |       );
44279 |     }
44280 |   };
44281 |   try {
44282 |     return fs$7.watch(path, options, handleEvent);
                   ^
EBUSY: EBUSY watching "C:/devika/devika/ui"
 syscall: "watch"
   path: "C:/devika/devika/ui"
   
in Fedora Linux 39:
playwritght install --with-deps
just gives command not found...

**To Reproduce**
1. system not been used for development, Windows 11 or Fedora Linux 39
2. Following the steps in the installation guide

**Expected behavior**
the steps in the guide should work

**Desktop (please complete the following information):**
Windows 11 and Fedora Linux 39

**Additional context**
further more, there were alott more problems on my way to this point, that i had to find a solution to. Unmentioned in the installation guide. like for eksample, do i use the terminal, vscode or powershell. it is not self explaning. If when i run a particular line, and are forced to restart commandline, do i need to start from the beginning ?

i highly suggest when write an installation guide. Use a fresh system without the hidden traces of a developer

**Comment by javacaliente** [comment]
I've had the same issue and keep trying to get clarification.  I've made a pull request #268 to delete the ##Quick Start, hoping just to get focus on the ##Installation.

I think a lot of the bugs and feedback they get are from conflicting installation guides. After 2.5 days I gave up and am waiting until further advice of how to proceed.

**Comment by cue232s** [comment]
What error are you getting?

**Comment by xphraze1989** [comment]
I haven't read the rules, but I can guess that questions aren't allowed. However, I am going to ask anyway because I can't find the answer anywhere...

So, I am wondering why Python is chosen over other frameworks for these types of projects. I can see that Python is easy for the developer, but I would have been greatly demotivated to carry out my project if I knew that I was doing it in a language/framework that didn't have any good deployment solution. It means that it doesn't matter how much work I did and how great I did the product, it would never become something of a hit because it would only reach the ones who are familiar with or did\does Python development. Why isn't, for example, Qt used? It is a cross-platform framework, and even as a web app.

As I have read and understand it, Python isn't meant or made for application development, but for scientific research, or as a inplementation for plugin support inn core applications written in different languages. Server applications. but never written entirely in python. In my opinion, it's sad to see Python being chosen as an allaround solution over and over again for these types of projects. This project is written as a server application. 

But Devika is a developer tool, it needs file/folder access on the local computer. Eventualy compiler access, maybe able to interact with an IDE. it doesent belong in a webbrowser at all. It needs to be a desktop application. i understand the choise when the developer sais he did it for fun in 3 days, he is god damn it capable, i am sad about Python being the choise, becouse the project is outstanding, and i want people to be able to install and run it, i want to run it on my workstation.

Please correct me and change my opinion if I am on the wrong track, I could be.

**Comment by javacaliente** [comment]
ya you're right, about picking a bad spot to post this.  Hardly anybody will this your post.
I appreciate the dialog about framework and would like to see the reply to it. Can you post your comment in discord general channel?

**Comment by javacaliente** [comment]
> I haven't read the rules, but I can guess that questions aren't allowed. However, I am going to ask anyway because I can't find the answer anywhere...

> Please correct me and change my opinion if I am on the wrong track, I could be.

ya you're right, about picking a bad spot to post this. Hardly anybody will see your post.
I appreciate the dialog about framework and would like to see the reply to it. Can you post your comment in the discord general channel?

**Comment by xphraze1989** [comment]
yeah, i did, edited some, and added some.. curious my self

**Comment by nocturnalguru** [comment]
Are you missing a semicolon?

**Comment by ARajgor** [comment]
> **Describe the bug** installation guide incomplete, simply not working. in Windows 11:
> 
> PS C:\devika\devika\ui> bun run dev $ vite dev 44277 | sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath) 44278 | ); 44279 | } 44280 | }; 44281 | try { 44282 | return fs$7.watch(path, options, handleEvent); ^ EBUSY: EBUSY watching "C:/devika/devika/ui" syscall: "watch" path: "C:/devika/devika/ui"
> 
> in Fedora Linux 39: playwritght install --with-deps just gives command not found...
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. system not been used for development, Windows 11 or Fedora Linux 39
> 2. Following the steps in the installation guide
> 
> **Expected behavior** the steps in the guide should work
> 
> **Desktop (please complete the following information):** Windows 11 and Fedora Linux 39
> 
> **Additional context** further more, there were alott more problems on my way to this point, that i had to find a solution to. Unmentioned in the installation guide. like for eksample, do i use the terminal, vscode or powershell. it is not self explaning. If when i run a particular line, and are forced to restart commandline, do i need to start from the beginning ?
> 
> i highly suggest when write an installation guide. Use a fresh system without the hidden traces of a developer

frontend commands: 
`bun install`
`bun -i vite` (if you are facing vite issue)
`bun run dev`

backend:
- create virtual env
- activate it
- install requirements.txt
- run `python devika.py`


My systems:
```
Windows 11
Node js - 20.9.0
python - 3.11
```
node version should be >= 16

**Comment by jmtatsch** [comment]
why not try the dockerized version?

its as easy as
```
docker compose build
docker compose up
```

**Comment by xphraze1989** [comment]
this is not how you install Spotify or Firefox, or vscode for that matter. i am so glad that vscode didnt require me to access it trough local address in a webbrowser

**Comment by xphraze1989** [comment]
> > **Describe the bug** installation guide incomplete, simply not working. in Windows 11:
> > PS C:\devika\devika\ui> bun run dev $ vite dev 44277 | sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath) 44278 | ); 44279 | } 44280 | }; 44281 | try { 44282 | return fs$7.watch(path, options, handleEvent); ^ EBUSY: EBUSY watching "C:/devika/devika/ui" syscall: "watch" path: "C:/devika/devika/ui"
> > in Fedora Linux 39: playwritght install --with-deps just gives command not found...
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. system not been used for development, Windows 11 or Fedora Linux 39
> > 2. Following the steps in the installation guide
> > 
> > **Expected behavior** the steps in the guide should work
> > **Desktop (please complete the following information):** Windows 11 and Fedora Linux 39
> > **Additional context** further more, there were alott more problems on my way to this point, that i had to find a solution to. Unmentioned in the installation guide. like for eksample, do i use the terminal, vscode or powershell. it is not self explaning. If when i run a particular line, and are forced to restart commandline, do i need to start from the beginning ?
> > i highly suggest when write an installation guide. Use a fresh system without the hidden traces of a developer
> 
> frontend commands: `bun install` `bun -i vite` (if you are facing vite issue) `bun run dev`
> 
> backend:
> 
> * create virtual env
> * activate it
> * install requirements.txt
> * run `python devika.py`
> 
> My systems:
> 
> ```
> Windows 11
> Node js - 20.9.0
> python - 3.11
> ```
> 
> node version should be >= 16

PS C:\devika\devika\ui> bun install
bun install v1.1.1 (ca1dbb4e)
  🔒 Saving lockfile... error: failed to open lockfile: EBUSY
PS C:\devika\devika\ui> bun -i vite
44277 |         sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath)
44278 |       );
44279 |     }
44280 |   };
44281 |   try {
44282 |     return fs$7.watch(path, options, handleEvent);
                   ^
EBUSY: EBUSY watching "C:/devika/devika/ui"
 syscall: "watch"
   path: "C:/devika/devika/ui"

      at new FSWatcher (node:fs:105:27)
      at watch2 (node:fs:284:199)
      at createFsWatchInstance (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44282:12)
      at setFsWatchListener (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44329:15)
      at _watchWithNodeFs (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44484:14)
      at C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44720:14
PS C:\devika\devika\ui> bun run dev
$ vite dev
44277 |         sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath)
44278 |       );
44279 |     }
44280 |   };
44281 |   try {
44282 |     return fs$7.watch(path, options, handleEvent);
                   ^
EBUSY: EBUSY watching "C:/devika/devika/ui"
 syscall: "watch"
   path: "C:/devika/devika/ui"

      at new FSWatcher (node:fs:105:27)
      at watch2 (node:fs:284:199)
      at createFsWatchInstance (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44282:12)
      at setFsWatchListener (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44329:15)
      at _watchWithNodeFs (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44484:14)
      at C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44720:14
error: script "dev" exited with code 1
PS C:\devika\devika\ui>

**Comment by ARajgor** [comment]
> > > **Describe the bug** installation guide incomplete, simply not working. in Windows 11:
> > > PS C:\devika\devika\ui> bun run dev $ vite dev 44277 | sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath) 44278 | ); 44279 | } 44280 | }; 44281 | try { 44282 | return fs$7.watch(path, options, handleEvent); ^ EBUSY: EBUSY watching "C:/devika/devika/ui" syscall: "watch" path: "C:/devika/devika/ui"
> > > in Fedora Linux 39: playwritght install --with-deps just gives command not found...
> > > **To Reproduce** Steps to reproduce the behavior:
> > > 
> > > 1. system not been used for development, Windows 11 or Fedora Linux 39
> > > 2. Following the steps in the installation guide
> > > 
> > > **Expected behavior** the steps in the guide should work
> > > **Desktop (please complete the following information):** Windows 11 and Fedora Linux 39
> > > **Additional context** further more, there were alott more problems on my way to this point, that i had to find a solution to. Unmentioned in the installation guide. like for eksample, do i use the terminal, vscode or powershell. it is not self explaning. If when i run a particular line, and are forced to restart commandline, do i need to start from the beginning ?
> > > i highly suggest when write an installation guide. Use a fresh system without the hidden traces of a developer
> > 
> > 
> > frontend commands: `bun install` `bun -i vite` (if you are facing vite issue) `bun run dev`
> > backend:
> > 
> > * create virtual env
> > * activate it
> > * install requirements.txt
> > * run `python devika.py`
> > 
> > My systems:
> > ```
> > Windows 11
> > Node js - 20.9.0
> > python - 3.11
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > node version should be >= 16
> 
> PS C:\devika\devika\ui> bun install bun install v1.1.1 (ca1dbb4e) 🔒 Saving lockfile... error: failed to open lockfile: EBUSY PS C:\devika\devika\ui> bun -i vite 44277 | sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath) 44278 | ); 44279 | } 44280 | }; 44281 | try { 44282 | return fs$7.watch(path, options, handleEvent); ^ EBUSY: EBUSY watching "C:/devika/devika/ui" syscall: "watch" path: "C:/devika/devika/ui"
> 
> ```
>   at new FSWatcher (node:fs:105:27)
>   at watch2 (node:fs:284:199)
>   at createFsWatchInstance (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44282:12)
>   at setFsWatchListener (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44329:15)
>   at _watchWithNodeFs (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44484:14)
>   at C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44720:14
> ```
> 
> PS C:\devika\devika\ui> bun run dev $ vite dev 44277 | sysPath$2.resolve(path, evPath), KEY_LISTENERS, sysPath$2.join(path, evPath) 44278 | ); 44279 | } 44280 | }; 44281 | try { 44282 | return fs$7.watch(path, options, handleEvent); ^ EBUSY: EBUSY watching "C:/devika/devika/ui" syscall: "watch" path: "C:/devika/devika/ui"
> 
> ```
>   at new FSWatcher (node:fs:105:27)
>   at watch2 (node:fs:284:199)
>   at createFsWatchInstance (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44282:12)
>   at setFsWatchListener (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44329:15)
>   at _watchWithNodeFs (C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44484:14)
>   at C:\devika\devika\ui\node_modules\vite\dist\node\chunks\dep-B-u6xNiR.js:44720:14
> ```
> 
> error: script "dev" exited with code 1 PS C:\devika\devika\ui>

delete the bun lock file

**Comment by javacaliente** [comment]
Those install directions are way different than the read me.
The read me says nothing about node.js
I thought bun was in place of node.js.  Are you saying it's in addition to?

**Comment by xphraze1989** [comment]
> delete the bun lock file

i did that, same error.. Devika is open source, we decide what we want of this right?.. cant we decide it to be a desktop application ? a C++ framework with Python support ? cant we start a new GPL project ?

**Comment by ARajgor** [comment]
https://github.com/stitionai/devika/pull/387
