### ISSUE TITLE
playwright requires root access to install browsers with their dependencies

### ISSUE THREAD

**Issue by tchayintr** [stitionai/devika#379]
Hi, thank you for making Devika!

I'm trying to install Playwright dependencies using `playwright install --with-deps` , but it's requesting root access (`Switching to root user to install dependencies...`). 
Could you suggest ways to install these dependencies without root privileges?

**Comment by Polygons1** [comment]
playwright needs to install dependencies and it uses the built in package manager and that requires root access

**Comment by jmtatsch** [comment]
See pr #317

**Comment by ARajgor** [comment]
solved by #317
