### ISSUE TITLE
Fails to parse ollama model code output

### ISSUE THREAD

**Issue by dproworld** [stitionai/devika#380]
**Describe the bug**
Whenever I instruct Devika to program anything, the initial stages of the process go well, but once it gets to the programming part, the agent fails to parse the models output correctly: `Invalid response from the model, trying again...`

All other parts of the agent are functional, including web browser, searching, and search result parsing. 

**Desktop (please complete the following information):**
 - OS: WSL (Ubuntu 22.04) - Windows 11 Pro 
 - Browser: Firefox
 - Version:
```bash
commit edd99a7fd112173436f3b8e3bcdadb1e31a961eb (HEAD -> main, origin/main, origin/HEAD)
Author: ayush rajgor <76404080+ARajgor@users.noreply.github.com>
Date:   Fri Apr 5 00:24:21 2024 +0530

    Fix: setting page loading issue, messages from user (#359)

    * fix: HMR error

    * fix: second message from not showing/ remove:console.log

    resolved #359
```

**Additional context**
I've attached the [console log file](https://github.com/stitionai/devika/files/14892201/consolelog.txt) (a txt of console output) here. I can provide any additional logs.

**Comment by dproworld** [comment]
#347 and #307 are related, and this is likely a duplicate, although an important issue for local models.

**Comment by Ahmet0691** [comment]
what did u use to LLM model ?

**Comment by dproworld** [comment]
It is mentioned in the log file.

**Comment by ARajgor** [comment]
duplicate #347
