### ISSUE TITLE
Hello author, can I close huggingface for this project? I have my own api_key for OpenAI

### ISSUE THREAD

**Issue by yxl23** [stitionai/devika#381]
![image](https://github.com/stitionai/devika/assets/115678682/9de95730-4dac-4f43-8952-c3086bc492e2)
![image](https://github.com/stitionai/devika/assets/115678682/8cfefbd2-ec75-4b36-920e-cc423fd1a579)

**Comment by ARajgor** [comment]
`SentenceBert(sentence).extract_keywords()` is required for internal function to devika work perfectly. That's why it connecting to huggingface for downloading model
