### ISSUE TITLE
No response from devika gave apis like gemini and gpt but still no response

### ISSUE THREAD

**Issue by PURUSHOTHAMREDDYKOTA** [stitionai/devika#390]
24.04.07 23:14:37: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'create python snake game', 'timestamp': '2024-04-07 23:14:37'}}

iam getting this log message.

**Comment by obliviousz** [comment]
Does this happen even after re-running devika.py?

**Comment by PxlNote** [comment]
Same Problem here.
Its getting stuck at this everytime

**Comment by arunwallex** [comment]
Same problem here. Any solutions to this?

**Comment by JamesD-git** [comment]
I'm also having this issue using ollama models on MacOS

**Comment by ARajgor** [comment]
fixed. fetch the latest changes. for more read the changelog in discord.
