### ISSUE TITLE
Not working with LLM

### ISSUE THREAD

**Issue by stan1233** [stitionai/devika#396]
**Describe the bug**
I've tested the "Implement Conway's Game of Life in Python using Pygame", but I always encounter "Invalid response from the model, trying again..."

I've attempted using llama2:70b and qwen:72b - both yielded identical outcomes.

</body>
</html>

**Additional context**
![image](https://github.com/stitionai/devika/assets/20401741/ae00e649-1afd-4fd3-b571-0d1936843e37)
![image](https://github.com/stitionai/devika/assets/20401741/dc9d9c3f-5ecd-418d-ad7f-fb9b8d7ee797)

**Comment by obliviousz** [comment]
What I feel is it's llama2's inability to follow the prompt and give the correct format response. Try with another LLM, like Claude3 (for which you get free 5$ initially) or Gemini till May is free i guess

**Comment by brPreetham** [comment]
I can reproduce this issue. Looks like the LLM's response is not in the intended format.

**Comment by brPreetham** [comment]
I have submitted a pull request for a modification that I believe will improve on the issue. 
The Llama2 model is not providing the responses in the expect format. 
``` JSON { ...... }```
Instead it includes additional explanation/justification sections in some of its responses. Causing the JSON validation to fail
Llama2 output: ```JSON{...} explanation: ....```

This can be somewhat corrected by modifying the prompt to explicitly inform the model to adhere to the output format requested. 
Please have a look at the prompt.jinja file modification here: https://github.com/stitionai/devika/commit/ea4076945f458b2ba492d5beba576b87c21747d1
Check and confirm  if the suggested modification helps.

**Comment by hqnicolas** [comment]
@stan1233  are you in ollama?

Use:
command-r:35b-v0.1-q4_K_M
openchat:7b-v3.5-1210-q5_K_M
mistral-openorca:7b-q6_K

Latest Devika Version was Working with Ollama,
I have Freezed it on my Repo:
git push https://github.com/hqnicolas/devika
cd devika
create config file
edit the docker compose to ollama url
sudo docker compose build
sudo docker compose up

**Comment by start-life** [comment]
This is exactly my problem

**Comment by daniel-luper** [comment]
> I have submitted a pull request for a modification that I believe will improve on the issue. The Llama2 model is not providing the responses in the expect format. ` JSON { ...... }` Instead it includes additional explanation/justification sections in some of its responses. Causing the JSON validation to fail Llama2 output: `JSON{...} explanation: ....`
> 
> This can be somewhat corrected by modifying the prompt to explicitly inform the model to adhere to the output format requested. Please have a look at the prompt.jinja file modification here: [ea40769](https://github.com/stitionai/devika/commit/ea4076945f458b2ba492d5beba576b87c21747d1) Check and confirm if the suggested modification helps.

@brPreetham How can you see the raw Ollama output?

I'm new to the project and would like to know where to look to debug exactly what my model is formatting incorrectly.

**Comment by hjamet** [comment]
I am currently working on the problem [here](https://github.com/stitionai/devika/pull/469) :)

**Comment by ARajgor** [comment]
fixed. fetch the latest changes. for more read the changelog in discord.

**Comment by iChristGit** [comment]
> fixed. fetch the latest changes. for more read the changelog in discord.

I still face this issue with llama3-8B-Instruct-Q_8
