### ISSUE TITLE
Playwright

### ISSUE THREAD

**Issue by sravan792** [stitionai/devika#399]
**Describe the bug**
playwright._impl._errors.Error: Protocol error (Page.navigate): Cannot navigate to invalid URL

**Comment by PlanetMacro** [comment]
Also does not support Debian. https://github.com/microsoft/playwright/issues/8361 

So maybe switch to something that is not coming from microsoft?

**Comment by kindgracekind** [comment]
I'm also getting this error on Mac OS Sonoma 14.3.1

**Comment by ARajgor** [comment]
solved the link issue. solved it. fetch the latest changes.
