### ISSUE TITLE
Implement the Logs page in the Svelte Web UI

### ISSUE THREAD

**Issue by mufeedvh** [stitionai/devika#4]
In the main UI, the Logs page is not implemented yet. Here's how to implement it:

### Get Real-time Logs

**Endpoint:** `/api/real-time-logs`
**Method:** GET

Poll this endpoint in the main event loop.

## UI

Render the logs inside a code block with syntax highlighting for log files.

**Comment by dsfx3d** [comment]
Hi, I'm interested in contributing to this issue if it's not already taken.
