### ISSUE TITLE
Devika server not running due to gevent module not being found even though it is installed

### ISSUE THREAD

**Issue by mansmako** [stitionai/devika#402]
File "C:\WINDOWS\system32\devika\devika.py", line 7, in <module>
    from gevent import monkey
ModuleNotFoundError: No module named 'gevent'

**To Reproduce**
1. Go to ' cd devika'
2. Click on ' python devika.py'
3. See error

If I skip this stage in the installation instructions I get a crash
PS C:\WINDOWS\system32\devika> cd ui/
>> bun install
>> bun run dev
bun install v1.1.3 (2615dc74)
  📦 Installing [202/208]
uh-oh: index out of bounds
bun will crash now 😭😭😭

**Comment by nalaso** [comment]
To solve frontend issue.
1. Delete both nodemodules and bun.lockb
2. Do bun install in UI 
3. Now run bun run dev.
4. Open localhost3000
5. If it's white screen restart bun run dev

To solve backend issue.
1. Create a virtual environment 
2. The do pip install -r requirements.txt

It will install gevent

**Comment by markolia** [comment]
it dont work.. backend alway grevent issue at least for me..

**Comment by manuhelpiz** [comment]
It happened to me as well and it was because I forgot to run "uv pip install -r requirements.txt" before python3 devikya.py...
