### ISSUE TITLE
OFF TOPIC: who got access to real devin?

### ISSUE THREAD

**Issue by Mike-FreeAI** [stitionai/devika#406]
not me 
<img width="140" alt="image" src="https://github.com/stitionai/devika/assets/145850829/7f60c558-acb2-4ba9-9553-520f3e21e375">

**Comment by NathanielAH** [comment]
I wish!
I really wish Devika could be hosted like Devin. I can't build these programs at work where I really need them (extreme security).

**Comment by Mike-FreeAI** [comment]
ok
