### ISSUE TITLE
Can't create a project!

### ISSUE THREAD

**Issue by NAME0x0** [stitionai/devika#409]
I am trying to create a new Project but it's not working. I can't choose a Search Engine nor Language Model. The UI is present and is interactable but is not functional. Due to my inexperience with GitHub I posted my problem in another issue. I apologize for that. I will paste the link to the exact issue where I posted the pictures and the problems in detail so as to save time for everyone. I have tried 3 different ways of installation. Installation always works but the UI is not functional despite being interactive. 

The issue where I posted the problem:
[https://github.com/stitionai/devika/issues/155](url)  #155 

Please tell me what I am doing wrong if you can or if you need any extra details do let me know and I will provide them earnestly. There is no visible issue with the backend or the frontend so I am confused where the problem really is.

Thank you for your time.

**Comment by obliviousz** [comment]
Have you installed node js? It is probably due to that.

**Comment by NAME0x0** [comment]
I did. I even updated it to the most recent version including npm.

**Comment by beetlezap** [comment]
I am running devika in docker on Raspberry PI (building it locally) and have the same problem. UI is non-responsive without any errors in log.

**Comment by MKPTechnicals** [comment]
I faced the same problem. But have you started backend server. If yes, try to restart it.

**Comment by beetlezap** [comment]
Yes, and yes ;) I have tried different configuration options and restarted the back-end service repeatedly.

**Comment by MKPTechnicals** [comment]
Can you please send screenshots of backend server log and ui screenshot.

**Comment by NAME0x0** [comment]
I found the issue. I did a clean reinstall of nodejs. However, the problem wasn't with nodejs. It was with the command to run the backend. Instead of writing `bun run dev`, you have to type `bun run dev --host` and that got it running with no problem.

**Comment by NAME0x0** [comment]
I am not sure whether to type that every single time from now on but it definitely got it running. Let me run Devika again without `bun run dev --host` this time and I will give an update.

**Comment by NAME0x0** [comment]
There seems to be a problem with just running `bun run dev` which leads to the UI not being functional for some reason. However, running `bun run dev --host` seems to fix it. Furthermore, the network link should be used to interact with Devika, not the local one, which is very odd.

**Comment by NAME0x0** [comment]
Run `bun run dev --host` and choose the network link instead of the local one. That should resolve the issue for anyone else facing the same issue.

**Comment by NAME0x0** [comment]
ahh makes sense. However, I am running it as admin as well on powershell. Strange that normal one doesn't seem to work for me.

**Comment by beetlezap** [comment]
Screenshot:
<img width="1667" alt="image" src="https://github.com/stitionai/devika/assets/17266818/7d54dd6b-f032-4c22-8518-4ff18d20680f">

Log from docker:
```
ollama-service-1         | time=2024-04-11T14:55:27.613Z level=INFO source=images.go:806 msg="total blobs: 5"
ollama-service-1         | time=2024-04-11T14:55:27.614Z level=INFO source=images.go:813 msg="total unused blobs removed: 0"
ollama-service-1         | time=2024-04-11T14:55:27.614Z level=INFO source=routes.go:1110 msg="Listening on [::]:11434 (version 0.1.29)"
ollama-service-1         | time=2024-04-11T14:55:27.615Z level=INFO source=payload_common.go:112 msg="Extracting dynamic libraries to /tmp/ollama800548662/runners ..."
devika-frontend-app-1    | $ vite dev --host
devika-backend-engine-1  | 24.04.11 14:55:28: root: INFO   : Initializing Devika...
devika-backend-engine-1  | 24.04.11 14:55:28: root: INFO   : Initializing Prerequisites Jobs...
devika-frontend-app-1    | 
devika-frontend-app-1    |   VITE v5.2.8  ready in 1207 ms
devika-frontend-app-1    | 
devika-frontend-app-1    |   ➜  Local:   http://localhost:3000/
devika-frontend-app-1    |   ➜  Network: http://172.19.0.4:3000/
ollama-service-1         | time=2024-04-11T14:55:31.961Z level=INFO source=payload_common.go:139 msg="Dynamic LLM libraries [cpu cuda_v11]"
ollama-service-1         | time=2024-04-11T14:55:31.961Z level=INFO source=gpu.go:77 msg="Detecting GPU type"
ollama-service-1         | time=2024-04-11T14:55:31.961Z level=INFO source=gpu.go:191 msg="Searching for GPU management library libnvidia-ml.so"
ollama-service-1         | time=2024-04-11T14:55:31.961Z level=INFO source=gpu.go:237 msg="Discovered GPU libraries: []"
ollama-service-1         | time=2024-04-11T14:55:31.961Z level=INFO source=cpu_common.go:18 msg="CPU does not have vector extensions"
ollama-service-1         | time=2024-04-11T14:55:31.961Z level=INFO source=routes.go:1133 msg="no GPU detected"
devika-backend-engine-1  | 24.04.11 14:55:36: root: INFO   : Loading sentence-transformer BERT models...
devika-backend-engine-1  | 24.04.11 14:55:42: root: INFO   : BERT model loaded successfully.
devika-backend-engine-1  | 24.04.11 14:55:45: root: WARNING: Ollama not available
devika-backend-engine-1  | 24.04.11 14:55:45: root: WARNING: run ollama server to use ollama models otherwise use other models
devika-backend-engine-1  | 24.04.11 14:55:47: root: INFO   : Devika is up and running!

```

I suspect this has impact but uncertain to fix:
```
devika-frontend-app-1    |   ➜  Local:   http://localhost:3000/
devika-frontend-app-1    |   ➜  Network: http://172.19.0.4:3000/
```

**Comment by MKPTechnicals** [comment]
Ohh you're using ollama. I'm using gemini.

**Comment by beetlezap** [comment]
I am not using anything since I cannot choose that from the UI ;)

**Comment by spcmediaco** [comment]
> bun run dev --host

Thank you, that worked for me too!
