### ISSUE TITLE
Sweet Laravel love ❤️ for Devika

### ISSUE THREAD

**Issue by aldoyh** [stitionai/devika#414]
Hey Devika team,

I'm digging what you've built with Devika AI – it's seriously cool stuff! Been playing around with it, and honestly, I feel like it could be the ultimate Laravel dev sidekick if it had a little more framework awareness.

> Why Laravel + PHP = Awesome for Devika

Devs Like Us: Laravel is HUGE. Like, so many of us build with it every day. Imagine Devika understanding our projects and spitting out sweet Laravel-flavored code snippets. That's game-changing productivity right there.
PHP Power: Don't forget, PHP is still what makes a big chunk of the web tick. Devika rocking solid PHP skills would make it a go-to tool for way more devs.

### Obviously, this isn't a two-minute fix, but here are some thoughts:

- Laravel Brain Transplant: Teach Devika all the ins and outs of Laravel – routes, controllers, you name it. Suddenly, it gets what we're building.

- API BFFs: Hook Devika up with Laravel's docs. Imagine it generating sweet code examples using the framework's tools.

- Pattern Spotter: Train Devika to pick up on how we write Laravel code for super-smart suggestions.

**Wanna team up?**

I'm no AI trainer guru, but I know Laravel inside out. Happy to be a guinea pig, give feedback, or even help with some Laravel-y tutorials for Devika.  Let's make this AI a must-have for PHP devs!

Thanks in advance.

![Alchemy Magic Image (5)](https://github.com/stitionai/devika/assets/5215449/2023158c-85ec-421d-afa6-1eb0d4696373)
![Alchemy Magic Image (6)](https://github.com/stitionai/devika/assets/5215449/dde959a9-208f-4bd1-832d-88ab7552fa33)
![Alchemy Magic Image (7)](https://github.com/stitionai/devika/assets/5215449/50ebd288-645b-418c-bcc4-7b3d24493486)

`The unrelated attached photos prompt: Devika, a masterfully crafted humanoid AI, exudes an aura of sleek modernity intertwined with a hint of enigmatic intrigue. Her cybernetic features gleam with metallic precision, while her intricately designed neural circuits hum with energy. This stunning portrait captures Devika's dynamic essence, blending cutting-edge technology with a touch of captivating mystery. The vivid colors and intricate details of the image emphasize the sheer brilliance of this artificial intelligence creation.`

**Comment by titonova** [comment]
Neat. Seems like the kind of thing that should be developed as an external plugin though. Wont make much sense to build it into devika itself, and this is coming from a laravel dev

**Comment by aldoyh** [comment]
Thanks for your reply, of course it's unnecessary.. But for now all my tries to request any PHP task or Laravel starts to hallucinate into python. so that what I noticed from `coder/prompt.jinja2` or something similar for PHP?
