### ISSUE TITLE
the front is here i can choose the model the search engine select a project but the agent doesnt respond to my prompt

### ISSUE THREAD

**Issue by SpringBootReactTypescriptTailwindMaster** [stitionai/devika#417]
![321161691-51af1c5c-1ab3-4e77-9bdb-b73bdb1b03e9](https://github.com/stitionai/devika/assets/154255969/f0c5acfe-e0fd-42d8-967a-96099a514d08)

**Comment by obliviousz** [comment]
It'd help if you show the logs rather than the API keys. I'd also suggest to remove the API keys as you have shown the OpenAI API key and this is an open platform with literally anyone who can see your keys. Thanks

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
Yes my bad for the keys i forgot that it's forbidden to show them i deleted the image

![image](https://github.com/stitionai/devika/assets/154255969/9b5f8c3f-e351-45be-a5b4-301ab37d5011)

This is the bottom of the logs the last thing that i did in the front is adding the prompt " Hi create me a Website in JS in which the main page show 3 differents type of coffee " 

![image](https://github.com/stitionai/devika/assets/154255969/ac5cfc6f-16d0-4767-ad24-c9de7540f5ac)

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
Honestly i dont know, it seems like the logs are not showing something when i type the prompt i dont have the same logs that i see in a video of someone installing and using Devika. It's buggy sometimes i cannot type another prompt because it's written " agent is busy " i need to wait or to reload the page, i can show you a video of the manipulation but unfortunately the format is not working in github

**Comment by ARajgor** [comment]
can you run it again and share the python log like check if there is any error in terminal?

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
I cannot even run it again i do "python devika.py" and "bun run dev"

![image](https://github.com/stitionai/devika/assets/154255969/9c3525e3-b5d0-440a-aca5-3a53d3c9d755)

![image](https://github.com/stitionai/devika/assets/154255969/a4babdf3-398c-4ac8-8485-46b0d2deb350)

**Comment by ARajgor** [comment]
node version?

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
it was the node 16 version because i used it for Angular 15 i putted again node 20 the front is showing back again, but now i cannot create projects, choose models and all others stuff

**Comment by ARajgor** [comment]
have you started the python backend?

**Comment by prathamshaw22** [comment]
👍

Pratham reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
like you can see on the previous screenshot i started devika.py and bun run dev

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
I really dont understand what is going on 

![image](https://github.com/stitionai/devika/assets/154255969/a95d4927-cf3d-435c-aa9e-87c59257f5b3)

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
Yes i did 

![image](https://github.com/stitionai/devika/assets/154255969/5a45d84f-85f2-46fa-9739-fe3c8b354583)

![image](https://github.com/stitionai/devika/assets/154255969/7d6f38a5-b09c-4f08-ae8a-b4ba8d9a9453)

_

I just putted API KEYS for google_search google_search_engine_id openai Appearance Dark created 2 projects selected it both tried a prompt like " create me a website in JS " with Google and GPT-3.5 

![image](https://github.com/stitionai/devika/assets/154255969/e6a72347-e051-4f31-af66-8da82368b1aa)

![image](https://github.com/stitionai/devika/assets/154255969/087023b1-a4d0-49be-b9d0-abf449fd33db)

![image](https://github.com/stitionai/devika/assets/154255969/8970c44e-5cc2-4f78-9aff-d1b10db441ce)

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
![image](https://github.com/stitionai/devika/assets/154255969/e6e52a4d-9b7a-4eba-801f-53f1826c1adf)

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
Do you think it's possible to have Devika for the next week ?

**Comment by prathamshaw22** [comment]
Ya! It's possible to create AI like devika it's absolutely respond to each other's

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
I mean i dont wanna create a Saas like devika i just wanna use it because i will start to work monday and i really wanna ensure my employability idk if someone of your team can help me to fix this but it could be really enjoyable

**Comment by ARajgor** [comment]
@SpringBootReactTypescriptTailwindMaster your API keys are visibles

**Comment by SpringBootReactTypescriptTailwindMaster** [comment]
OS : Windows 10
Python 3.12.2
Node v20.9.0
Bun v1.1.3
search engine : Google 
Model : gpt 3.5

**Comment by ARajgor** [comment]
fixed. fetch the latest changes. for more read the changelog in discord.
