### ISSUE TITLE
as installed devika repository and installed all requirement but still devika is not responding to 

### ISSUE THREAD

**Issue by Mlbadboy** [stitionai/devika#424]
**Describe the bug**

no response from devika even after giving all api and the terminal is showing waitng

**Comment by MKPTechnicals** [comment]
Can you check what server log says?

**Comment by arsaboo** [comment]
Seeing the same....here are the logs:
```
24.04.11 10:28:56: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'sdafd', 'timestamp': '2024-04-11 10:28:56'}}
24.04.11 10:28:57: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'asdfasdf', 'timestamp': '2024-04-11 10:28:57'}}
24.04.11 10:28:58: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'asdf', 'timestamp': '2024-04-11 10:28:58'}}
24.04.11 10:28:58: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'asdf', 'timestamp': '2024-04-11 10:28:58'}}
```

Basically, there is no response to any message

**Comment by MKPTechnicals** [comment]
Can you provide with complete logs from starting server or screenshot of the same?

**Comment by MKPTechnicals** [comment]
I'm asking for the messages displayed in server cmd.

**Comment by arsaboo** [comment]
There is not much besides these:
```bash
24.04.11 10:27:18: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'hello', 'timestamp': '2024-04-11 10:27:18'}}
24.04.11 10:28:16: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'create a calculator app', 'timestamp': '2024-04-11 10:28:16'}}
24.04.11 10:28:28: root: INFO   : /api/settings GET
24.04.11 10:28:28: root: DEBUG  : /api/settings GET - Response: {"settings":{"API_ENDPOINTS":{"BING":"https://api.bing.microsoft.com/v7.0/search","OLLAMA":"http://192.168.2.162:11434"},"API_KEYS":{"BING":"REDACTED","OPENAI":"REDACTED"},"LOGGING":{"LOG_PROMPTS":"false","LOG_REST_API":"true"},"STORAGE":{"LOGS_DIR":"data/logs","PDFS_DIR":"data/pdfs","PROJECTS_DIR":"data/projects","REPOS_DIR":"data/repos","SCREENSHOTS_DIR":"data/screenshots","SQLITE_DB":"data/db/devika.db"}}}

Socket connected ::  {'data': 'frontend connected!'}
24.04.11 10:28:41: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.04.11 10:28:41: root: INFO   : /api/data GET
24.04.11 10:28:41: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2 70B","llama2-70b-4096"],["GROQ GEMMA 7B IT","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[["codebooga","codebooga:latest"],["codellama","codellama:latest"],["command-r","command-r:35b"],["deepseek-coder","deepseek-coder:33b"],["dolphin-mixtral","dolphin-mixtral:latest"],["gemma","gemma:latest"],["llama2","llama2:70b"],["llama2","llama2:latest"],["llama2-uncensored","llama2-uncensored:latest"],["llava","llava:latest"],["mxbai-embed-large","mxbai-embed-large:latest"],["nomic-embed-text","nomic-embed-text:latest"],["nous-hermes2","nous-hermes2:latest"],["qwen","qwen:32b"],["qwen","qwen:72b"],["starling-lm","starling-lm:latest"]],"OPENAI":[["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]},"projects":["temp"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.04.11 10:28:41: root: INFO   : /api/get-agent-state POST
24.04.11 10:28:41: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-11 10:26:55","token_usage":363}}

24.04.11 10:28:56: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'sdafd', 'timestamp': '2024-04-11 10:28:56'}}
24.04.11 10:28:57: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'asdfasdf', 'timestamp': '2024-04-11 10:28:57'}}
24.04.11 10:28:58: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'asdf', 'timestamp': '2024-04-11 10:28:58'}}
24.04.11 10:28:58: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'asdf', 'timestamp': '2024-04-11 10:28:58'}}
```

**Comment by MKPTechnicals** [comment]
Try using bun run dev --host

**Comment by MKPTechnicals** [comment]
Refer to:

https://github.com/stitionai/devika/issues/409

**Comment by arsaboo** [comment]
It now works on other computers on the network, but still the same behavior (no response; but no errors in the logs):
```
24.04.11 17:36:38: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-11 10:26:55","token_usage":363}}

24.04.11 17:36:47: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'Hi', 'timestamp': '2024-04-11 17:36:47'}}
24.04.11 17:37:02: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'hello', 'timestamp': '2024-04-11 17:37:02'}}

```

**Comment by volleytech8** [comment]
everything is working but the terminal is stuck on waiting
here are my logs:
24.04.12 04:01:00: root: INFO   : Initializing Devika...
24.04.12 04:01:00: root: INFO   : Initializing Prerequisites Jobs...
24.04.12 04:01:04: root: INFO   : Loading sentence-transformer BERT models...
24.04.12 04:01:11: root: INFO   : BERT model loaded successfully.
24.04.12 04:01:13: root: INFO   : Ollama available
24.04.12 04:01:14: root: INFO   : Devika is up and running!
24.04.12 04:01:26: root: INFO   : /api/data GET
24.04.12 04:01:26: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2 70B","llama2-70b-4096"],["GROQ GEMMA 7B IT","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[],"OPENAI":[["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]},"projects":["project"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.04.12 04:01:27: root: INFO   : /api/get-agent-state POST
24.04.12 04:01:27: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

Socket connected ::  {'data': 'frontend connected!'}
24.04.12 04:01:27: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.04.12 04:01:29: root: INFO   : /api/get-agent-state POST
24.04.12 04:01:29: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-12 03:57:23","token_usage":364}}

24.04.12 04:03:01: root: INFO   : /api/data GET
24.04.12 04:03:01: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2 70B","llama2-70b-4096"],["GROQ GEMMA 7B IT","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[],"OPENAI":[["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]},"projects":["project"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.04.12 04:03:01: root: INFO   : /api/get-agent-state POST
24.04.12 04:03:01: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

Socket connected ::  {'data': 'frontend connected!'}
24.04.12 04:03:01: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.04.12 04:03:04: root: INFO   : /api/get-agent-state POST
24.04.12 04:03:04: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-12 03:57:23","token_usage":364}}

24.04.12 04:03:11: root: INFO   : /api/data GET
24.04.12 04:03:11: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2 70B","llama2-70b-4096"],["GROQ GEMMA 7B IT","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[],"OPENAI":[["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]},"projects":["project"],"search_engines":["Bing","Google","DuckDuckGo"]}

Socket connected ::  {'data': 'frontend connected!'}
24.04.12 04:03:11: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.04.12 04:03:11: root: INFO   : /api/get-agent-state POST
24.04.12 04:03:11: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

24.04.12 04:05:02: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'python snake game', 'timestamp': '2024-04-12 04:05:02'}}

**Comment by volleytech8** [comment]
when i try to bun install, it says:
error: moving "tiktoken" to cache dir failed
EPERM: Operation not permitted (NtSetInformationFile())

**Comment by ARajgor** [comment]
you have to wait for some time while LLM generates the output for you. before that, you are sending messaging per second. Also which model are you using.

**Comment by arsaboo** [comment]
None of the models are working for me.

**Comment by ARajgor** [comment]
fixed. fetch the latest changes. for more read the changelog in discord.
