### ISSUE TITLE
Integration of Azure OpenAI

### ISSUE THREAD

**Issue by JLJuradoDeloitte** [stitionai/devika#425]
**Is your feature request related to a problem? Please describe.**
Currently, developers utilizing Azure OpenAI and GitHub's Devikas repository face a disjointed workflow when integrating AI capabilities into their projects. They need to switch between platforms, leading to inefficiencies and potential integration challenges.

**Describe the solution you'd like**
I propose a seamless integration between Azure OpenAI and GitHub's Devikas repository, allowing developers to access OpenAI's models, APIs, and tools directly within the GitHub interface. This integration would streamline the development process and enhance collaboration by enabling real-time model training, version control for AI models, and integration with GitHub's pull request workflow.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ARajgor** [comment]
duplicate #55
