### ISSUE TITLE
 Plan doesn't shows up because of incorrect formatting of the response from Gemini , GPT ...

### ISSUE THREAD

**Issue by Abdullahsaleh203** [stitionai/devika#429]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by obliviousz** [comment]
Hey, I fixed this by adding an example to the prompt.

https://github.com/stitionai/devika/pull/438

Want some reviewers to review the changes.
Thanks
