### ISSUE TITLE
Add account-feature / password protection

### ISSUE THREAD

**Issue by Pils10** [stitionai/devika#434]
**Is your feature request related to a problem? Please describe.**
I want to host Devika on a publicly exposed remote docker server, but this would leak my API keys.

**Describe the solution you'd like**
Either a simple enter password page like VSCode-Server or an account system with would allow different users to use the tool, each one with their custom settings.

**Describe alternatives you've considered**
Whilst only exposing it through a proxy does work, it is inconvenient and requires technical knowledge. I think many people will run the tool with the default configuration and, therefore, might expose their API-keys. The password could simply be added to the "config.toml" file and be required to access the site.

**Comment by ARajgor** [comment]
not planned currently
