### ISSUE TITLE
Need clear documentation, it's not suitable for everyone

### ISSUE THREAD

**Issue by parthamk** [stitionai/devika#441]
### Documentation is not clear 
Previously the documentation had clear instruction of how to run it with the clear cut instruction of how to install packages and software needed now following the same documentation it's impossible to run the application.

### How To Reproduce
Steps to reproduce the behavior (example):
1. Provide details instructions of software need to install
2. Clean and clear instructions on install and run the application

***Please check the documentation properly before merging***

**Comment by ARajgor** [comment]
The installation guide is the same as the previous one. no changes.

**Comment by ARajgor** [comment]
I make some changes. let me if it's better or not.

**Comment by PlanetMacro** [comment]
On thing that should be mentioned is how to use the --host parameter for remote access via browser. If I'm not mistaken, it it not mentioned currently.

**Comment by parthamk** [comment]
Now the problem is solved. Missed couple of instruction because of the incomplete instructions. Thank you.
