### ISSUE TITLE
can access UI but nothing happens when I prompt it

### ISSUE THREAD

**Issue by abhatia-kdoa** [stitionai/devika#445]
Installed it, it is up and running
Added google search API and Openai API 

Selected google as my search enginer and gpt-4

<img width="1325" alt="Screenshot 2024-04-16 at 2 10 32 PM" src="https://github.com/stitionai/devika/assets/159954982/4f7eb21c-84ac-48c0-b46a-b76f01006534">

Just shows echo waiting all the time

Log below

24.04.16 14:10:24: root: DEBUG : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-16 14:00:30","token_usage":372}}

24.04.16 14:10:24: root: INFO : /api/get-agent-state POST

24.04.16 14:10:24: root: DEBUG : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2 70B","llama2-70b-4096"],["GROQ GEMMA 7B IT","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[],"OPENAI":[["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]},"projects":["2fa"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.04.16 14:10:24: root: INFO : /api/data GET

24.04.16 14:00:10: root: DEBUG : /api/get-agent-state POST - Response: {"state":null}

24.04.16 14:00:10: root: INFO : /api/get-agent-state POST

24.04.16 14:00:07: root: DEBUG : /api/get-agent-state POST - Response: {"state":null}

24.04.16 14:00:07: root: INFO : /api/get-agent-state POST

24.04.16 14:00:07: root: DEBUG : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2 70B","llama2-70b-4096"],["GROQ GEMMA 7B IT","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[],"OPENAI":[["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]},"projects":["2fa"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.04.16 14:00:07: root: INFO : /api/data GET

24.04.16 13:59:31: root: DEBUG : /api/get-agent-state POST - Response: {"state":null}

24.04.16 13:59:31: root: INFO : /api/get-agent-state POST

24.04.16 13:59:31: root: DEBUG : /api/create-project POST - Response: {"message":"Project created"}

**Comment by kingler** [comment]
I am experiencing the same issue. I reinstalled several times with no success.

**Comment by flight505** [comment]
same

**Comment by flight505** [comment]
Think there were some updates that use sveltejs, try to update your bun: 
curl -fsSL https://bun.sh/install | bash
and you might also update node to latest 2.0.1:
brew install node
I was @ node 2.0. but it should not hurt,  at least it resolved the issue and started running

**Comment by zahid313** [comment]
doing` npm install -g bun@latest` solved it for me.

**Comment by sritam2** [comment]
I have the same issue. The server is not responding to the requests from the client.

> 24.04.24 02:59:56: root: INFO   : /api/data GET
24.04.24 02:59:56: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["GROQ Mixtral","mixtral-8x7b-32768"],["GROQ LLAMA2 70B","llama2-70b-4096"],["GROQ GEMMA 7B IT","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[],"OPENAI":[["GPT-4 Turbo","gpt-4-0125-preview"],["GPT-3.5","gpt-3.5-turbo-0125"]]},"projects":["helloWorld1"],"search_engines":["Bing","Google","DuckDuckGo"]}

Socket connected ::  {'data': 'frontend connected!'}
24.04.24 02:59:56: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.04.24 02:59:56: root: INFO   : /api/get-agent-state POST
24.04.24 02:59:56: root: DEBUG  : /api/get-agent-state POST - Response: {"state":null}

24.04.24 03:00:00: root: INFO   : /api/get-agent-state POST
24.04.24 03:00:00: root: DEBUG  : /api/get-agent-state POST - Response: {"state":{"agent_is_active":true,"browser_session":{"screenshot":null,"url":null},"completed":false,"internal_monologue":null,"message":null,"step":null,"terminal_session":{"command":null,"output":null,"title":null},"timestamp":"2024-04-24 02:53:00","token_usage":363}}

24.04.24 03:00:30: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'why are you nit resonding?', 'timestamp': '2024-04-24 03:00:30'}}

![image](https://github.com/stitionai/devika/assets/16870405/cdbc993f-9d2c-47ac-afcb-88aeceb0124b)

**Comment by sritam2** [comment]
No response at all from AI agent devika

**Comment by MnMs-Mojo** [comment]
Same here. Seems like the browsing nor the terminal component ever gets into a "connected" state. See screenshot from abhatia-kdoa: aren't these lights supposed to show up in color instead of just remaining grayed out? Just thinking out loud here ...

**Comment by ARajgor** [comment]
fixed. fetch the latest changes. for more read the changelog in discord.
