### ISSUE TITLE
ValueError: The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked.

### ISSUE THREAD

**Issue by MKPTechnicals** [stitionai/devika#454]
### Describe the bug 
Many times it searches web for anything it ends up with this error. I just gave task displayed in demo to create game of life in python using pygame. Sometimes when I create new project and run same commands it runs successfully.

Used Gemini and DuckDuckGo search engine

### Expected behavior
It should give following error.

### Screenshots and logs
Exception in thread Thread-3 (<lambda>):
Traceback (most recent call last):
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\HOME\Desktop\devika\devika.py", line 94, in <lambda>
    thread = Thread(target=lambda: agent.execute(message, project_name))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HOME\Desktop\devika\src\agents\agent.py", line 346, in execute
    search_results = self.search_queries(queries, project_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HOME\Desktop\devika\src\agents\agent.py", line 112, in search_queries
    results[query] = self.formatter.execute(data, project_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HOME\Desktop\devika\src\agents\formatter\formatter.py", line 21, in execute
    response = self.llm.inference(raw_text, project_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HOME\Desktop\devika\src\llm\llm.py", line 96, in inference
    response = model.inference(self.model_id, prompt).strip()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HOME\Desktop\devika\src\llm\gemini_client.py", line 14, in inference
    return response.text
           ^^^^^^^^^^^^^
  File "C:\Users\HOME\AppData\Local\Programs\Python\Python311\Lib\site-packages\google\generativeai\types\generation_types.py", line 347, in text
    raise ValueError(
ValueError: The `response.text` quick accessor only works when the response contains a valid `Part`, but none was returned. Check the `candidate.safety_ratings` to see if the response was blocked.

### Configuration
```
- OS: Windows
- Python version: 3.11
- search engine: DuckDuckGo
- Model: Gemini
```

**Comment by MKPTechnicals** [comment]
And can devika execute code it has generated??

**Comment by ARajgor** [comment]
it's Gemini problem

**Comment by ARajgor** [comment]
solved it. fetch the latest changes.

**Comment by MKPTechnicals** [comment]
Can you please let me know if devika can execute code by itself or not?

**Comment by mkdemkov** [comment]
> solved it. fetch the latest changes.

hello. As i understood you use gemini and u said that you've fixed this issue with response.text error. Can you please say how? You did something like hardcode ?

**Comment by ARajgor** [comment]
> > solved it. fetch the latest changes.
> 
> hello. As i understood you use gemini and u said that you've fixed this issue with response.text error. Can you please say how? You did something like hardcode ?

not hard coded but handle it properly. check on gemini_client.py

**Comment by mkdemkov** [comment]
> > > solved it. fetch the latest changes.
> > 
> > 
> > hello. As i understood you use gemini and u said that you've fixed this issue with response.text error. Can you please say how? You did something like hardcode ?
> 
> not hard coded but handle it properly. check on gemini_client.py

yes, I've seen that. However, sometimes there is no even a candidate so the line `print("Finish reason:", response.candidates[0].finish_reason)` causes an error. Hope google'll fix that asap
