### ISSUE TITLE
Error in Devika installation

### ISSUE THREAD

**Issue by 20481A5450** [stitionai/devika#455]
### the bug 
I was trying to install devika on my local machine after the installation of th requirements while i was running the main file which is **devika.py** shown me an error 

###Error
Traceback (most recent call last):
  File "C:\Users\shaik\devika\devika.py", line 24, in <module>
    from src.agents import Agent
  File "C:\Users\shaik\devika\src\agents\__init__.py", line 1, in <module>
    from .agent import Agent
  File "C:\Users\shaik\devika\src\agents\agent.py", line 2, in <module>
    from .researcher import Researcher
  File "C:\Users\shaik\devika\src\agents\researcher\__init__.py", line 1, in <module>
    from .researcher import Researcher
  File "C:\Users\shaik\devika\src\agents\researcher\researcher.py", line 12, in <module>
    class Researcher:
  File "C:\Users\shaik\devika\src\agents\researcher\researcher.py", line 25, in Researcher
    def validate_response(self, response: str) -> dict | bool:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### Screenshots and logs
![Screenshot 2024-04-17 190532](https://github.com/stitionai/devika/assets/99806742/cb38ecf4-5abd-4068-9b3a-a26205ebee7c)

### Configuration
```
- OS: [e.g. Windows, Linux, MacOS]
- Python version: 3.9.0
These are the requirement packages i have installed
absl-py==2.1.0
annotated-types==0.6.0
anthropic==0.25.3
anyio==4.3.0
arabic-reshaper==3.0.0
asgiref==3.7.2
asn1crypto==1.5.1
astunparse==1.6.3
beautifulsoup4==4.12.3
bidict==0.23.1
blinker==1.7.0
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
cryptography==41.0.7
cssselect2==0.7.0
curl-cffi==0.6.2
cycler==0.12.1
distlib==0.3.8
distro==1.9.0
Django==4.2.11
dm-tree==0.1.8
dnspython==2.6.1
duckduckgo-search==5.3.0
eventlet==0.36.1
exceptiongroup==1.2.0
fastlogging==1.0.0
filelock==3.13.4
flask==3.0.3
Flask-Cors==4.0.0
Flask-SocketIO==5.3.6
flatbuffers==24.3.6
fontawesomefree==6.5.1
fonttools==4.49.0
fsspec==2024.3.1
gast==0.5.4
gevent==24.2.1
gevent-websocket==0.10.1
gitdb==4.0.11
GitPython==3.1.43
google-ai-generativelanguage==0.6.2
google-api-core==2.17.1
google-api-python-client==2.121.0
google-auth==2.28.1
google-auth-httplib2==0.2.0
google-auth-oauthlib==1.2.0
google-generativeai==0.5.1
google-pasta==0.2.0
googleapis-common-protos==1.62.0
greenlet==3.0.3
groq==0.5.0
grpcio==1.62.0
gspread==6.0.2
h11==0.14.0
h5py==3.10.0
html5lib==1.1
httpcore==1.0.5
httplib2==0.22.0
httpx==0.27.0
huggingface-hub==0.22.2
idna==3.6
importlib-metadata==7.0.1
importlib-resources==6.1.2
iniconfig==2.0.0
itsdangerous==2.2.0
Jinja2==3.1.3
joblib==1.3.2
keras==2.15.0
keybert==0.8.4
kiwisolver==1.4.5
libclang==16.0.6
lxml==5.2.1
Markdown==3.5.2
markdown-it-py==3.0.0
markdownify==0.12.1
MarkupSafe==2.1.5
matplotlib==3.8.3
mdurl==0.1.2
mistletoe==1.3.0
mistralai==0.1.8
ml-dtypes==0.2.0
mpmath==1.3.0
mysql-connector-python==8.3.0
mysqlclient==2.2.4
namex==0.0.7
netlify-py==0.1.0
networkx==3.2.1
np-utils==0.6.0
numpy==1.26.4
oauth2client==4.1.3
oauthlib==3.2.2
ollama==0.1.8
openai==1.20.0
opt-einsum==3.3.0
orjson==3.10.1
oscrypto==1.3.0
packaging==23.2
pandas==2.2.1
pdfminer.six==20231228
pillow==10.2.0
platformdirs==4.2.0
playwright==1.43.0
pluggy==1.4.0
proto-plus==1.23.0
protobuf==4.25.3
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==2.7.0
pydantic-core==2.18.1
pyee==11.1.0
pygments==2.17.2
pyHanko==0.23.2
pyhanko-certvalidator==0.26.3
PyMySQL==1.1.0
pyparsing==3.1.2
pypdf==4.2.0
pypng==0.20220715.0
pytest==8.1.1
pytest-base-url==2.1.0
pytest-playwright==0.4.4
python-bidi==0.4.2
python-dateutil==2.9.0.post0
python-engineio==4.9.0
python-slugify==8.0.4
python-socketio==5.11.2
pytz==2024.1
PyYAML==6.0.1
qrcode==7.4.2
regex==2024.4.16
reportlab==4.0.9
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.7.1
rsa==4.9
safetensors==0.4.3
scikit-learn==1.4.1.post1
scipy==1.12.0
sentence-transformers==2.6.1
simple-websocket==1.0.0
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
soupsieve==2.5
SQLAlchemy==2.0.29
sqlmodel==0.0.16
sqlparse==0.4.4
StrEnum==0.4.15
svglib==1.5.1
sympy==1.12
tensorboard==2.15.2
tensorboard-data-server==0.7.2
tensorflow==2.15.0
tensorflow-estimator==2.15.0
tensorflow-intel==2.15.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.4.0
text-unidecode==1.3
threadpoolctl==3.3.0
tiktoken==0.6.0
tinycss2==1.2.1
tokenizers==0.15.2
toml==0.10.2
tomli==2.0.1
torch==2.2.2
tqdm==4.66.2
transformers==4.39.3
typing-extensions==4.10.0
tzdata==2024.1
tzlocal==5.2
uritemplate==4.1.1
uritools==4.0.2
urllib3==1.26.15
virtualenv==20.25.1
webencodings==0.5.1
werkzeug==3.0.1
wrapt==1.14.1
wsproto==1.2.0
xhtml2pdf==0.2.15
zipp==3.17.0
zope.event==5.0
zope.interface==6.3

Thank you.

**Comment by nalaso** [comment]
I think type | type operantion is only supported in python 3.10 and later

**Comment by 20481A5450** [comment]
> I think type | type operation is only supported in python 3.10 and later

Then i'll change the python version and see if it is working

**Comment by acoulon99** [comment]
I also ran into this issue last night and was able to work around it by using Python 3.10.

**Comment by 20481A5450** [comment]
> I also ran into this issue last night and was able to work around it by using Python 3.10.

Glad you have replied does it work perfectly after making a fix to it?

**Comment by acoulon99** [comment]
> > I also ran into this issue last night and was able to work around it by using Python 3.10.
> 
> Glad you have replied does it work perfectly after making a fix to it?

I was able to successfully start the backend and frontend. I don’t have API keys setup yet so I haven’t tried to generate anything, but I’ll get into that during my next session and report back.

**Comment by 20481A5450** [comment]
### Problem has been solved
![Screenshot 2024-04-17 202416](https://github.com/stitionai/devika/assets/99806742/d98723b4-ebab-4499-b314-feb63225c25b)

It is up and running successfully thanks to you guys **@nalaso  @acoulon99** .

**Comment by acoulon99** [comment]
Great! :)
We should, though, update the readme so that others won’t encounter the same issue. I can submit a Pull Request during my next session.
