### ISSUE TITLE
update config file for the openAI base url

### ISSUE THREAD

**Issue by theguy000** [stitionai/devika#456]
### Describe the bug 
OpenAI base url is not correct.

### How To Reproduce
Steps to reproduce the behavior (example):
1. use openai and obeserve error "raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'type': 'invalid_request_error', 'code': 'unknown_url', 'message': 'Unknown request URL: POST /chat/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.', 'param': None}}"

I changed config.toml file like this - 
from 
```
OPENAI = "https://api.openai.com"
```
to 
```
OPENAI = "https://api.openai.com/v1"
```

**Comment by nalaso** [comment]
its fixed just now. Pull the latest commits
