### ISSUE TITLE
TypeError: 'type' object is not subscriptable - devika\src\llm

### ISSUE THREAD

**Issue by Roialfassi** [stitionai/devika#46]
line 32, in LLM
    def list_models(self) -> list[tuple[str, str]]:
TypeError: 'type' object is not subscriptable

**Comment by 0xSaurabhx** [comment]
> line 32, in LLM def list_models(self) -> list[tuple[str, str]]: TypeError: 'type' object is not subscriptable
use python version >3.8 and also its better to use venv for smooth run
