### ISSUE TITLE
When running through a proxy (JupyterHub) or a tunnel (VS Code with Tunneling) settings and logs URLS are created incorrectly

### ISSUE THREAD

**Issue by MGPowerlytics** [stitionai/devika#461]
### Describe the bug 
When running through a proxy (JupyterHub) or a tunnel (VS Code with Tunneling) settings and logs URLS are created incorrectly

### How To Reproduce
Steps to reproduce the behavior (example):
1. Viewing Devika UI through a JupyterHub proxy, the main page's URL would be generated such as www.company.com/jupyterhub/user/username/proxy/3001/
2. Clicking on settings tries to take you to www.company.com/settings

### Expected behavior
The URL should be generated relative to the current URL, not absolutely.
www.company.com/jupyterhub/user/<username>/proxy/3001/settings

Similar behavior happens through VS Code Tunnels and Port Forwarding. 

Both of these are exceptionally common development tools and in many cases the only way to view web UIs in corporate development environments.

**Comment by ARajgor** [comment]
solved it. fetch the latest changes.
