### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by smanna123** [stitionai/devika#47]
Your Reply to the Human Prompter: Sure, I can help you with that!

Current Focus: Developing a Tic-Tac-Toe game using Python.

Plan:
- [ ] Step 1: Research and understand the rules and logic of the Tic-Tac-Toe game.
- [ ] Step 2: Set up the Python development environment on your machine.
- [ ] Step 3: Create a blank 3x3 grid to represent the Tic-Tac-Toe board.
- [ ] Step 4: Implement the logic to alternate turns between two players (X and O).
- [ ] Step 5: Allow players to input their moves on the grid.
- [ ] Step 6: Check for winning conditions after each move.
- [ ] Step 7: Implement a function to check for a draw if no player wins.
- [ ] Step 8: Display the updated board after each move.
- [ ] Step 9: Continue the game until a player wins or it ends in a draw.
- [ ] Step 10: Display the end result (win/draw) and ask if players want to play again.

Summary: To create a Tic-Tac-Toe game in Python, we need to research the game rules, set up the development environment, implement the game logic including player input and turn alternation, check for winning conditions, and display the game board. Testing will involve ensuring the game runs smoothly without bugs, and the final game should allow for continuous play. Dependencies include understanding basic Python syntax and data structures, as well as implementing the grid logic for the game board. Potential challenges may arise in handling user input and managing game states effectively.
```
==================================================
{'developing', 'toe', 'python', 'game', 'tic'}
Token usage: 1160
Token usage: 1206
I need to research the rules of Tic-Tac-Toe and set up the Python environment first. Then I can start creating the game logic and interface for players to input their moves.
==================================================
Token usage: 2121
Token usage: 2178
{'queries': ['Tic-Tac-Toe game rules and logic explanation Python', 'Python development environment setup guide for beginners', '3x3 grid implementation in Python for Tic-Tac-Toe game'], 'ask_user': ''}
==================================================
Exception in thread Thread-167 (<lambda>):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/broadifi/Desktop/work/ai_soft/devika/devika.py", line 49, in <lambda>
    target=lambda: Agent(base_model=base_model).execute(prompt, project_name)
  File "/home/broadifi/Desktop/work/ai_soft/devika/src/agents/agent.py", line 333, in execute
    search_results = self.search_queries(queries, project_name)
  File "/home/broadifi/Desktop/work/ai_soft/devika/src/agents/agent.py", line 84, in search_queries
    link = bing_search.get_first_link()
  File "/home/broadifi/Desktop/work/ai_soft/devika/src/browser/search.py", line 24, in get_first_link
    return self.query_result["webPages"]["value"][0]["url"]
TypeError: 'NoneType' object is not subscriptable

**Comment by Ph0rk0z** [comment]
For me too.. I don't have a bing API key nor can I really get one.

**Comment by hollaugo** [comment]
Had the same issue, can we use Tavily or Serapi APIs?

**Comment by ARajgor** [comment]
fetch the latest changes
