### ISSUE TITLE
Make the installation guide clearer

### ISSUE THREAD

**Issue by PierrunoYT** [stitionai/devika#48]
It's hard to see how to install devika on windows step by step. Pls add a better and clearer readme.

**Comment by DrewPear309** [comment]
I'm on windows. install seems easy and straightforward, but i have an error running the server.
are you having issues getting it running? was there items the install guide did not cover?
thank you!

**Comment by PierrunoYT** [comment]
I don't really see a Windows Installation Guide inside the Readme. I think it's build in the wrong way.

**Comment by DrewPear309** [comment]
Bun is not working?
The instructions assume a minimal pre-understanding that you use the windows command line and 2 programs installed. Type cmd into the start bar to search for it and open it up. before you do anything, be sure to have installed python and git from the respective web sites.
Type cd c:\ into the commandline. this takes you to your C drive. Then follow the instructions in the readme. you find the folder.  Cheers!

**Comment by PierrunoYT** [comment]
Thanks for the reply but why it says that it need the bun.sh installed?

**Comment by RohitX0X** [comment]
> Thanks for the reply but why it says that it need the bun.sh installed?

Did u install bun? 

if not , run this in your cmd/git bash
`powershell -c "irm bun.sh/install.ps1|iex"
`

**Comment by PierrunoYT** [comment]
> powershell -c "irm bun.sh/install.ps1|iex"

No because the installation guide is a mess.

**Comment by PierrunoYT** [comment]
WARNUNG: Bun for Windows is currently experimental.
For a more stable experience, install Bun within WSL:
https://bun.sh/docs/installation
To get started, restart your terminal/editor, then type "bun"

**Comment by PierrunoYT** [comment]
> > Thanks for the reply but why it says that it need the bun.sh installed?
> 
> Did u install bun?
> 
> if not , run this in your cmd/git bash `powershell -c "irm bun.sh/install.ps1|iex" `
> 
> later you might even need to do
> 
> `bun install vite`

I installed it now but what should I set in the config?

**Comment by RohitX0X** [comment]
> Author

are you able to run 
`bun run dev`
in your ui folder in cmd

after that set your api key in config.toml
If you are using openai then provide the string there

**Comment by PierrunoYT** [comment]
> > Author
> 
> are you able to run `bun run dev` in your ui folder in cmd
> 
> after that set your api key in config.toml If you are using openai then provide the string there

Can you add me on Discord PierrunoYT

**Comment by RohitX0X** [comment]
> Can you add me on Discord PierrunoYT

I currently do not use it as it is blocked xd  
Btw Do we have a discord group for this?

**Comment by PierrunoYT** [comment]
> > Can you add me on Discord PierrunoYT
> 
> I currently do not use it as it is blocked xd Btw Do we have a discord group for this?

How can I communicate with you? I wanted to make a discord server for this but I could need some help.

**Comment by PierrunoYT** [comment]
I created one https://discord.gg/nKP3f6p4v5

**Comment by 0xsunil** [comment]
Alternatively, you can use WSL. It works fine.

**Comment by ARajgor** [comment]
done.

**Comment by ARajgor** [comment]
https://github.com/stitionai/devika/pull/387
