### ISSUE TITLE
Missing API Key Input [ISSUE]

### ISSUE THREAD

**Issue by lscheder** [stitionai/devika#498]
### Describe your issue
Hello! I just installed Devika and got it up and running, only for one vital feature to be missing: The ability to input API keys within the settings menu. Please see images for reference...

### How To Reproduce
Steps to reproduce the behavior (example):
1. Launch Devika.
2. Navigate to the settings menu.

### Expected behavior
I should be able to add API keys to the settings...

### Screenshots and logs
Issue:
![image](https://github.com/stitionai/devika/assets/156968723/b6e70b2b-0e86-4a18-b85a-f1784c6ceaef)

Launching from Bun:
![image](https://github.com/stitionai/devika/assets/156968723/e1eb56a0-0f8e-4828-9528-9183539c9aef)
![image](https://github.com/stitionai/devika/assets/156968723/00f8de49-4803-475c-ac74-20dc14f6a8d5)

Launching from Python:
![image](https://github.com/stitionai/devika/assets/156968723/a8bd2080-7215-421c-badf-aabbb4e709df)

### Configuration
```
- OS: Windows 11
- Python version: 3.10.6
- Node version: v20.11.1
- bun version: 1.1.5
- search engine: Not Available
- Model: None Installed Yet
```

#### Additional context
I was following along with Aitrepreneur's video about installing Devika. After getting through the installation and everything seems to be working fine, I open the service to encounter that bug... Please help me! And thanks in advance!

Quick edit: Clicking the edit button changes the button to Save but no text input option exists.

**Comment by Orindoomhammer** [comment]
I have no answer to this only some more information, I too am getting this error, In the main page its saying that it is not connected to the server.

**Comment by lscheder** [comment]
> I have no answer to this only some more information, I too am getting this error, In the main page its saying that it is not connected to the server.
> 
> ![image](https://private-user-images.githubusercontent.com/10428441/326119968-8dae393d-29d5-4e99-bc7c-fbf8e78c089b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNjg4NTEsIm5iZiI6MTcxNDE2ODU1MSwicGF0aCI6Ii8xMDQyODQ0MS8zMjYxMTk5NjgtOGRhZTM5M2QtMjlkNS00ZTk5LWJjN2MtZmJmOGU3OGMwODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDIxNTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NTY3MzBiMzU1ZjZkZWU1ZDI4MzQ1ZmU2NmQ2NzExYjRmNGZhMjczNWJlODkxYTU4Y2M1MzA4MmM5OTQ0MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EbJ6cJYb5ajNxcXQkLqavUfBjHEZAJB-8qxZCRUQWC0)

Yes, same here, sorry for not putting this in the original post…

**Comment by ARajgor** [comment]
first run the python server then try for frontend

**Comment by lscheder** [comment]
> first run the python server then try for frontend

Sorry, this didn't work for me... Thank you for the response though :D

**Comment by ASXXX0** [comment]
i have the same problem try to run with bun run dev --host and take the 192.168.. ip it working for me

**Comment by lscheder** [comment]
> i have the same problem try to run with bun run dev --host and take the 192.168.. ip it working for me

Thank you! This worked great for me! Steps:

1. Run devika backend.
2. Run devika front end using bun run dev --host
3. Click on either network links
4. Navigate to setting to find API input boxes there.

Thank you so much!

P.S. If you want me to reopen this thread, please PM me...
