### ISSUE TITLE
Implement extensive logging throughout the project

### ISSUE THREAD

**Issue by mufeedvh** [stitionai/devika#5]
The [`Logger`](https://github.com/stitionai/devika/blob/main/src/logger.py) has not been integrated into the project yet. All agent routes and code paths should implement extensive logging.

**Comment by rohittp0** [comment]
Hi, I think I can help with this. Can you assign me the issue?

**Comment by 123vivekr** [comment]
That's awesome. Reply here if you need help or on Discord :)

**Comment by VJlaxmi** [comment]
Hi, If this issue is open, I can contribute

**Comment by rohittp0** [comment]
I think it would be nice if you can handle more of such cases and add proper error logging

**Comment by VJlaxmi** [comment]
Should I pick it up?

**Comment by rohittp0** [comment]
@VJlaxmi It would be great if you can. Feel free to reach out if you need anything from my side.
