### ISSUE TITLE
run success but not wroking 

### ISSUE THREAD

**Issue by sulaymanyf** [stitionai/devika#50]
I try run devika and want to use local ollama, ollama is working frontend is working beacuse i can see project name is backend is not work i cannot see project name 
backend terminal -----------------
24.03.22 16:18:12: root: INFO   : Booting up... This may take a few seconds
24.03.22 16:18:12: root: INFO   : Initializing Devika...
24.03.22 16:18:12: root: INFO   : Initializing Prerequisites Jobs...
24.03.22 16:18:12: root: INFO   : Loading sentence-transformer BERT models...
24.03.22 16:18:15: root: INFO   : BERT model loaded successfully.
 * Serving Flask app 'devika'
 * Debug mode: off
 * ----------------------------
frontend 
  VITE v5.1.6  ready in 450 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.
warn - Update your configuration file to eliminate this warning.
===========================
when i write some thing in the input no response

**Comment by robin-collins** [comment]
experiencing the same

**Comment by rohittp0** [comment]
There is a bug causing this https://github.com/stitionai/devika/blob/6d45188ed2358047e7c291f87a256395df2bd6c6/devika.py#L101 if is always false. The    `AgentState().is_agent_completed(project_name)` is returning `None`.

**Comment by feirydraco** [comment]
hey, is there a solution for this ? @rohittp0

**Comment by sulaymanyf** [comment]
@rohittp0 you are right there returned none

**Comment by sulaymanyf** [comment]
fixed the issue 
1. src/llm 
  `    OLLAMA_MODELS = [
        (
            model["name"].split(":")[0],
            model["name"]
        )
        for model in Ollama.list_models()
    ]`  line 20-26

`        ollama_models = {model[1]: "OLLAMA_MODELS" for model in Model.OLLAMA_MODELS.value}
`  line 39

2. delete db/devika.db  and restart
