### ISSUE TITLE
Inference shouldn't have a timeout

### ISSUE THREAD

**Issue by PlanetMacro** [stitionai/devika#502]
Especially with larger local models on OLLAMA, inference might take some time. Especially on the initial loading of the model. Currently devika throws a timeout, basically rendering its useless for such a setup.

**Comment by DGdev91** [comment]
Seems like the timeout is hardcoded in llm.py
`if int(elapsed_time) == 30:
    emit_agent("inference", {"type": "warning", "message": "Inference is taking longer than expected"})
if elapsed_time > 60:
    raise concurrent.futures.TimeoutError`

As a quick hack to make it work you can increase those values, or just comment the lines.

Anyway, i agree. it shouldn't have a timeout, or at least it should be easly configurable to increase/disable it if needed
