### ISSUE TITLE
[ISSUE] unable to give input (UI isnt working fine)

### ISSUE THREAD

**Issue by danilo139** [stitionai/devika#513]
after giving the first prompt to devika: "make a python app that generate ultra secure random passwords" she ask me later for Please provide an upper limit for the length of the generated passwords.

until here is everything fine, the problem is that the UI is having some bug because when devika ask me for some input, im not able to write anything in the input box (it appears a forbidden sign), so is impossible to give the input to continue.

using ollama with llama3 model and also tried with dolphin-llama3 (is happenining with every model i tried)

see pictures attached below

![image](https://github.com/stitionai/devika/assets/151397556/60b0ea21-64ff-49e9-81ba-33d9f11318b0)
![image](https://github.com/stitionai/devika/assets/151397556/86bdd363-9b10-46f6-ba0d-e30ca327f79c)

**Comment by ARajgor** [comment]
fixed
