### ISSUE TITLE
vite-plugin-svelte not found

### ISSUE THREAD

**Issue by haseeb-heaven** [stitionai/devika#52]
The error message indicates that the package '@sveltejs/vite-plugin-svelte' is not found. This package is required by your Vite configuration file.

You should install the missing package by running the following command in your terminal:
`npm install @sveltejs/vite-plugin-svelte`

After running this command, try running your development server again with npm run dev.

Here is PR for this https://github.com/stitionai/devika/pull/51

**Comment by amjiddader** [comment]
Make sure npm and node is installed (use nvm for node) \

if `npm install ` doesn't work use ` npm update --legacy-peer-deps`
