### ISSUE TITLE
[ISSUE] Error "playwright install --with-deps" on Ubuntu 24.04

### ISSUE THREAD

**Issue by cesaregerbino** [stitionai/devika#523]
### Issue description
Running this command `playwright install --with-deps,` as per the installation procedure, I get this error ...

    Installing dependencies...
    Switching to root user to install dependencies...
    Hit:1 http://it.archive.ubuntu.com/ubuntu noble InRelease
    Hit:2 http://security.ubuntu.com/ubuntu noble-security InRelease
    Hit:3 http://it.archive.ubuntu.com/ubuntu noble-updates InRelease
    Get:4 http://it.archive.ubuntu.com/ubuntu noble-backports InRelease [90.8 kB]
    Fetched 90.8 kB in 0s (208 kB/s)
    Reading package lists... Done
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done

    Note, selecting 'libatk-bridge2.0-0t64' instead of 'libatk-bridge2.0-0'
    Note, selecting 'libatk1.0-0t64' instead of 'libatk1.0-0'
    Note, selecting 'libatspi2.0-0t64' instead of 'libatspi2.0-0'
    Note, selecting 'libcups2t64' instead of 'libcups2'
    Note, selecting 'libglib2.0-0t64' instead of 'libglib2.0-0'
    Note, selecting 'libgtk-3-0t64' instead of 'libgtk-3-0'
    Note, selecting 'libpng16-16t64' instead of 'libpng16-16'
    Note, selecting 'libevent-2.1-7t64' instead of 'libevent-2.1-7'
    Package libasound2 is a virtual package provided by:
     liboss4-salsa-asound2 4.2-build2020-1ubuntu3
     libasound2t64 1.2.11-1build2 (= 1.2.11-1build2)
    You should explicitly select one to install.

    E: Package 'libasound2' has no installation candidate
    E: Unable to locate package libicu70
    E: Unable to locate package libffi7
    E: Unable to locate package libx264-163
    Failed to install browsers
    Error: Installation process exited with code: 100

### How To Reproduce
Trying to follow the installation commands

### Expected behavior
A correct installation without errors

### Configuration
```
- OS: Ubuntu 24.04 virtual machine via Oracle Virtual Box 7.0 on Windows 11
- Python version: 3.11.9
- Node version: 20.12.2
- bun version: 1.1.6
- search engine: not defined in config.toml
- Model: OpenAI 3.5
```

#### Additional context
Here you are my `config.toml` file
```
[STORAGE]
SQLITE_DB = "data/db/devika.db"
SCREENSHOTS_DIR = "data/screenshots"
PDFS_DIR = "data/pdfs"
PROJECTS_DIR = "data/projects"
LOGS_DIR = "data/logs"
REPOS_DIR = "data/repos"

[API_KEYS]
BING = "<YOUR_BING_API_KEY>"
GOOGLE_SEARCH = "<YOUR_GOOGLE_SEARCH_API_KEY>"
GOOGLE_SEARCH_ENGINE_ID = "<YOUR_GOOGLE_SEARCH_ENGINE_ID>"
CLAUDE = "<YOUR_CLAUDE_API_KEY>"
OPENAI = "sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
GEMINI = "<YOUR_GEMINI_API_KEY>"
MISTRAL = "<YOUR_MISTRAL_API_KEY>"
GROQ = "<YOUR_GROQ_API_KEY>"
NETLIFY = "<YOUR_NETLIFY_API_KEY>"

[API_ENDPOINTS]
BING = "https://api.bing.microsoft.com/v7.0/search"
GOOGLE = "https://www.googleapis.com/customsearch/v1"
OLLAMA = "http://127.0.0.1:11434"
OPENAI = "https://api.openai.com/v1"

[LOGGING]
LOG_REST_API = "true"
LOG_PROMPTS = "false"

[TIMEOUT]
INFERENCE = 60
```

Any suggestion will be appreciated!!

**Comment by Polygons1** [comment]
follow this issue: https://github.com/microsoft/playwright/issues/30368
