### ISSUE TITLE
[Bug] Docker compose file not working as expected (app.dockerfile: no such file or directory)

### ISSUE THREAD

**Issue by prakashchokalingam** [stitionai/devika#528]
### Describe the bug 
Getting the below error while running the docker compose file

failed to solve: failed to read dockerfile: open app.dockerfile: no such file or directory

### How To Reproduce
Steps to reproduce the behavior (example):
1. docker compose -f "docker-compose.yaml" up -d --build

### Expected behavior
As the error suggests there is no file app.dockerfile present in the repo.

### Screenshots and logs
must share logs from frontend or backend. also If applicable, add screenshots to help explain your problem. 

<img width="1091" alt="Screenshot 2024-05-03 at 11 38 59 AM" src="https://github.com/stitionai/devika/assets/5512765/7b0d37a8-a9f1-4dbc-ba1d-d845ece2f0de">

**Comment by Polygons1** [comment]
it was removed for some reason in #522
