### ISSUE TITLE
Devika running perfectly

### ISSUE THREAD

**Issue by raju11011967** [stitionai/devika#549]
Hi,
I have run frontend and backend for devika successfully, when  i give a test message, devika is not connecting to any of the LLM's and always showing api key error (in the background) and not working and shows waiting in terminal.
Any help with this issue will be highly appreciated.
Thank you in advance

**Comment by raju11011967** [comment]
24.05.11 11:29:23: root: INFO   : Initializing Devika...
24.05.11 11:29:23: root: INFO   : checking configurations...
24.05.11 11:29:23: root: INFO   : Initializing Prerequisites Jobs...
24.05.11 11:29:37: root: INFO   : Loading sentence-transformer BERT models...
24.05.11 11:29:51: root: INFO   : BERT model loaded successfully.
24.05.11 11:29:56: root: INFO   : Ollama available
24.05.11 11:29:59: root: INFO   : Devika is up and running!
24.05.11 11:30:15: root: INFO   : /api/data GET
24.05.11 11:30:15: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["LLAMA3 8B","llama3-8b-8192"],["LLAMA3 70B","llama3-70b-8192"],["LLAMA2 70B","llama2-70b-4096"],["Mixtral","mixtral-8x7b-32768"],["GEMMA 7B","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[],"OPENAI":[["GPT-4 Turbo","gpt-4-turbo"],["GPT-3.5 Turbo","gpt-3.5-turbo-0125"]]},"projects":["test"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.05.11 11:30:15: root: INFO   : /api/status GET
24.05.11 11:30:15: root: DEBUG  : /api/status GET - Response: {"status":"server is running!"}

Socket connected ::  {'data': 'frontend connected!'}
24.05.11 11:30:15: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.05.11 11:30:48: root: INFO   : /api/settings GET
24.05.11 11:30:48: root: DEBUG  : /api/settings GET - Response: *** Settings are not logged ***
24.05.11 11:31:20: root: INFO   : /api/settings POST
24.05.11 11:31:20: root: DEBUG  : /api/settings POST - Response: *** Settings are not logged ***
24.05.11 11:31:24: root: INFO   : /api/data GET
24.05.11 11:31:24: root: DEBUG  : /api/data GET - Response: {"models":{"CLAUDE":[["Claude 3 Opus","claude-3-opus-20240229"],["Claude 3 Sonnet","claude-3-sonnet-20240229"],["Claude 3 Haiku","claude-3-haiku-20240307"]],"GOOGLE":[["Gemini 1.0 Pro","gemini-pro"]],"GROQ":[["LLAMA3 8B","llama3-8b-8192"],["LLAMA3 70B","llama3-70b-8192"],["LLAMA2 70B","llama2-70b-4096"],["Mixtral","mixtral-8x7b-32768"],["GEMMA 7B","gemma-7b-it"]],"MISTRAL":[["Mistral 7b","open-mistral-7b"],["Mistral 8x7b","open-mixtral-8x7b"],["Mistral Medium","mistral-medium-latest"],["Mistral Small","mistral-small-latest"],["Mistral Large","mistral-large-latest"]],"OLLAMA":[],"OPENAI":[["GPT-4 Turbo","gpt-4-turbo"],["GPT-3.5 Turbo","gpt-3.5-turbo-0125"]]},"projects":["test"],"search_engines":["Bing","Google","DuckDuckGo"]}

24.05.11 11:31:24: root: INFO   : /api/status GET
24.05.11 11:31:24: root: DEBUG  : /api/status GET - Response: {"status":"server is running!"}

Socket connected ::  {'data': 'frontend connected!'}
24.05.11 11:31:24: root: INFO   : SOCKET socket_response MESSAGE: {'data': 'Server Connected'}
24.05.11 11:31:31: root: INFO   : User message: {'message': 'test', 'base_model': 'Claude 3 Sonnet', 'project_name': 'test', 'search_engine': 'Google'}
24.05.11 11:31:32: root: INFO   : SOCKET info MESSAGE: {'type': 'warning', 'message': "previous agent doesn't completed it's task."}
24.05.11 11:31:32: root: INFO   : SOCKET server-message MESSAGE: {'messages': {'from_devika': False, 'message': 'test', 'timestamp': '2024-05-11 11:31:32'}}
24.05.11 11:31:32: root: INFO   : SOCKET agent-state MESSAGE: [{'internal_monologue': "I'm starting the work...", 'browser_session': {'url': None, 'screenshot': None}, 'terminal_session': {'command': None, 'output': None, 'title': None}, 'step': 1, 'message': None, 'completed': False, 'agent_is_active': True, 'token_usage': 0, 'timestamp': '2024-05-11 11:31:32'}]
24.05.11 11:31:32: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 2183}
Model: Claude 3 Sonnet, Enum: CLAUDE
ype': 'time', 'elapsed_time': '0.21'}
24.05.11 11:31:35: root: INFO   : SOCKET inference MESSAGE: {'type': 'time', 'elapsed_time': '0.73'}
24.05.11 11:31:35: root: ERROR  : Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}
24.05.11 11:31:35: root: INFO   : SOCKET inference MESSAGE: {'type': 'error', 'message': "Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}}"}

**Comment by raju11011967** [comment]
error in the backend

**Comment by raju11011967** [comment]
help with this error

**Comment by sbera7** [comment]
how were you able to resolve the issue? I am getting a similar kind of error. I am using local llm Mistral:7B. Getting an error 
```root: INFO   : SOCKET inference MESSAGE: {'type': 'error', 'message': 'Status: 401. Message: {\n  "message":"Unauthorized",\n  "request_id":"26b2964f5351f75cd8132a02ec160b17"\n}'}```
