### ISSUE TITLE
运行devika.py报错

### ISSUE THREAD

**Issue by taojinying** [stitionai/devika#555]
用pyhton运行devika.py之后，提示：
No sentence-transformers model found with name sentence-transformers/all-MiniLM-L6-v2. Creating a new one with MEAN pooling
![Uploading 1.png…]()

**Comment by taojinying** [comment]
![Uploading 1.png…]()

**Comment by taojinying** [comment]
![Uploading 2.png…]()

**Comment by taojinying** [comment]
![2024-05-13 01-25-57屏幕截图](https://github.com/stitionai/devika/assets/101920788/396a2a0e-cad9-4646-af6c-528c4b6f88d4)

**Comment by ARajgor** [comment]
duplicate https://github.com/stitionai/devika/issues/293
