### ISSUE TITLE
No output from Devika

### ISSUE THREAD

**Issue by Dultus** [stitionai/devika#56]
![image](https://github.com/stitionai/devika/assets/37348379/c4545acc-c3bb-49bf-bea5-aa242793ae27)
![image](https://github.com/stitionai/devika/assets/37348379/06de662c-291b-459e-a6bc-1cba4d3d8ce8)
Devika doesn't respond. Any ideas?

**Comment by RohitX0X** [comment]
try creating new project and try again, Wait for a while after first query
 I see only the first time , agent execution is called in the api

**Comment by Dultus** [comment]
> try creating new project and try again, Wait for a while after first query I see only the first time , agent execution is called in the api

![image](https://github.com/stitionai/devika/assets/37348379/3a2e8251-207b-45eb-9e4e-da8315aa4d14)
Hmm, it says the api_key is missing - it's set though.

**Comment by RohitX0X** [comment]
Yep thats right , see issue: https://github.com/stitionai/devika/issues/29

**Comment by titonova** [comment]
Fixed here: #59

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
