### ISSUE TITLE
Anyone want to help with the Discord Server?

### ISSUE THREAD

**Issue by PierrunoYT** [stitionai/devika#58]
I created one for Devika. DM me if you want to help with it: https://discord.gg/nKP3f6p4v5

**Comment by PierrunoYT** [comment]
It still need some work

**Comment by mufeedvh** [comment]
Hi @PierrunoYT, here's the Discord Invite: https://discord.com/invite/8eYNbPuB

**Comment by PierrunoYT** [comment]
Hey there

Can you send me a DM on Discord:
PierrunoYT?

**Comment by lainofthewired369** [comment]
can you send discord link

**Comment by LeonieFreisinger** [comment]
can you send me the discord link as well? Thanks!

**Comment by ARajgor** [comment]
we are already working @PierrunoYT ;)
