### ISSUE TITLE
Openai api ket not working

### ISSUE THREAD

**Issue by davtin19** [stitionai/devika#59]
TypeError: OpenAI.__init__() missing 1 required positional argument: 'api_key'
[2024-03-22 13:20:25,809] ERROR in app: Exception on /api/project-list [GET]
Traceback (most recent call last):

**Comment by titonova** [comment]
Fixed here: #62

**Comment by shreydevep** [comment]
Try upgrading **toml and openai packages**

`TypeError: OpenAI.__init__() missing 1 required positional argument: 'api_key'
(base) shreyaspandey@Shreyass-MacBook-Air devika % pip install toml --upgrade
Requirement already satisfied: toml in /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages (0.10.2)
MacBook-Air devika % python devika.py          
24.03.23 07:41:53: root: WARNING: Ollama server not running, please start the server to use models from Ollama.
24.03.23 07:41:56: root: INFO   : Booting up... This may take a few seconds
24.03.23 07:41:56: root: INFO   : Initializing Devika...
24.03.23 07:41:56: root: INFO   : Initializing Prerequisites Jobs...
24.03.23 07:41:56: root: INFO   : Loading sentence-transformer BERT models...
24.03.23 07:42:02: root: INFO   : BERT model loaded successfully.
 * Serving Flask app 'devika'
 * Debug mode: off`
``

> TypeError: OpenAI.**init**() missing 1 required positional argument: 'api_key' [2024-03-22 13:20:25,809] ERROR in app: Exception on /api/project-list [GET] Traceback (most recent call last):

``

**Comment by Fratua** [comment]
The project was updated to fix this issue, you can manually change the
files, make a new clone, or update your existing copy of devika

**Comment by Fratua** [comment]
You also might want to install ollama, I'm not sure what difference it
makes but I did Install it

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed
