### ISSUE TITLE
[Bug] npm install freeze on docker build

### ISSUE THREAD

**Issue by LuuNa-JD** [stitionai/devika#598]
### Describe the bug 
I encountered an issue where npm install freezes on the dependency color-name. Despite trying several solutions, the installation process remains stuck, preventing further progress.

### How To Reproduce
Steps to reproduce the behavior (example):
1. Clone the repository and navigate to the project directory.
2. Run docker-compose build
3. During the build process of devika-frontend-app , observe that npm install hangs on "color-name"

### Expected behavior
The npm install command should complete successfully without freezing on any dependency, allowing the Docker image to be built properly.

### Screenshots and logs
```
npm install --legacy-peer-deps --verbose
[...]
npm http fetch GET 200 https://registry.npmjs.org/color-name 99ms (cache miss)
```

### Configuration
```
- OS: Linux (WSL 2 on Windows)
- Python version: 3.10
- Node version: 20.14.0
- bun version: 0.1.0
- search engine: npm registry
- Model: not applicable
```

#### Additional context
I have tried the following solutions:
- Updating the Dockerfile to use the latest version of dependencies.
- Cleaning the npm cache and setting the registry to https://registry.npmjs.org/.
- Attempting to bypass the problematic dependency color-name by setting up npm configurations and registry changes.

Despite these attempts, the installation process still freezes on color-name. Any assistance or guidance on how to properly configure the npm installation to avoid this issue would be greatly appreciated. Thank you!

**Comment by nickbcmu** [comment]
What was the solution to this? I'm encountering the same problem on Windows builds.
