### ISSUE TITLE
[Bug] Getting error "unsupported operand type(s) for |: 'type' and 'type'"

### ISSUE THREAD

**Issue by lalitgupta-blr** [stitionai/devika#625]
### Describe the bug 

 % python3 devika.py
24.07.14 17:14:23: root: INFO   : Initializing Devika...
24.07.14 17:14:23: root: INFO   : checking configurations...
24.07.14 17:14:23: root: INFO   : Initializing Prerequisites Jobs...
24.07.14 17:14:28: root: INFO   : Loading sentence-transformer BERT models...
24.07.14 17:14:32: root: INFO   : BERT model loaded successfully.
24.07.14 17:14:33: root: WARNING: Ollama not available
24.07.14 17:14:33: root: WARNING: run ollama server to use ollama models otherwise use API models
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Traceback (most recent call last):
  File "/Users/lg/Perseeq/Devika/devika/devika.py", line 24, in <module>
    from src.agents import Agent
  File "/Users/lg/Perseeq/Devika/devika/src/agents/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/Users/lg/Perseeq/Devika/devika/src/agents/agent.py", line 2, in <module>
    from .researcher import Researcher
  File "/Users/lg/Perseeq/Devika/devika/src/agents/researcher/__init__.py", line 1, in <module>
    from .researcher import Researcher
  File "/Users/lg/Perseeq/Devika/devika/src/agents/researcher/researcher.py", line 13, in <module>
    class Researcher:
  File "/Users/lg/Perseeq/Devika/devika/src/agents/researcher/researcher.py", line 27, in Researcher
    def validate_response(self, response: str) -> dict | bool:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### How To Reproduce
Steps to reproduce the behavior (example):
1. {steps_1}
2. {steps_2}
3. {steps_3}
After downloading from default branch :
pip install -r requirements.txt
pip install protobuf==3.20.1  
python3 devika.py

### Expected behavior
WebUI on port 3000 should open

### Screenshots and logs
must share logs from frontend or backend. also If applicable, add screenshots to help explain your problem. 
24.07.14 17:14:23: root: INFO   : Initializing Devika...
24.07.14 17:14:23: root: INFO   : checking configurations...
24.07.14 17:14:23: root: INFO   : Initializing Prerequisites Jobs...
24.07.14 17:14:28: root: INFO   : Loading sentence-transformer BERT models...
24.07.14 17:14:32: root: INFO   : BERT model loaded successfully.
24.07.14 17:14:33: root: WARNING: Ollama not available
24.07.14 17:14:33: root: WARNING: run ollama server to use ollama models otherwise use API models
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Traceback (most recent call last):
  File "/Users/lg/Perseeq/Devika/devika/devika.py", line 24, in <module>
    from src.agents import Agent
  File "/Users/lg/Perseeq/Devika/devika/src/agents/__init__.py", line 1, in <module>
    from .agent import Agent
  File "/Users/lg/Perseeq/Devika/devika/src/agents/agent.py", line 2, in <module>
    from .researcher import Researcher
  File "/Users/lg/Perseeq/Devika/devika/src/agents/researcher/__init__.py", line 1, in <module>
    from .researcher import Researcher
  File "/Users/lg/Perseeq/Devika/devika/src/agents/researcher/researcher.py", line 13, in <module>
    class Researcher:
  File "/Users/lg/Perseeq/Devika/devika/src/agents/researcher/researcher.py", line 27, in Researcher
    def validate_response(self, response: str) -> dict | bool:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### Configuration
```
- OS: [e.g. Windows, Linux, MacOS] MacOS
- Python version: [e.g. 3.10]  3.9.7
- Node version: [e.g. 18.0.0] v15.14.0
- bun version: [e.g. 0.1.0] 
- search engine: [e.g. google] default
- Model: [e.g. gpt, cluade] default
```

**Comment by lalitgupta-blr** [comment]
Same outcome with python 3.10 (after using brew install python@3.10)

**Comment by ARajgor** [comment]
You have to use Python 3.10 or the letter version.
