### ISSUE TITLE
How to run it with ollama?

### ISSUE THREAD

**Issue by alfi4000** [stitionai/devika#63]
How can I run it with ollama local model?
I just see people say they use ollama local models!

**Comment by haseeb-heaven** [comment]
There is PR for this and its working for me its not merged yet

**Comment by haseeb-heaven** [comment]
https://github.com/stitionai/devika/pull/49

**Comment by alfi4000** [comment]
I found it quick start but got error in the gui: https://github.com/stitionai/devika/issues/37#issuecomment-2016312356
