### ISSUE TITLE
There is a Bug in the MistralAi Library.

### ISSUE THREAD

**Issue by FarVision2** [stitionai/devika#640]
There is a Bug in the MistralAi Library.

```
File "/home/x/devika/src/llm/llm.py", line 11, in <module>
    from .mistral_client import MistralAi
  File "/home/x/devika/src/llm/mistral_client.py", line 2, in <module>
    from mistralai.models.chat_completion import ChatMessage
ModuleNotFoundError: No module named 'mistralai.models.chat_completion'
```

Module installed numerous times.

 I can't say that I can debug the entire Mistral AI module so it is disabled in llm.py 

```
from .gemini_client import Gemini
# from .mistral_client import MistralAi
from .groq_client import Groq
```

The project then runs in standalone and in docker-compose.

However, in devika.py some of the ports are misconfigured for the front end, and it doesn't attach to the back end even when running manually as well as docker.

and

There is no sandbox attachment in standalone nor in docker. 

Did we build a rocket ship to the moon and leave everyone behind?

 perhaps an alternate dimension?

 the world may never know

**Next time If you're going to bail on a project hit that archive button so we get the alert.**

**Comment by Hasnainbro** [comment]
well there is no actual chat_completion model, so what can be done to make it right? I tried re installing but same error

**Comment by hardikns** [comment]
Install a older version of the lib mistralai==0.4.2

**Comment by Hasnainbro** [comment]
> Install a older version of the lib mistralai==0.4.2
Its working fine now! I just changed the code to newer version instead!

**Comment by ARajgor** [comment]
resolved https://github.com/stitionai/devika/pull/633

**Comment by WahahaZeng** [comment]
I have the bug now. And my version is the latest one 1.2.5. Anyone has any ideas?
