### ISSUE TITLE
Document Prerequisites: Hardware and Software

### ISSUE THREAD

**Issue by harshbakori** [stitionai/devika#68]
This issue is raised to document the prerequisites required for the project in terms of both hardware and software. Ensuring that users have the necessary environment set up will improve the on-boarding experience and reduce confusion.

**Comment by Ph0rk0z** [comment]
The readme was pretty good.. in terms of hardware you're on your own. Can use small models on 1 gpu or big models. Am testing it with 103-120b @ 16k context.
