### ISSUE TITLE
How to use the Gemini Model in config

### ISSUE THREAD

**Issue by Revanthraja** [stitionai/devika#71]

**Comment by bugthug404** [comment]
why do you need to use gemini model in config?
after running project you can select any gemini model from ollama & use it (if ollama running in background)
or 
please provide more context what you want to achieve.

**Comment by RohitX0X** [comment]
Do you mean Gemini API , if yes , i think there is another PR on this https://github.com/stitionai/devika/pull/24 yet to be merged

**Comment by Revanthraja** [comment]
Yes
