### ISSUE TITLE
No response from devika

### ISSUE THREAD

**Issue by dx111ge** [stitionai/devika#79]
Did the installation and did start first devika.py than ui. Could create the project (even the project is not visible in the folder project, just in sqllite db file). added the keys and did simple type hello, there is no response in ui, nor any error in console or log, just looping and showing the following : 24.03.23 21:26:51: root: INFO   : /api/get-messages POST
24.03.23 21:26:51: root: DEBUG  : /api/get-messages POST - Response: {"messages":[{"from_devika":false,
"message":"hello","timestamp":"2024-03-23 21:26:15"}]}

any advice? I don't even know where to search for an error message beside the log and the console.just one small hint in the ui console i found : 9:25:41 PM [vite-plugin-svelte] /Users/xxx/PycharmProjects/pythonProject/devikaTest/devika/ui/src/lib/components/ControlPanel.svelte:112:10 A11y: '#' is not a valid href attribute

Thanks in advance

**Comment by devparanjay** [comment]
Facing the same issue as well.

**Comment by PierrunoYT** [comment]
Same here

**Comment by thiyagab** [comment]
+1 anyone have a perfect run with this, please share screenshot or any missed steps.

**Comment by Atif1727** [comment]
yeah i am getting the same error how can i solve this?

**Comment by byakuyaxgara** [comment]
same issue

**Comment by lafintiger** [comment]
Same issue

**Comment by sime2408** [comment]
same

**Comment by feb-in** [comment]
same issue
