### ISSUE TITLE
Stuck at "I am browsing the web to research the following queries: . If I need anything, I will make sure to ask you."

### ISSUE THREAD

**Issue by bishaladhikari** [stitionai/devika#84]
### Problem
After installing and running the project with the OpenAI API key, the chat works fine but gets stuck while trying to browse the web. The browser window isn't showing anything. Any ideas on what might be causing this? Thanks!
 I waited for 10 minutes, seeing the backend it's keeps throwing the same response in a loop.

### Screenshot
<img width="1720" alt="Screenshot 2024-03-23 at 9 17 07 PM" src="https://github.com/stitionai/devika/assets/34532137/1da74fb0-2688-4bcb-829f-af9f8dfed806">

### Backend throwing same response in a loop
<img width="570" alt="Screenshot 2024-03-23 at 9 22 33 PM" src="https://github.com/stitionai/devika/assets/34532137/8b61a924-6072-4790-91f0-039f5a91f128">

**Comment by NinjaEde** [comment]
Have you entered your Bing API Key?

**Comment by bishaladhikari** [comment]
@NinjaEde 
Oh right! completely missed that. Thanks for your quick response!
