### ISSUE TITLE
Ollama WebUI Backend Required (Svelte Package Error)

### ISSUE THREAD

**Issue by blevlabs** [stitionai/devika#86]
```
SvelteKitError: Not found: /api/v1/
    at resolve (/home/blabs/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
    at resolve (/home/blabs/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
    at #options.hooks.handle (/home/blabs/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
    at Module.respond (/home/blabs/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40) {
  status: 404,
  text: 'Not Found'
}
12:05:16 PM [vite] page reload .svelte-kit/generated/server/internal.js
12:05:16 PM [vite] page reload .svelte-kit/generated/root.svelte
```

Also, unfortunately every time I boot the service I run into this issue. Ollama is running on my backend.

![image](https://github.com/stitionai/devika/assets/91391670/80b3a066-8289-41ee-9ce6-72f5a6c34182)

Any ideas to fix this?

**Comment by ARajgor** [comment]
fetch the latest changes. are you still facing the same issue.

**Comment by ARajgor** [comment]
> @ARajgor I'm facing the same issue with the latest changes. Any idea on the fix?
> ```
>   ➜  Local:   http://localhost:3000/
>   ➜  Network: use --host to expose
>   ➜  press h + enter to show help
> SvelteKitError: Not found: /api/v1/
>     at resolve (/Users/jnarayan/Documents/AI/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
>     at resolve (/Users/jnarayan/Documents/AI/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
>     at #options.hooks.handle (/Users/jnarayan/Documents/AI/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
>     at Module.respond (/Users/jnarayan/Documents/AI/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40) {
>   status: 404,
>   text: 'Not Found'
> ```

What the node version??

**Comment by jeyadevnarayanan** [comment]
> > @ARajgor I'm facing the same issue with the latest changes. Any idea on the fix?
> > ```
> >   ➜  Local:   http://localhost:3000/
> >   ➜  Network: use --host to expose
> >   ➜  press h + enter to show help
> > SvelteKitError: Not found: /api/v1/
> >     at resolve (/Users/jnarayan/Documents/AI/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:522:13)
> >     at resolve (/Users/jnarayan/Documents/AI/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:322:5)
> >     at #options.hooks.handle (/Users/jnarayan/Documents/AI/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/index.js:71:56)
> >     at Module.respond (/Users/jnarayan/Documents/AI/devika/ui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:40) {
> >   status: 404,
> >   text: 'Not Found'
> > ```
> 
> What the node version??

v18.16.0

**Comment by ARajgor** [comment]
@jeyadevnarayanan is it showing the UI?

**Comment by jeyadevnarayanan** [comment]
> @jeyadevnarayanan is it showing the UI?

So I just did a clean install of all the components and its working now. Thanks!
