### ISSUE TITLE
Multiple issues with Chat in UI and Model Response (empty messages in chat; stuck on "Waiting...").

### ISSUE THREAD

**Issue by devparanjay** [stitionai/devika#87]
_Thanks for this project._

I'm facing a few issues listed below and would appreciate some help. I don't mind working on them myself with some guidance from the project team.

1. The "step-by-step plan" is not showing up in the UI, along with another empty message.
The plan does show up in the terminal though, so I'm thinking it might just be a minor issue.
![image](https://github.com/stitionai/devika/assets/45117614/fe65a15b-17c9-4f58-8b13-1ac02018fc9c)

2. I've also never been able to progress beyond this stage -
![image](https://github.com/stitionai/devika/assets/45117614/9a21cf03-1f92-463c-8f46-5a641107c697)

3. This is also showing up in the terminal after a while -
![image](https://github.com/stitionai/devika/assets/45117614/6777ba7b-e46b-47d3-aed6-f43245077447)
`Token usage: 2106762
Invalid response from the model, trying again...
Token usage: 2126366`

I've tried with two different models, WizardCoder and Gemma with same results.

**Comment by pencilHackerDesign** [comment]
Facing the same issue on Mac, is there any fix for this?

**Comment by ARajgor** [comment]
fetch the latest changes. already fixed

**Comment by alex89607** [comment]
Not fixed with local LLM llama2 atleast

**Comment by Dygitz** [comment]
Also not working for me against ollama nor LMStudio
