### ISSUE TITLE
 Feature Request: Support Custom Base URL for OpenAI (Azure) Integration

### ISSUE THREAD

**Issue by syaikhipin** [stitionai/devika#89]
**Description:**

I'd like to request the addition of a feature that allows users to specify a custom base URL when interacting with OpenAI through this library/framework. This would enable integration with custom OpenAI deployments hosted on Azure or cater to specific security requirements.

**Motivation:**

Supporting custom base URLs would provide several benefits:

- Increased flexibility for users with private or on-premises OpenAI deployments.
- Enhanced compatibility with internal security policies that might restrict access to the default OpenAI API endpoint.
- Streamlined integration with existing workflows that involve custom OpenAI instances.

**Proposed Solution:**

One possible implementation could involve adding a configuration option like `baseUrl` when initializing the OpenAI client. This option would allow users to specify the desired base URL for API requests.

**Additional Considerations:**

- It would be important to validate the provided base URL to ensure it's a valid URL format.
- Error handling mechanisms should be in place to gracefully handle cases where the custom base URL is unreachable or returns errors.

**Labels:** feature-request, openai, azure

**Comment by segmentationf4u1t** [comment]
This can be overcomed with env variables
export OPENAI_BASE_URL=https://your.reverse.proxy.url/v1

**Comment by syaikhipin** [comment]
Thanks for the nice information

**Comment by pranaysahith** [comment]
@segmentationf4u1t I have set the following env vars, however I get `openai.NotFoundError` error when I send any message. 
```
export OPENAI_BASE_URL=https://xyz.openai.azure.com
export AZURE_OPENAI_ENDPOINT=https://xyz.openai.azure.com
export AZURE_OPENAI_API_KEY=xyz
export OPENAI_API_VERSION=2023-05-15
```

**Comment by segmentationf4u1t** [comment]
> /

Thats correct, azure might bring some troubles (im uncertain how does azure handle the openai api, specifically in terms of payload and response standards. It's important to note that the `OPENAI_BASE_URL` environment variable should be used primarily for reverse-proxies and/or inference structure clones for the BASE api model, as mentioned above.

**Comment by ARajgor** [comment]
https://github.com/stitionai/devika/pull/69
duplicate https://github.com/stitionai/devika/issues/55
