### ISSUE TITLE
Context limits? Plus no idea what the AI is doing.

### ISSUE THREAD

**Issue by Ph0rk0z** [stitionai/devika#96]
I used the DDG PR, not sure if the search is working. I set the AI to write me a python hello world. It came up with a plan. Now it's doing something.. it keeps generating and it has exhausted my 16k context limit.

The logs are full of repetition and I think you got debug stuck on as the messages cycle. I still can't get into settings on either chrome nor firefox and I can't delete projects. It's pretty cool but I think it still has a long way to go. The plans are really great but it seems to be stuck at executing them.

**Comment by Drlordbasil** [comment]
Hits here too, maybe we should add a sleep or wait function to properly not spam us with useless shit lol

**Comment by ARajgor** [comment]
you have to choose a model with a bigger context length for working devika in full mode. try gemini or gpt-4

**Comment by Ph0rk0z** [comment]
Is 32k not enough? Not all models, even API have the same context. It's not infinite.

**Comment by Drlordbasil** [comment]
32k limit isn't big enough yo think of shit properly without rag tbh

**Comment by Ph0rk0z** [comment]
Then lord help the people with ollama using this. Whole thing seems more of a way to sell people on APIs.
